
BG3_LOCATION_LIST = [
    ["CHA_Chapel-AccessedTemple", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-BanditTalking", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-BeachEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-ConfrontJergal", ["Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-ConnectedSarcophagusJergal", ["Crypt: Open Sarcophagus", "Crypt: Read Plaque", "Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-Exit", [], 0],
    ["CHA_Chapel-FoundSarcophagus_Opened", ["Crypt: Find Sarcophagus", "Crypt: Open Sarcophagus"], 0],
    ["CHA_Chapel-FoundSarcophagus_Sealed", ["Crypt: Find Sarcophagus"], 0],
    ["CHA_Chapel-HatchEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-JergalAtCamp", ["Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-LeftRegion", [], 0],
    ["CHA_Chapel-OpenedSarcophagus", ["Crypt: Open Sarcophagus"], 0],
    ["CHA_Chapel-ReadDruidBook", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-ReadSarcophagusPlaque", ["Crypt: Read Plaque"], 0],
    ["CHA_Chapel-ShadowheartMention", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-WeirdDoor", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-WeirdDoorEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_LaezelRecruit-AgreedToHelp", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-Attacked", [], 0],
    ["CHA_LaezelRecruit-AttackedAlt", [], 0],
    ["CHA_LaezelRecruit-DidntAgreeHelp", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-FailedIntimidation", [], 0],
    ["CHA_LaezelRecruit-FailedIntimidationAlt", [], 0],
    ["CHA_LaezelRecruit-FailedPersuasion", [], 0],
    ["CHA_LaezelRecruit-FailedPersuasionAlt", [], 0],
    ["CHA_LaezelRecruit-Freed", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-IntimidatedLeave", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-IntimidatedLeaveAlt", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-InvitedCamp", ["Beach-LZ: Get the Tieflings Away", "Beach-LZ: Recruit Lae'zel"], 0],
    ["CHA_LaezelRecruit-KilledLaezel", [], 0],
    ["CHA_LaezelRecruit-LaezelPermaDefeatead", [], 0],
    ["CHA_LaezelRecruit-LearnedCure", ["Beach-LZ: Talk to Lae'zel"], 0],
    ["CHA_LaezelRecruit-LeftArea", [], 0],
    ["CHA_LaezelRecruit-LeftAreaAfterRecruitment", [], 0],
    ["CHA_LaezelRecruit-Mindmelted", ["Beach-LZ: Talk to Lae'zel"], 0],
    ["CHA_LaezelRecruit-PersuadedKill", [], 0],
    ["CHA_LaezelRecruit-PersuadedKillAlt", [], 0],
    ["CHA_LaezelRecruit-PersuadedLeave", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-PersuadedLeaveAlt", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-Recruited", ["Beach-LZ: Get the Tieflings Away", "Beach-LZ: Recruit Lae'zel"], 0],
    ["CHA_LaezelRecruit-RefusedInvolvement", [], 0],
    ["CHA_LaezelRecruit-RefusedRecruit", [], 0],
    ["CHA_LaezelRecruit-ReleasedEarly", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-ReleasedEarlyAlt", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedLaezel", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedLaezelAlt", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedTieflings", [], 0],
    ["CHA_LaezelRecruit-Started", ["Beach-LZ: Find Lae'zel"], 0],
    ["CHA_LaezelRecruit-StartedAlt", ["Beach-LZ: Find Lae'zel"], 0],
    ["CHA_LaezelRecruit-TieflingsDefeated", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["DEN_HarpyMeal-DefeatedHarpies", ["Grove-Harpy: Defeat Harpies"], 0],
    ["DEN_HarpyMeal-DoneKidDied", [], 0],
    ["DEN_HarpyMeal-DoneKidFled_NoThank", [], 0],
    ["DEN_HarpyMeal-DoneLeftKid", [], 0],
    ["DEN_HarpyMeal-DoneNoInvestigation", [], 0],
    ["DEN_HarpyMeal-DoneStateChanged", [], 0],
    ["DEN_HarpyMeal-DoniFled", [], 0],
    ["DEN_HarpyMeal-DoniGone", [], 0],
    ["DEN_HarpyMeal-DoniShownWay", ["Grove-Harpy: Tell password to Doni"], 0],
    ["DEN_HarpyMeal-FoughtHarpies", ["Grove-Harpy: Defeat Harpies"], 0],
    ["DEN_HarpyMeal-FoundKid", ["Grove-Harpy: Find Child"], 0],
    ["DEN_HarpyMeal-GroveChanged", [], 0],
    ["DEN_HarpyMeal-HeardBeachSong", ["Grove-Harpy: Hear Harpy Song"], 0],
    ["DEN_HarpyMeal-InvestigateFoundDeadKid", [], 0],
    ["DEN_HarpyMeal-MetMol", ["Grove-Harpy: Meet Mol"], 0],
    ["DEN_HarpyMeal-MolGone", [], 0],
    ["DEN_HarpyMeal-ToldDragonLair_MetMol", ["Grove-Harpy: Tell password to Doni", "Grove-Harpy: Meet Mol"], 0],
    ["DEN_HarpyMeal-ToldDragonLair", ["Grove-Harpy: Discover Hideout Password"], 0],
    ["DEN_RobbedAdventurer-AdventurerDead", [], 0],
    ["DEN_RobbedAdventurer-FindLocket_KnockOut", [], 0],
    ["DEN_RobbedAdventurer-FindLocket_NoKnockOut", [], 0],
    ["DEN_RobbedAdventurer-FoundLocket_NoAccuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-FoundLocketChest_Accuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-FoundLocketKid_Accuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-GroveChanged", [], 0],
    ["DEN_RobbedAdventurer-NoConflictResolve", [], 0],
    ["DEN_RobbedAdventurer-NoLocketReturn", [], 0],
    ["DEN_RobbedAdventurer-ReturnedLocketFree", ["Grove-Locket: Return Locket"], 0],
    ["DEN_RobbedAdventurer-ReturnedLocketReward", ["Grove-Locket: Return Locket"], 0],
    ["DEN_SnakeCourt-EnteredLair", ["Grove-Snake: Learn about Arabella", "Grove-Snake: Find Arabella", "Grove-Kagha: Get past Guards"], 0],
    ["DEN_SnakeCourt-GroveChanged", [], 0],
    ["DEN_SnakeCourt-KidDied", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-KidDiedFirst", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-KidFreed", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-KidFreedFirst", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-LeftRegion", [], 0],
    ["DEN_SnakeCourt-MetParent", ["Grove-Snake: Learn about Arabella"], 0],
    ["DEN_SnakeCourt-ParentAutoReunited", [], 0],
    ["DEN_SnakeCourt-ParentDevastated", ["Grove-Snake: Talk to Arabella's Parents"], 0],
    ["DEN_SnakeCourt-ParentGone", [], 0],
    ["DEN_SnakeCourt-ParentLied", [], 0],
    ["DEN_SnakeCourt-ParentMovedOn", [], 0],
    ["DEN_SnakeCourt-ParentThankful", ["Grove-Snake: Talk to Arabella's Parents"], 0],
    ["DEN_SnakeCourt-SkippedHelp", [], 0],
    ["DEN_Thieflings-AlreadyKnowsMol", [], 0],
    ["DEN_Thieflings-BefriendedTieflings", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-DiscoveredRobbed", ["Grove-Thief: Discover Pickpocketing"], 0],
    ["DEN_Thieflings-DoneAngeredThieflings", [], 0],
    ["DEN_Thieflings-DoneLeftAct", [], 0],
    ["DEN_Thieflings-DoneOutsmartedKids", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-DoneTookGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-EnteredHideout", ["Grove-Thief: Learn About Hideout", "Grove-Thief: Enter Hideout"], 0],
    ["DEN_Thieflings-GivenGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-GivenSomeGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-GroveChanged", [], 0],
    ["DEN_Thieflings-KnowsMolAndHideout", [], 0],
    ["DEN_Thieflings-KnowsMolLeader", [], 0],
    ["DEN_Thieflings-RefusedPayGoods", [], 0],
    ["DEN_Thieflings-ToldHideout", ["Grove-Thief: Learn About Hideout"], 0],
    ["DEN_Thieflings-ToldRobbed", ["Grove-Thief: Discover Pickpocketing"], 0],
    ["DEN_Thieflings-TriedSmallEntrance", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-Apprentice_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticeDied_BeforeTadpoled", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticeDied_Tadpoled", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticePersuaded", ["Tadpole-Nettie: Be Poisoned by Nettie", "Tadpole-Nettie: Learn about Antidote", "Tadpole-Nettie: Cure the Poison"], 0],
    ["GLO_Tadpole_SUB_Apprentice-CuredApprenticePoison", ["Tadpole-Nettie: Cure the Poison"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedAboutNettie", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedCureDaleland", ["Tadpole-Nettie: Learn about Antidote"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedCureSwD", ["Tadpole-Nettie: Learn about Antidote"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedNettieNearby_NoName", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedNettieNearby", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-PoisonedByApprentice", ["Tadpole-Nettie: Be Poisoned by Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-SavedHalsin_BeforeTadpoled", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ToldAboutTadpole", ["Tadpole-Nettie: Talk to Nettie"], 0],
    ["HIDDEN_BGO_Boosters-WYR_FigaroSister_FinishedNaaberDialog", [], 0],
    ["HIDDEN_BGO_Boosters-WYR_MerchantsHouse_ChasingOut", [], 0],
    ["HIDDEN_BGO_Boosters-WYR_NymphGrotto_Bliss", [], 0],
    ["HIDDEN_BGO_Boosters-WYR_NymphGrotto_Rapture", [], 0],
    ["HIDDEN_BGO_Boosters-WYR_SmugglersCave_HelpedTheGuild", [], 0],
    ["HIDDEN_BGO_Boosters-WYR_Wyrmway_SolvedTrials", [], 0],
    ["HIDDEN_CRE_Boosters-CRE_WeaponsPuzzle_SolvedPuzzle", [], 0],
    ["HIDDEN_CRE_Boosters-CRE_YouthTraining_BoySpared", [], 0],
    ["HIDDEN_CRE_Boosters-CRE_YouthTraining_SavedKid", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_BloodMerchantLair_DrinkPotion", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Bonecloak_CatForDerryth", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_1", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_2", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_3", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_4", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_5", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_6", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_7", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_CountingHouse_VipVault_8", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_DjinniTrap_Escaped", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Elfsong_BuyCollar", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_ForsakenSkull", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_BartenderStalker", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey1", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey2", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey3", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey4", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey5", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey6", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey7", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey8", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_Bursar_GiveKey9", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_Guildhall_DeliveredZhentShipment", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_HagSurvivors_DefeatSquatterBandits", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_KurwinCoffin_BereavedCouple", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_KurwinCoffin_BuriedMan", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SahuaginAttack_SavedCivilians", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SerialKiller_DevellaReward", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SerialKiller_HighberrysBooster", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SorcerousSundries_KarsusBook", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SorcerousSundries_SeelieBook", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SorcerousSundries_StrategyBook", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_SteepEvacuation_ConvincedCaptain", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_TheLodge_EnterSecretRoom", [], 0],
    ["HIDDEN_CTY_Boosters-LOW_VoloFate_SavedVolo", [], 0],
    ["HIDDEN_HAG_Reward-HagReward", [], 0],
    ["HIDDEN_SCL_Boosters-SCL_DevilishOx_LeftOxBe", [], 0],
    ["HIDDEN_SCL_Boosters-SCL_NightsongPrison_Weapon", [], 0],
    ["HIDDEN_SCL_Boosters-SCL_OliversShadow_WonHideAndSeek", [], 0],
    ["HIDDEN_TUT_Boosters-TUT_Lab_ExtractedIntDev", [], 0],
    ["HIDDEN_WLD_Boosters-CAMP_Courier_Tamed", [], 0],
    ["HIDDEN_WLD_Boosters-CAMP_OwlbearCub_Tamed", [], 0],
    ["HIDDEN_WLD_Boosters-CHA_Chapel_BanditTalking", [], 0],
    ["HIDDEN_WLD_Boosters-CRA_Escape_SavedThralls", [], 0],
    ["HIDDEN_WLD_Boosters-CRA_Escape_ThrallsDied", [], 0],
    ["HIDDEN_WLD_Boosters-CRA_HarperBooster_Looted", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Confrontation_PersuadedAradin", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_DruidLair_OpenedVault", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_ElevatorBear_Moved", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_GoblinScouts_SavedDruid", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_GruntingKid_Persuaded", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_IrritatedTiefling_Trained", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_OxHayStack_Looted", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Prodigy_Persuaded", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Stargazing_Rescued", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Thieflings_BefriendedMol", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Thieflings_PersuadedAdventurer", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Thieflings_PersuadedKid", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_Thieflings_PersuadedPickpocket", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_TieflingBard_Helped", [], 0],
    ["HIDDEN_WLD_Boosters-DEN_ZenBear_Helped", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_Backpack_SucceededCheck", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_GoblinAmbush_Persuaded", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_KnifeMeat_SucceededCheck", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_PriestOfTheConqueringGod_Commanded", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_SeluneStash_Opened", [], 0],
    ["HIDDEN_WLD_Boosters-FOR_ThayanCellar_OpenMirror", [], 0],
    ["HIDDEN_WLD_Boosters-GLO_BookOfRestoredGods_Opened", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_ChickenChase_Won", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_DrunkGoblin_StoleRing", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_DrunkGoblin_WonDuel", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_GoblinKing_Performed", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_GoblinPriest_Brand", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_GoblinToast_Poisoned", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_Heretic_Saved", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_NerdyGoblinSage_GotBook", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_PainPriest_Penanced", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_SpiderNest_Saved", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_TempleAccess_Solved", [], 0],
    ["HIDDEN_WLD_Boosters-GOB_Torturers_Freed", [], 0],
    ["HIDDEN_WLD_Boosters-HAG_FairyRing_OpenedSwamp", [], 0],
    ["HIDDEN_WLD_Boosters-HAG_FairyRing_OpenedUnderdark", [], 0],
    ["HIDDEN_WLD_Boosters-HAG_FairyRing_OpenedWaterfall", [], 0],
    ["HIDDEN_WLD_Boosters-HAG_FairyRing_OpenedWorkshop", [], 0],
    ["HIDDEN_WLD_Boosters-ORI_Gale_Freed", [], 0],
    ["HIDDEN_WLD_Boosters-PLA_GithChokepoint_Fooled", [], 0],
    ["HIDDEN_WLD_Boosters-PLA_Tavern_CalmedOx", [], 0],
    ["HIDDEN_WLD_Boosters-PLA_ZhentCache_SucceededCheck", [], 0],
    ["HIDDEN_WLD_Boosters-PLA_ZhentDungeon_Persuaded", [], 0],
    ["HIDDEN_WLD_Boosters-UND_ArcaneTower_Activated", [], 0],
    ["HIDDEN_WLD_Boosters-UND_ArcaneTower_PetGrave", [], 0],
    ["HIDDEN_WLD_Boosters-UND_ChestOfMundane_Identified", [], 0],
    ["HIDDEN_WLD_Boosters-UND_DeadInTheWater_AcquiredTrinket", [], 0],
    ["HIDDEN_WLD_Boosters-UND_DuergarCamp_FirewallTraps_ReachedEnd", [], 0],
    ["HIDDEN_WLD_Boosters-UND_DuergarCamp_Stonemason_SucceededChecks", [], 0],
    ["HIDDEN_WLD_Boosters-UND_HarperSpy_OpenedStash", [], 0],
    ["HIDDEN_WLD_Boosters-UND_HarperSpy_OpenedStashAvoidedMimics", [], 0],
    ["HIDDEN_WLD_Boosters-UND_KuoToaGod_Blessed", [], 0],
    ["HIDDEN_WLD_Boosters-UND_MerregonMask_FoundAll", [], 0],
    ["HIDDEN_WLD_Boosters-UND_MonkAmulet_SparedLavaElemental", [], 0],
    ["HIDDEN_WLD_Boosters-UND_MyconidCircle_InjuredGnome_ReportedGrymforgeFate", [], 0],
    ["HIDDEN_WLD_Boosters-UND_SpiderEvangelical_PersuadedLeave", [], 0],
    ["HIDDEN_WLD_Boosters-UND_SwordInStone_SucceededCheck", [], 0],
    ["HIDDEN_WLD_Boosters-UND_WormWall_SucceededCheck", [], 0],
    ["HIDDEN_WLD_Rewards-DEN_Squirrel_Reward", [], 0],
    ["HIDDEN_WLD_Rewards-TEST_Reward_01", [], 0],
    ["HIDDEN_WLD_Rewards-UND_ArcaneTower_SecretRing", [], 0],
    ["ORI_Avatar_Astarion-Act1LeftReveal", [], 0],
    ["ORI_Avatar_Astarion-Ascended", [], 0],
    ["ORI_Avatar_Astarion-Bite_Animal", [], 0],
    ["ORI_Avatar_Astarion-Bite_Avatar_Failure", [], 0],
    ["ORI_Avatar_Astarion-Bite_CompanionLeft", [], 0],
    ["ORI_Avatar_Astarion-Bite_Gale_KnowsBomb", [], 0],
    ["ORI_Avatar_Astarion-Bite_Gale_NoBomb", [], 0],
    ["ORI_Avatar_Astarion-Bite_Lie_Success", [], 0],
    ["ORI_Avatar_Astarion-Bite_Reveal_Success", [], 0],
    ["ORI_Avatar_Astarion-Bite_Stealth_HalfDrain", [], 0],
    ["ORI_Avatar_Astarion-Bite_Stealth_Murder", [], 0],
    ["ORI_Avatar_Astarion-CazadorInCoffin", [], 0],
    ["ORI_Avatar_Astarion-EnteredDungeon", [], 0],
    ["ORI_Avatar_Astarion-EnteredPalace", [], 0],
    ["ORI_Avatar_Astarion-FirstDream", [], 0],
    ["ORI_Avatar_Astarion-FoundCazador_NoRitual", [], 0],
    ["ORI_Avatar_Astarion-FoundCazador_Ritual", [], 0],
    ["ORI_Avatar_Astarion-GameplayBiteReveal", [], 0],
    ["ORI_Avatar_Astarion-HelpedOrthon", [], 0],
    ["ORI_Avatar_Astarion-KilledOrhon", [], 0],
    ["ORI_Avatar_Astarion-KilledPrisoners", [], 0],
    ["ORI_Avatar_Astarion-LearnedRitual", [], 0],
    ["ORI_Avatar_Astarion-LearnedStaff", [], 0],
    ["ORI_Avatar_Astarion-LeftPrisoners", [], 0],
    ["ORI_Avatar_Astarion-LeftToEND", [], 0],
    ["ORI_Avatar_Astarion-MetAmbushSpawns_Failed", [], 0],
    ["ORI_Avatar_Astarion-MetAmbushSpawns_Succeeded_DEPRECATED", [], 0],
    ["ORI_Avatar_Astarion-MetAmbushSpawns_Succeeded", [], 0],
    ["ORI_Avatar_Astarion-MetFlophouseSpawns_Ritual", [], 0],
    ["ORI_Avatar_Astarion-MetFlophouseSpawns", [], 0],
    ["ORI_Avatar_Astarion-MetGurHunter_LearnedEmployer", [], 0],
    ["ORI_Avatar_Astarion-MetGurHunter_Murder", [], 0],
    ["ORI_Avatar_Astarion-MetGurHunter", [], 0],
    ["ORI_Avatar_Astarion-MetRaphaelHaven_NoInfo", [], 0],
    ["ORI_Avatar_Astarion-MetRaphaelHaven", [], 0],
    ["ORI_Avatar_Astarion-MetRaphaelMasoleum", [], 0],
    ["ORI_Avatar_Astarion-MetSebastian", [], 0],
    ["ORI_Avatar_Astarion-RaphaelLeftNoInfo", [], 0],
    ["ORI_Avatar_Astarion-ReachedBG", [], 0],
    ["ORI_Avatar_Astarion-ReleasedPrisoners", [], 0],
    ["ORI_Avatar_Astarion-ScarsRevealed", [], 0],
    ["ORI_Avatar_Astarion-SecondDream", [], 0],
    ["ORI_Avatar_Astarion-Start", [], 0],
    ["ORI_Avatar_Astarion-TruthReveal", [], 0],
    ["ORI_Avatar_Astarion-Ulma_Dead", [], 0],
    ["ORI_Avatar_Astarion-Ulma_GurHostile", [], 0],
    ["ORI_Avatar_Astarion-Ulma_GurPeace", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-Ceremony", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-DevilsFee", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-Execution", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-MistressOfSouls", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-ORI_Avatar_DarkUrge_OldFriends_End", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-Pod", [], 0],
    ["ORI_Avatar_DarkUrge_OldFriends-WallTentacle", [], 0],
    ["ORI_Avatar_DarkUrge-AlfiraKilled_Reward", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalDisappointed", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalLost", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalResisted_BrainDestroyed", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalResisted", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalWon_BrainSubjugated", [], 0],
    ["ORI_Avatar_DarkUrge-BhaalWon", [], 0],
    ["ORI_Avatar_DarkUrge-Bloodwedding", [], 0],
    ["ORI_Avatar_DarkUrge-ButlerAppearance_FailedBard", [], 0],
    ["ORI_Avatar_DarkUrge-ButlerAppearance", [], 0],
    ["ORI_Avatar_DarkUrge-FailedKillAlfira", [], 0],
    ["ORI_Avatar_DarkUrge-FailedKillBardBackup", [], 0],
    ["ORI_Avatar_DarkUrge-FirstNight", [], 0],
    ["ORI_Avatar_DarkUrge-IndulgedUrges", [], 0],
    ["ORI_Avatar_DarkUrge-IsobelKillOrder", [], 0],
    ["ORI_Avatar_DarkUrge-KilledAlfira", [], 0],
    ["ORI_Avatar_DarkUrge-KilledBardBackup", [], 0],
    ["ORI_Avatar_DarkUrge-KilledCompanion", [], 0],
    ["ORI_Avatar_DarkUrge-KilledIsobel", [], 0],
    ["ORI_Avatar_DarkUrge-OtherKilledIsobel", [], 0],
    ["ORI_Avatar_DarkUrge-ResistedIsobelUrge", [], 0],
    ["ORI_Avatar_DarkUrge-ResistedUrges", [], 0],
    ["ORI_Avatar_DarkUrge-SawUrges", [], 0],
    ["ORI_Avatar_DarkUrge-SparedIsobel", [], 0],
    ["ORI_Avatar_DarkUrge-SparedIsobelAndCompanion", [], 0],
    ["ORI_Avatar_DarkUrge-Start", [], 0],
    ["ORI_Avatar_Gale_Letter-DestroyedPouch", [], 0],
    ["ORI_Avatar_Gale_Letter-GaleDied", [], 0],
    ["ORI_Avatar_Gale_Letter-GotScroll", [], 0],
    ["ORI_Avatar_Gale_Letter-LearnedFlute", [], 0],
    ["ORI_Avatar_Gale_Letter-LearnedMephit", [], 0],
    ["ORI_Avatar_Gale_Letter-LearnedPouch", [], 0],
    ["ORI_Avatar_Gale_Letter-OpenedPouch", [], 0],
    ["ORI_Avatar_Gale_Letter-PlayedNotes", [], 0],
    ["ORI_Avatar_Gale_Letter-PrematureProjectionEnd", [], 0],
    ["ORI_Avatar_Gale_Letter-ResurrectedGale", [], 0],
    ["ORI_Avatar_Gale_MagicCircle-Crafted", [], 0],
    ["ORI_Avatar_Gale_MagicCircle-Destroyed", [], 0],
    ["ORI_Avatar_Gale_MagicCircle-FoundCircle", [], 0],
    ["ORI_Avatar_Gale_MagicCircle-MagicCircle_Act3", [], 0],
    ["ORI_Avatar_Gale-BecameGodOfAmbition", [], 0],
    ["ORI_Avatar_Gale-BookHintInvisibility1", [], 0],
    ["ORI_Avatar_Gale-BookHintInvisibility2", [], 0],
    ["ORI_Avatar_Gale-BookHintInvisibility3", [], 0],
    ["ORI_Avatar_Gale-BookHintPath", [], 0],
    ["ORI_Avatar_Gale-ChallengedMystra", [], 0],
    ["ORI_Avatar_Gale-ContractAfterDelayedMystra", [], 0],
    ["ORI_Avatar_Gale-ContractAfterPromisedMystra", [], 0],
    ["ORI_Avatar_Gale-ContractAfterRefusedMystra", [], 0],
    ["ORI_Avatar_Gale-DelayedMystra", [], 0],
    ["ORI_Avatar_Gale-DestroyedContract", [], 0],
    ["ORI_Avatar_Gale-DiedAttemptingToBecomeGod", [], 0],
    ["ORI_Avatar_Gale-ElminsterBrief", [], 0],
    ["ORI_Avatar_Gale-EmperorIllithid_NoBook", [], 0],
    ["ORI_Avatar_Gale-EmperorIllithid", [], 0],
    ["ORI_Avatar_Gale-EndGame_NoBook", [], 0],
    ["ORI_Avatar_Gale-EndGame_SkippedMystra", [], 0],
    ["ORI_Avatar_Gale-EnteredOffice", [], 0],
    ["ORI_Avatar_Gale-Exploded", [], 0],
    ["ORI_Avatar_Gale-FailedDominateBrain_NoBook", [], 0],
    ["ORI_Avatar_Gale-FailedDominateBrain", [], 0],
    ["ORI_Avatar_Gale-FindBook_Book", [], 0],
    ["ORI_Avatar_Gale-FindBook_Raphael", [], 0],
    ["ORI_Avatar_Gale-FindBook", [], 0],
    ["ORI_Avatar_Gale-FindBook2", [], 0],
    ["ORI_Avatar_Gale-FoundBook", [], 0],
    ["ORI_Avatar_Gale-GaleIllithid_NoBook", [], 0],
    ["ORI_Avatar_Gale-GaleIllithid", [], 0],
    ["ORI_Avatar_Gale-GaveCrownToMystra_InElysium", [], 0],
    ["ORI_Avatar_Gale-GaveCrownToMystra_MystrasChosen", [], 0],
    ["ORI_Avatar_Gale-GaveCrownToMystra_NotSpeaking", [], 0],
    ["ORI_Avatar_Gale-GotItem1", [], 0],
    ["ORI_Avatar_Gale-GotItem2", [], 0],
    ["ORI_Avatar_Gale-GotItem3", [], 0],
    ["ORI_Avatar_Gale-KarlachIllithid_NoBook", [], 0],
    ["ORI_Avatar_Gale-KarlachIllithid", [], 0],
    ["ORI_Avatar_Gale-KarsiteWeave", [], 0],
    ["ORI_Avatar_Gale-MeetElminster", [], 0],
    ["ORI_Avatar_Gale-MeetElminsterCTY", [], 0],
    ["ORI_Avatar_Gale-MissedBrain", [], 0],
    ["ORI_Avatar_Gale-MissedDominatebrain_NoBook", [], 0],
    ["ORI_Avatar_Gale-MissedDominatebrain", [], 0],
    ["ORI_Avatar_Gale-MystraRequest", [], 0],
    ["ORI_Avatar_Gale-MystraWithContract", [], 0],
    ["ORI_Avatar_Gale-NeedItem1", [], 0],
    ["ORI_Avatar_Gale-NeedItem2", [], 0],
    ["ORI_Avatar_Gale-NeedItem3", [], 0],
    ["ORI_Avatar_Gale-NoContractAfterMystra", [], 0],
    ["ORI_Avatar_Gale-NoTolna", [], 0],
    ["ORI_Avatar_Gale-OpenedPortal", [], 0],
    ["ORI_Avatar_Gale-OrpheusIllithid_NoBook", [], 0],
    ["ORI_Avatar_Gale-OrpheusIllithid", [], 0],
    ["ORI_Avatar_Gale-PromiseMystra", [], 0],
    ["ORI_Avatar_Gale-ReadNotes", [], 0],
    ["ORI_Avatar_Gale-RefusedMystra", [], 0],
    ["ORI_Avatar_Gale-SawBrain", [], 0],
    ["ORI_Avatar_Gale-Start", [], 0],
    ["ORI_Avatar_Gale-TeleportedToVault1", [], 0],
    ["ORI_Avatar_Gale-TeleportedToVault2", [], 0],
    ["ORI_Avatar_Gale-TolnaDirectedOffice", [], 0],
    ["ORI_Avatar_Gale-TolnaMentionedVault", [], 0],
    ["ORI_Avatar_Gale-TolnaRefusedVault", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-DammonFound_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-DammonFound_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-DammonNeverMet", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-DammonPermadefeated", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindDammon_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindDammon_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_FirstUpgrade_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_FirstUpgrade_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_FirstUpgrade", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_SecondUpgrade_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_SecondUpgrade_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-ForgingOfTheHeart_ReachEND", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-GetFirstUpgrade_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-GetFirstUpgrade_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-GetFirstUpgrade", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-GetSecondUpgrade_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-GetSecondUpgrade_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-KarlachFullyUpgraded_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-KarlachFullyUpgraded_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-TalkToDammon_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-TalkToDammon_Act3", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-TieflingsLeft", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-WaitForNextAct", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-WaitForNextDay_Act2", [], 0],
    ["ORI_Avatar_Karlach_SUB_ForgingOfTheHeart-WaitForNextDay_Act3", [], 0],
    ["ORI_Avatar_Karlach-Act2PointOfNoReturn", [], 0],
    ["ORI_Avatar_Karlach-AvernusEscaped", [], 0],
    ["ORI_Avatar_Karlach-DealWithPaladins", [], 0],
    ["ORI_Avatar_Karlach-EscapeAvernus", [], 0],
    ["ORI_Avatar_Karlach-ExploreSwordCoast", [], 0],
    ["ORI_Avatar_Karlach-ForgingOfTheHeart", [], 0],
    ["ORI_Avatar_Karlach-GetUpgrades_DoesKnowDammon", [], 0],
    ["ORI_Avatar_Karlach-GetUpgrades_DoesNotKnowDammon", [], 0],
    ["ORI_Avatar_Karlach-GoToGortashCorpse", [], 0],
    ["ORI_Avatar_Karlach-KillGortash", [], 0],
    ["ORI_Avatar_Karlach-MetGortashInCOL_KarlachPresent", [], 0],
    ["ORI_Avatar_Karlach-ReachEND_FullyUpgraded_GortashDefeated", [], 0],
    ["ORI_Avatar_Karlach-ReachEND_FullyUpgraded_GortashNotDefeated", [], 0],
    ["ORI_Avatar_Karlach-ReachEND_NotFullyUpgraded_GortashDefeated", [], 0],
    ["ORI_Avatar_Karlach-ReachEND_NotFullyUpgraded_GortashNotDefeated", [], 0],
    ["ORI_Avatar_Karlach-SaveTheCity", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-OrpheusFreed_OrpheusMF", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-OrpheusFreed_OrpheusNotMF", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-OrpheusKilled", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-OrpheusSacrificesHimself", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-OrpheusStartsRebellion", [], 0],
    ["ORI_Avatar_Laezel_SUB_OrpheusFuture-VlaakithVisitedInCampOrpheus", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-OrpheusFreed", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-OrpheusKilled", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-OrpheusKilledDuringCombatOver", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-OrpheusSelfSacrifice", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-OrpheusStartsRebellion", [], 0],
    ["ORI_Avatar_Laezel_SUB_VlaakithFuture-VlaakithVisitedInCampVlaakith", [], 0],
    ["ORI_Avatar_Laezel-AgreedVoss", [], 0],
    ["ORI_Avatar_Laezel-AskedZevlorAboutZorru", [], 0],
    ["ORI_Avatar_Laezel-AttackedVossGotHammer", [], 0],
    ["ORI_Avatar_Laezel-BackToInquisitor_InquisitorDead", [], 0],
    ["ORI_Avatar_Laezel-ChokepointCombatStarted", [], 0],
    ["ORI_Avatar_Laezel-ChokepointDefeated", [], 0],
    ["ORI_Avatar_Laezel-CrecheDestroyed_NothingDone", [], 0],
    ["ORI_Avatar_Laezel-CrecheDestroyed_ZaithiskDoneVlaakithNotDone", [], 0],
    ["ORI_Avatar_Laezel-CrecheDestroyed_ZaithiskNotDoneVlaakithDone", [], 0],
    ["ORI_Avatar_Laezel-CrecheFinished", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_OrpheusPath_OrpheusAlive", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_OrpheusPath_OrpheusDead", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_OtherEnding", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_Romance", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_VlaakithPath", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_WanderFaerun_ChoseToStay", [], 0],
    ["ORI_Avatar_Laezel-DecideEnding_WanderFaerun_FailedMission", [], 0],
    ["ORI_Avatar_Laezel-DefeatedDoctor", [], 0],
    ["ORI_Avatar_Laezel-DefeatInquisitor_AfterAstral", [], 0],
    ["ORI_Avatar_Laezel-DiscussTadpole_NoHammer", [], 0],
    ["ORI_Avatar_Laezel-DiscussTadpole_WithHammer", [], 0],
    ["ORI_Avatar_Laezel-EnteredArtefact", [], 0],
    ["ORI_Avatar_Laezel-EnteredAstralPlane_NoHammer", [], 0],
    ["ORI_Avatar_Laezel-EnteredAstralPlane_WithHammer", [], 0],
    ["ORI_Avatar_Laezel-EnteredCreche", [], 0],
    ["ORI_Avatar_Laezel-EnteredHoH", [], 0],
    ["ORI_Avatar_Laezel-FindCure_AfterBetrayal", [], 0],
    ["ORI_Avatar_Laezel-FindCure_LeftRoomAfterVlaakithCommand", [], 0],
    ["ORI_Avatar_Laezel-FinishedIntermezzo_VossContact", [], 0],
    ["ORI_Avatar_Laezel-FinishedIntermezzo_VossInSC", [], 0],
    ["ORI_Avatar_Laezel-FinishedIntermezzo_VossNotPresent", [], 0],
    ["ORI_Avatar_Laezel-FoundCrecheLocationNoHints", [], 0],
    ["ORI_Avatar_Laezel-FoundCrecheLocationWithHints", [], 0],
    ["ORI_Avatar_Laezel-FoundInfirmary", [], 0],
    ["ORI_Avatar_Laezel-FoundOutAboutZorru", [], 0],
    ["ORI_Avatar_Laezel-GotHammer_VossInSC", [], 0],
    ["ORI_Avatar_Laezel-GotHammer_VossInSewers", [], 0],
    ["ORI_Avatar_Laezel-GotHammer_VossNotPresent", [], 0],
    ["ORI_Avatar_Laezel-GotHammerFromRaphaelInAstralPlane", [], 0],
    ["ORI_Avatar_Laezel-GotNoInfoFromZorru", [], 0],
    ["ORI_Avatar_Laezel-GotNoInfoFromZorruWithoutKnowingHim", [], 0],
    ["ORI_Avatar_Laezel-HammerForceFieldDisabled", [], 0],
    ["ORI_Avatar_Laezel-InCrecheRegionWIthHints", [], 0],
    ["ORI_Avatar_Laezel-KilledKetheric", [], 0],
    ["ORI_Avatar_Laezel-KilledVoss", [], 0],
    ["ORI_Avatar_Laezel-KilledVossGotHammer", [], 0],
    ["ORI_Avatar_Laezel-KilledVossNoHammer", [], 0],
    ["ORI_Avatar_Laezel-LearnedAboutKeyFromRaphael_VossInSC", [], 0],
    ["ORI_Avatar_Laezel-LearnedAboutKeyFromRaphael_VossNotPresent", [], 0],
    ["ORI_Avatar_Laezel-LearnedAboutOrphicHammer_AlreadyInHoH", [], 0],
    ["ORI_Avatar_Laezel-LearnedAboutOrphicHammer", [], 0],
    ["ORI_Avatar_Laezel-LeftRoomAfterVlaakithCommand", [], 0],
    ["ORI_Avatar_Laezel-PermaDefeatedCheckpointGuardsInCreche", [], 0],
    ["ORI_Avatar_Laezel-PermaDefeatedGithyankiAtGates", [], 0],
    ["ORI_Avatar_Laezel-PermaDefeatInquisitor", [], 0],
    ["ORI_Avatar_Laezel-PointOfNoReturnReachedWithoutCreche", [], 0],
    ["ORI_Avatar_Laezel-ReadCrecheMap", [], 0],
    ["ORI_Avatar_Laezel-ResolvedAstralPrism_OrpheusAssimilated", [], 0],
    ["ORI_Avatar_Laezel-ResolvedAstralPrism_OrpheusFree", [], 0],
    ["ORI_Avatar_Laezel-ResolvedPeaceCreche", [], 0],
    ["ORI_Avatar_Laezel-ResolvedPeaceNoCreche", [], 0],
    ["ORI_Avatar_Laezel-SawDragonRider_KnowsAboutGithyankiPatrol", [], 0],
    ["ORI_Avatar_Laezel-SawDragonRider", [], 0],
    ["ORI_Avatar_Laezel-SawGithyankiAtGates_DoesNotKnowLocation", [], 0],
    ["ORI_Avatar_Laezel-SawGithyankiAtGates_KnowsLocation", [], 0],
    ["ORI_Avatar_Laezel-SawHammer", [], 0],
    ["ORI_Avatar_Laezel-SentToInfirmary", [], 0],
    ["ORI_Avatar_Laezel-ShowedVossHammer", [], 0],
    ["ORI_Avatar_Laezel-SpeakToRaphael", [], 0],
    ["ORI_Avatar_Laezel-SpokeToDaisy", [], 0],
    ["ORI_Avatar_Laezel-SpokeToDoctor_NotWaiting", [], 0],
    ["ORI_Avatar_Laezel-SpokeToDoctor_WaitingAtDevice", [], 0],
    ["ORI_Avatar_Laezel-SpokeToVlaakith", [], 0],
    ["ORI_Avatar_Laezel-SpokeToVossInSC", [], 0],
    ["ORI_Avatar_Laezel-Start", [], 0],
    ["ORI_Avatar_Laezel-TalkedToDeadTiefling", [], 0],
    ["ORI_Avatar_Laezel-UsedDevice_LaezelUsedIt", [], 0],
    ["ORI_Avatar_Laezel-UsedDevice_OtherUsedIt", [], 0],
    ["ORI_Avatar_Laezel-VossContact", [], 0],
    ["ORI_Avatar_Laezel-ZorruDied", [], 0],
    ["ORI_Avatar_Laezel-ZorruLeft", [], 0],
    ["ORI_Avatar_Laezel-ZorruMarkedMap", [], 0],
    ["ORI_Avatar_Laezel-ZorruMarkedMapWithoutKnowingAboutHim", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-BalthazarFight", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-CompletedCloneTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-CompletedDarknessTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-CompletedStealthTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-CompletedTrials", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-DeepShadowCurse", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-EnteredSanctum_Alt", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-EnteredShadowfell_Balthazar", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-EnteredShadowfell_NoBalthazar", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundCloneTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundDarknessTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundSharTemple_Alt", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundSharTemple", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundStealthTrial", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-FoundTrials", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-HadCommunion_NoSpear", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-HadCommunion_Spear", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-HadWaterCommunion_NoSpear", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-HadWaterCommunion_Spear", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_CityCorpses_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_CityCorpses_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Halsin_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Halsin_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Murals_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Murals_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Selune_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_Selune_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_ShadowCurse_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_ShadowCurse_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_SharIdol_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_SharIdol_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TempleApproach_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TempleApproach_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TempleVista_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TempleVista_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TownCorpses_Start", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-JusticiarHint_TownCorpses_Update", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-LootedSpearOfNight_Communion", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-LootedSpearOfNight_WaterCommunion", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-Nightsong_Killed", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-Nightsong_Spared", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-Nightsong_Surrendered", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_ChosenOfShar-SharSpoke", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-EnemyOfShar_MetNocturne", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-EnteredLowerCity", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-ForgotNocturne", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-KilledNocturne", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-NeverFoundNocturne", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-NoblestalkMemory", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-SharPath_MetNocturne", [], 0],
    ["ORI_Avatar_ShadowHeart_SUB_OldFriend-TalkedtoHandler", [], 0],
    ["ORI_Avatar_ShadowHeart-AbsoluteBox", [], 0],
    ["ORI_Avatar_ShadowHeart-CampFight_LaezelDied", [], 0],
    ["ORI_Avatar_ShadowHeart-CampFight_Peace", [], 0],
    ["ORI_Avatar_ShadowHeart-ConfessedSharran_Alt", [], 0],
    ["ORI_Avatar_ShadowHeart-ConfessedSharran", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_ArrivedInWYR", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_DefeatedViconia", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_EnteredLossChamber", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_GainEntry_Alt", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_GainEntry", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_KilledParents", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_LearnedCultLocation", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_MetViconia", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_NeverSavedParents", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_NightsongMeeting", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_ParentsSceneBroken", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_SavedParents", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_SharWrath", [], 0],
    ["ORI_Avatar_ShadowHeart-EnemyOfShar_ViconiaFight", [], 0],
    ["ORI_Avatar_ShadowHeart-FoundGithPatrol", [], 0],
    ["ORI_Avatar_ShadowHeart-FoundJusticiarHint", [], 0],
    ["ORI_Avatar_ShadowHeart-HaveJusticiarSuspicion", [], 0],
    ["ORI_Avatar_ShadowHeart-IncurableWound_FirstFlare", [], 0],
    ["ORI_Avatar_ShadowHeart-IncurableWound_Introspection", [], 0],
    ["ORI_Avatar_ShadowHeart-KilledNightsong", [], 0],
    ["ORI_Avatar_ShadowHeart-SeenBoxInsides", [], 0],
    ["ORI_Avatar_ShadowHeart-SeenShadowCurse", [], 0],
    ["ORI_Avatar_ShadowHeart-SeenWolfDream", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_ArrivedInWYR", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_DefeatedKetheric", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_DefeatedViconia", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_EnteredLossChamber", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_GainEntry_Alt", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_GainEntry", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_KilledParents", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_LearnedCultLocation", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_MetViconia", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_NeverCompletedPurge", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_ParentsSceneBroken", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_SavedParents", [], 0],
    ["ORI_Avatar_ShadowHeart-SharPath_ViconiaFight", [], 0],
    ["ORI_Avatar_ShadowHeart-SharTemple", [], 0],
    ["ORI_Avatar_ShadowHeart-SparedNightsong", [], 0],
    ["ORI_Avatar_ShadowHeart-Start", [], 0],
    ["ORI_Avatar_ShadowHeart-SurrenderedNightsong", [], 0],
    ["ORI_Avatar_ShadowHeart-VoiceOfAbsolute", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-BrokenAbandoned", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-BrokenDied", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-BrokenEscort", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-CouncillorDead", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-CouncillorDeadKnown", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-CouncillorRefused", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-CouncillorTalked", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-CouncillorTalkedKnowsMT", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-Died", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-DiedIRN", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-FoundDeadInIRN", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-InnReached", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-Kidnapped", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-LearnedRavengardDiedInIRNDestruction", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-LearntMT", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-LeftAct_Duke", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-LeftWithoutSeeingDeadRavengard", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-MizoraAtCamp", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-PactBroken", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-PactedEscort", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-PactedHint", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-PactedTalked", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-ReachedIRN", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-ReachedMT", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-RescuedIRN", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-RescuedTalked", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-Resurrected", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-Tadpoled", [], 0],
    ["ORI_Avatar_Wyll_SUB_Duke-TavernBurnt", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-DragonFound", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-DragonKilled", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-Entered_NoSolution", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-Entered", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-FromBook", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-LeftAct_Wyrmway", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-PuzzlesSolved", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-Reached_Knows", [], 0],
    ["ORI_Avatar_Wyll_SUB_Wyrmway-TalkedStatue", [], 0],
    ["ORI_Avatar_Wyll-BrokenPactRavengardDead", [], 0],
    ["ORI_Avatar_Wyll-BrokenPactRavengardSearch", [], 0],
    ["ORI_Avatar_Wyll-CeremonyResolved", [], 0],
    ["ORI_Avatar_Wyll-EternalPactRavengardHint", [], 0],
    ["ORI_Avatar_Wyll-EternalPactRavengardResurrected", [], 0],
    ["ORI_Avatar_Wyll-FirstContact", [], 0],
    ["ORI_Avatar_Wyll-FlorrickFallbackFightHostile", [], 0],
    ["ORI_Avatar_Wyll-FlorrickFightBookGiven", [], 0],
    ["ORI_Avatar_Wyll-FlorrickFightBookTaken", [], 0],
    ["ORI_Avatar_Wyll-FlorrickFightFallbackBookGiven", [], 0],
    ["ORI_Avatar_Wyll-FlorrickFightHostile", [], 0],
    ["ORI_Avatar_Wyll-KarlachHired", [], 0],
    ["ORI_Avatar_Wyll-KarlachKilled", [], 0],
    ["ORI_Avatar_Wyll-MetMizoraBeforeCeremony", [], 0],
    ["ORI_Avatar_Wyll-MetPaladinsOfTyr", [], 0],
    ["ORI_Avatar_Wyll-MizorasCaptureHappened", [], 0],
    ["ORI_Avatar_Wyll-MizorasCaptureReachedColony", [], 0],
    ["ORI_Avatar_Wyll-MizorasJudgementDevil", [], 0],
    ["ORI_Avatar_Wyll-MizorasJudgementReward", [], 0],
    ["ORI_Avatar_Wyll-MizorasRescueHappened", [], 0],
    ["ORI_Avatar_Wyll-MizorasRescueHappenedPact", [], 0],
    ["ORI_Avatar_Wyll-MizorasRescueReward", [], 0],
    ["ORI_Avatar_Wyll-MizoraWentToCamp", [], 0],
    ["ORI_Avatar_Wyll-RavengardRescuedIRN", [], 0],
    ["ORI_Avatar_Wyll-RavengardWyllAvernus", [], 0],
    ["ORI_Avatar_Wyll-RavengardWyllFrontiers", [], 0],
    ["ORI_Avatar_Wyll-RavengardWyllGrandDuke", [], 0],
    ["ORI_Avatar_Wyll-ReachedAct3", [], 0],
    ["ORI_Avatar_Wyll-ReachedEND", [], 0],
    ["ORI_Avatar_Wyll-RecruitedKarlachNoWyll", [], 0],
    ["ORI_Avatar_Wyll-Tut_Start", [], 0],
    ["ORI_Avatar_Wyll-WyllAvernus", [], 0],
    ["ORI_Avatar_Wyll-WyllFrontiers", [], 0],
    ["ORI_Avatar_Wyll-WyllGrandDuke", [], 0],
    ["ORI_Avatar_Wyll-WyrmwayFromBook", [], 0],
    ["ORI_Avatar_Wyll-WyrmwayFromRavengard", [], 0],
    ["ORI_Avatar_Wyll-WyrmwayReached", [], 0],
    ["ORI_Avatar_Wyll-WyrmwaySolved", [], 0],
    ["ORI_Avatar_Wyll-WyrmwaySolvedRavengard", [], 0],
    ["ORI_Avatar_Wyll-WyrmwaySubStarted", [], 0],
    ["ORI_COM_Astarion-RecruitedAstarion", ["Astarion: Recruited"], 0],
    ["ORI_COM_Gale_Letter-DestroyedPouch", [], 0],
    ["ORI_COM_Gale_Letter-GaleDied", ["Gale: Died"], 0],
    ["ORI_COM_Gale_Letter-GotScroll", ["Gale: Told Mephit his Name"], 0],
    ["ORI_COM_Gale_Letter-LearnedFlute", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-LearnedMephit", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-LearnedPouch", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-OpenedPouch", ["Gale: Opened Pouch"], 0],
    ["ORI_COM_Gale_Letter-PlayedNotes", ["Gale: Played Flute"], 0],
    ["ORI_COM_Gale_Letter-PrematureProjectionEnd", [], 0],
    ["ORI_COM_Gale_Letter-ResurrectedGale", ["Gale: Resurrected"], 0],
    ["ORI_COM_Gale-FoundAmulet", [], 0],
    ["ORI_COM_Gale-FoundBook", [], 0],
    ["ORI_COM_Gale-FoundBoots", [], 0],
    ["ORI_COM_Gale-FoundCowl", [], 0],
    ["ORI_COM_Gale-FoundFlask", [], 0],
    ["ORI_COM_Gale-FoundIdol", [], 0],
    ["ORI_COM_Gale-FoundStaff", [], 0],
    ["ORI_COM_Gale-FoundSword", [], 0],
    ["ORI_COM_Gale-FoundTome", [], 0],
    ["ORI_COM_Gale-GaveOneItem", ["Gale: Fed an Item"], 0],
    ["ORI_COM_Gale-GaveThreeItems", ["Gale: Fed a Second Item"], 0],
    ["ORI_COM_Gale-GaveTwoItems", ["Gale: Fed a Third Item"], 0],
    ["ORI_COM_Gale-LearnedBackstory", ["Gale: Told Backstory"], 0],
    ["ORI_COM_Gale-LearnedGoal", ["Gale: Told about Hunger"], 0],
    ["ORI_COM_Gale-LearnedGoal2", ["Gale: Told about Hunger"], 0],
    ["ORI_COM_Gale-NeedFirstItem", [], 0],
    ["ORI_COM_Gale-NeedSecondItem", [], 0],
    ["ORI_COM_Gale-NeedThirdItem", [], 0],
    ["ORI_COM_Gale-RecruitedGale", ["Gale: Recruited"], 0],
    ["TUT_NautiloidEscape-EscapedHell", ["Tut: Connect the Transponder"], 0],
    ["TUT_NautiloidEscape-LearnedHelm_AltGuide", ["Tut: Learn about the Helm"], 0],
    ["TUT_NautiloidEscape-LearnedHelm_Devourer", ["Tut: Learn about the Helm"], 0],
    ["TUT_NautiloidEscape-LearnedHelm_Laezel", ["Tut: Learn about the Helm"], 0],
    ["TUT_NautiloidEscape-ReachedHelm", ["Tut: Reach the Helm"], 0],
    ["TUT_NautiloidEscape-Start", [], 0],
    ["TUT_ShadowheartEscape-FindCaptive", ["Tut-SH: Find Captive"], 0],
    ["TUT_ShadowheartEscape-FoundRune", ["Tut-SH: Find the Rune"], 0],
    ["TUT_ShadowheartEscape-FreedAndRecruited", ["Tut-SH: Recruit Captive"], 0],
    ["TUT_ShadowheartEscape-FreedDidNotRecruit", [], 0],
    ["TUT_ShadowheartEscape-FreedLeftBehind", [], 0],
    ["TUT_ShadowheartEscape-LeftBehind", [], 0],
    ["TUT_ShadowheartEscape-UsedForce", ["Tut-SH: Find the Rune", "Tut-SH: Open the Pod"], 0],
    ["TUT_ShadowheartEscape-UsedRune", ["Tut-SH: Open the Pod"], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Lockdown", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_LockdownEnd", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Ready", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Started", [], 0],
    ["DEN_Conflict_SUB_AoD-ArrivedAtGrove", [], 0],
    ["DEN_Conflict_SUB_AoD-AskedTorture", [], 0],
    ["DEN_Conflict_SUB_AoD-CelebrationGoblins", [], 0],
    ["DEN_Conflict_SUB_AoD-CelebrationTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-GotBriefed", [], 0],
    ["DEN_Conflict_SUB_AoD-GotGroveLocation", [], 0],
    ["DEN_Conflict_SUB_AoD-King_SentToMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-MintharaDied", [], 0],
    ["DEN_Conflict_SUB_AoD-MintharaDiedLate", [], 0],
    ["DEN_Conflict_SUB_AoD-OrderedKillDruids", [], 0],
    ["DEN_Conflict_SUB_AoD-SazzaToldMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-SidedGoblins", [], 0],
    ["DEN_Conflict_SUB_AoD-SidedTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryAsharak", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryBackup", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryZevlor", [], 0],
    ["DEN_Conflict_SUB_Goblin-DEN_LearntGoblinLeaderCorpses", [], 0],
    ["DEN_Conflict_SUB_Goblin-DEN_LearntGoblinLeaderZevlor", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_ArrivedGoblinCamp", ["Gobs: Arrive at Goblin Camp"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_ArrivedGoblinCampLeaders", ["Gobs: Arrive at Goblin Camp"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntAllNames", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the Drow's Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntNoName", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntThirdName", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the Drow's Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntTwoNames", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledDrow", ["Gobs: Defeat (Knock Out) Minthara"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledKing", ["Gobs: Kill Dror Ragzlin"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledPriest", ["Gobs: Kill Priestess Gut"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledDrow", ["Gobs: Defeat (Knock Out) Minthara"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledKing", ["Gobs: Kill Dror Ragzlin"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledPriest", ["Gobs: Kill Priestess Gut"], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Goblin-LearnedLeaving", [], 0],
    ["DEN_Conflict_SUB_Halsin-Betrayal_DruidDead_Halsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-Celebration_MetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-DruidLeaderDied", [], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_DrowDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_KingDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_AoD", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_KillLeaders", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_LeadershipDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_PriestessDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_AoD", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_KillLeaders", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_LeadershipDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-Halsin_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Halsin-Halsin_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_AoDStarted", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_EndedAoD", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_KilledLeaders", ["Gobs-Halsin: Tell Halsin about Victory"], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinReturned_Known", ["Gobs-Halsin: Tell Halsin about Victory"], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinSentToRath", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinSentToRathAlt", [], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedBear", ["Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedEscaped", [], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedHalsinMissing", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedHalsinPosition", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedLostHalsin", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedPit", [], 0],
    ["DEN_Conflict_SUB_Halsin-LeftSafe_MetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-LeftSafe_NoMetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-RathDied", [], 0],
    ["DEN_Conflict_SUB_Halsin-RathRewarded", ["Gobs-Halsin: Get Reward from Rath"], 0],
    ["DEN_Conflict_SUB_Halsin-RathRewardedAlt", ["Gobs-Halsin: Get Reward from Rath"], 0],
    ["DEN_Conflict_SUB_Halsin-ReportHalsin_AoDStarted", [], 0],
    ["DEN_Conflict_SUB_Halsin-ReportHalsin_LeadersDefeated", ["Gobs-Halsin: Defeated all Goblin Leaders"], 0],
    ["DEN_Conflict_SUB_Murder-KaghaTurnedGood", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_BadKaghaDead", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Murder-Murder_DADruidsDead", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Murder-Murder_DAStarted", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_GobHuntDone", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Murder-SDCombatStarted", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorDied", [], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorRewarded", ["Grove-Kagha: Return to Zevlor"], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorTalkedMurder", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FightBad", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FightEndedBad", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Ritual-FightEndedGood", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Ritual-FightGood", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundLetterAfterNote", ["Grove-Kagha: Find Note in Swamp"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundLetterFirst", ["Grove-Kagha: Find Note in Swamp"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundNote", ["Grove-Kagha: Find Note in Grove"], 0],
    ["DEN_Conflict_SUB_Ritual-ReflectedKagha", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_DAStarted", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_GobHuntDone", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Ritual-RitualStopped", [], 0],
    ["DEN_Conflict-AllowedInUnknown", ["Grove-Kagha: Get past Guards"], 0],
    ["DEN_Conflict-AoD_Started_ParentUpdate", [], 0],
    ["DEN_Conflict-Betrayal", [], 0],
    ["DEN_Conflict-BetrayalAfterVictory", [], 0],
    ["DEN_Conflict-DADruidsDead", [], 0],
    ["DEN_Conflict-DADruidsDead_NoMet", [], 0],
    ["DEN_Conflict-FoundHalsin_ParentUpdate", ["Gobs-Halsin: Found Halsin"], 0],
    ["DEN_Conflict-FoundKaghaDoc_AfterZev", ["Grove-Kagha: Find Note in Grove"], 0],
    ["DEN_Conflict-HalsinGaveQuest", [], 0],
    ["DEN_Conflict-HeardAboutAoD", [], 0],
    ["DEN_Conflict-KaghaDiedEarly", [], 0],
    ["DEN_Conflict-LeftRegion", [], 0],
    ["DEN_Conflict-LeftSafe", ["Gobs-Halsin: Tieflings left for Baldur's Gate"], 0],
    ["DEN_Conflict-Lockdown", [], 0],
    ["DEN_Conflict-MetKagha", ["Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetKagha_FoundNote", ["Grove-Kagha: Find Note in Grove", "Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetKagha_ZevlorDead", ["Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetZevlor", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict-MintharaDiedEarly", [], 0],
    ["DEN_Conflict-NoTieflings", [], 0],
    ["DEN_Conflict-RathGaveQuest_AfterZev", ["Grove-Kagha: Talk to Rath"], 0],
    ["DEN_Conflict-RathGaveQuest_BeforeZev", ["Grove-Kagha: Talk to Rath"], 0],
    ["DEN_Conflict-SidedGoblins_ParentUpdate", [], 0],
    ["DEN_Conflict-SidedTieflings_Celebrate", ["Gobs-Halsin: Celebrate with Tieflings"], 0],
    ["DEN_Conflict-ToldKaghaZevlorDead_After", [], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom"], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate_Asharak", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom"], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate_Cerys", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom"], 0],
    ["DEN_Conflict-ZevGaveQuest", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict-ZevlorDiedEarly", [], 0],
    ["DEN_CapturedGoblin-MetGoblin", ["Grove-Sazza: Keep Sazza Alive"], 0],
    ["DEN_CapturedGoblin-Released", ["Grove-Sazza: Free Sazza"], 0],
    ["DEN_CapturedGoblin-Escaped", ["Grove-Sazza: Escort Sazza out"], 0],
    ["DEN_CapturedGoblin-FoundCheckpoint", [], 0],
    ["DEN_CapturedGoblin-FoundNearDrow", ["Grove-Sazza: Find Sazza at Minthara"], 0],
    ["DEN_CapturedGoblin-Saved", ["Grove-Sazza: Save Sazza Again"], 0],
    ["DEN_CapturedGoblin-SavedFromSpider", ["Grove-Sazza: Save Sazza Again"], 0],
    ["DEN_CapturedGoblin-NotReleased", [], 0],
    ["DEN_CapturedGoblin-DiedEscape", [], 0],
    ["DEN_CapturedGoblin-DiedSpiders", [], 0],
    ["DEN_CapturedGoblin-GoblinDead", [], 0],
    ["DEN_CapturedGoblin-NotFoundCheckpoint", [], 0],
    ["DEN_CapturedGoblin-NotRewarded", [], 0],
    ["DEN_FindingDoni-AoDStarted", [], 0],
    ["DEN_FindingDoni-BetrayedTieflings", [], 0],
    ["DEN_FindingDoni-FoundDoni", [], 0],
    ["DEN_FindingDoni-LeftAct", [], 0],
    ["DEN_FindingDoni-ReturnedRikka", [], 0],
    ["DEN_FindingDoni-RikkaAskedQuest", [], 0],
    ["DEN_FindingDoni-RikkaDied", [], 0],
    ["DEN_VoloAdventure-VoloTaken", ["Gobs-Volo: Watch Volo get Escorted Away"], 0],
    ["DEN_VoloAdventure-VoloTakenAlreadyMet", ["Gobs-Volo: Watch Volo get Escorted Away"], 0],
    ["DEN_VoloAdventure-VoloPrison", ["Gobs-Volo: Find Volo in Cage"], 0],
    ["DEN_VoloAdventure-VoloFree", ["Gobs-Volo: Free Volo"], 0],
    ["DEN_VoloAdventure-VoloEscaped", ["Gobs-Volo: Free Volo"], 0],
    ["DEN_VoloAdventure-VoloCamp", ["Gobs-Volo: Meet Volo in Camp"], 0],
    ["DEN_VoloAdventure-VoloDead", [], 0],
    ["DEN_VoloAdventure-NotSaved", [], 0],
    ["DEN_IdolTheft-AttackFinished", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-AttackTriggered", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-GaveIdol", ["Grove-Idol: Give Idol to Mol"], 0],
    ["DEN_IdolTheft-GroveChanged", [], 0],
    ["DEN_IdolTheft-JoinedRaiders", [], 0],
    ["DEN_IdolTheft-KeptIdol", [], 0],
    ["DEN_IdolTheft-KidsHostile", [], 0],
    ["DEN_IdolTheft-LostAttack", [], 0],
    ["DEN_IdolTheft-NoAttackTheft", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-NoIdolTheft", [], 0],
    ["DEN_IdolTheft-RaidFinished", [], 0],
    ["DEN_IdolTheft-RaidStarted", [], 0],
    ["DEN_IdolTheft-TheftRequest", ["Grove-Idol: Get Asked to Steal the Idol"], 0],
    ["DEN_IdolTheft-TheftRequest_AlreadyHad", ["Grove-Idol: Get Asked to Steal the Idol"], 0],
    ["DEN_IdolTheft-TieflingsLeftBefore", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-DestroyTome", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-DestroyTome_Radiant", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-EvilTome_COMPLETE", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-FindKey", ["Village-Book: Find Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-FindWayToDecypherPage", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-InvestigateMissingKnowledge", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-KeyInCave", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-KeyLost", ["Village-Book: Learn about Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-ReadTome", ["Village-Book: Learn about Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-UnlockTome", ["Village-Book: Learn about Gem", "Village-Book: Find Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-UseTome_Destroyed", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-UseTome_LostTome", [], 0],
    ["FOR_DangerousBook-DestroyedTome", [], 0],
    ["FOR_DangerousBook-FindCellar", ["Village-Book: Learn about Lab"], 0],
    ["FOR_DangerousBook-FindCellarAgain", ["Village-Book: Learn about Lab", "Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-FindLab", ["Village-Book: Learn about Lab"], 0],
    ["FOR_DangerousBook-FindLabAgain", ["Village-Book: Learn about Lab", "Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-FindTome", ["Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-InvestigateTome", ["Village-Book: Find Tome", "Village-Book: Unlock Tome"], 0],
    ["FOR_DangerousBook-LostTome", [], 0],
    ["FOR_DangerousBook-MadnessKnowledge", ["Village-Book: Find Tome", "Village-Book: Unlock Tome"], 0],
    ["FOR_DangerousBook-ReachedLastPage", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook-SearchLabAfterJournal", ["Village-Book: Find Lab"], 0],
    ["FOR_IncompleteMasterwork-FindJournal", ["Village-Forge: Find Journal"], 0],
    ["FOR_IncompleteMasterwork-FindPlansAfterJournal", ["Village-Forge: Find Plans"], 0],
    ["FOR_IncompleteMasterwork-FindPlansBeforeJournal", ["Village-Forge: Find Plans"], 0],
    ["FOR_UnfortunateGnome-Approach", ["Village-Gnome: Find Windmill"], 0],
    ["FOR_UnfortunateGnome-GoblinsAttacked", ["Village-Gnome: Talk to Goblins"], 0],
    ["FOR_UnfortunateGnome-Pacified", ["Village-Gnome: Talk to Goblins", "Village-Gnome: Get Rid of Goblins"], 0],
    ["FOR_UnfortunateGnome-Defeated", ["Village-Gnome: Get Rid of Goblins"], 0],
    ["FOR_UnfortunateGnome-WindmillStopped", ["Village-Gnome: Stop Windmill"], 0],
    ["FOR_UnfortunateGnome-GnomeFreed", ["Village-Gnome: Free Gnome"], 0],
    ["FOR_UnfortunateGnome-GnomeNotToCamp", ["Village-Gnome: Talk to Barcus"], 0],
    ["FOR_UnfortunateGnome-GnomeToCamp", ["Village-Gnome: Talk to Barcus"], 0],
    ["FOR_UnfortunateGnome-GnomeLeft", [], 0],
    ["FOR_UnfortunateGnome-GnomeDied", [], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_MeetArtist", ["Waukeen-Zhent: Meet Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_TwoLoveStory", ["Waukeen-Zhent: Meet Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_AgreedBuy", ["Waukeen-Zhent: Agree to Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_KnowPrice", ["Waukeen-Zhent: Learn Oskar's Price"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LowerPrice", ["Waukeen-Zhent: Learn Oskar's Price"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByBribe", ["Waukeen-Zhent: Agree to Free Oskar", "Waukeen-Zhent: Learn Oskar's Price", "Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByPersuade", ["Waukeen-Zhent: Agree to Free Oskar", "Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByViolence", ["Waukeen-Zhent: Agree to Free Oskar", "Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LeftForBG", ["Waukeen-Zhent: Agree to Free Oskar", "Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LeftLevelOskarFree", ["Waukeen-Zhent: Agree to Free Oskar", "Waukeen-Zhent: Free Oskar"], 0],
    ["PLA_GrandDukeRescue-OrderedBreachInn", ["Waukeen-Fire: Notice Fire"], 0],
    ["PLA_GrandDukeRescue-OrderedBreachInn_Fail", ["Waukeen-Fire: Notice Fire"], 0],
    ["PLA_GrandDukeRescue-EnteredInn", ["Waukeen-Fire: Enter Inn"], 0],
    ["PLA_GrandDukeRescue-FoundStuckHalfElf", ["Waukeen-Fire: Find Benryn"], 0],
    ["PLA_GrandDukeRescue-FoundCounsellor", ["Waukeen-Fire: Find Florrick"], 0],
    ["PLA_GrandDukeRescue-FreedCounsellor", ["Waukeen-Fire: Rescue Florrick"], 0],
    ["PLA_GrandDukeRescue-LearnedDukeMissingCounsellor", ["Waukeen-Fire: Learn about Duke"], 0],
    ["PLA_GrandDukeRescue-LearnedDukeMissingSwD", ["Waukeen-Fire: Learn about Duke"], 0],
    ["PLA_GrandDukeRescue-Counsellor_AcceptedHelp_Moonrise", ["Waukeen-Fire: Accept Mission to Rescue Duke"], 0],
    ["PLA_GrandDukeRescue-Counsellor_AcceptedHelp_NoLocation", ["Waukeen-Fire: Accept Mission to Rescue Duke"], 0],
    ["PLA_GrandDukeRescue-LearnedMoonrise", [], 0],
    ["PLA_GrandDukeRescue-Counsellor_DidntRescue", [], 0],
    ["PLA_GrandDukeRescue-Counsellor_RefusedHelp", [], 0],
    ["PLA_StuckHalfElf-Dead", [], 0],
    ["PLA_StuckHalfElf-Defeated", [], 0],
    ["PLA_StuckHalfElf-Start", ["Waukeen-Fire: Find Benryn"], 0],
    ["PLA_StuckHalfElf-Freed1", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-Freed2", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-Safe", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-LearnedWife", ["Waukeen-Fire: Learn about Benryn's Wife"], 0],
    ["PLA_StuckHalfElf-ReachedWife", ["Waukeen-Fire: Learn about Benryn's Wife"], 0],
    ["PLA_StuckHalfElf-FoundWife", ["Waukeen-Fire: Learn about Benryn's Wife", "Waukeen-Fire: Show Benryn his Wife"], 0],
    ["PLA_StuckHalfElf-KnowDowry", ["Waukeen-Fire: Learn about Dowry"], 0],
    ["PLA_StuckHalfElf-KnowDowry_Benryn", ["Waukeen-Fire: Learn about Dowry"], 0],
    ["PLA_StuckHalfElf-DowryGold", ["Waukeen-Fire: Learn about Dowry", "Waukeen-Fire: Recover Dowry"], 0],
    ["PLA_StuckHalfElf-ReturnedGold", ["Waukeen-Fire: Return Dowry"], 0],
    ["PLA_StuckHalfElf-KeptGold", [], 0],
    ["PLA_StuckHalfElf-ReachedNoReturn", [], 0],
    ["PLA_PaladinsOfTyr-MetAnders_AgreedHelp", ["Karlach-Tyr: Agree to Help Anders"], 0],
    ["PLA_PaladinsOfTyr-MetKarlach", ["Karlach-Tyr: Meet Karlach"], 0],
    ["PLA_PaladinsOfTyr-LearntZarielFollowers", ["Karlach-Tyr: Learn Anders Follows Zariel"], 0],
    ["PLA_PaladinsOfTyr-LearntZarielFollowers_Corpse", ["Karlach-Tyr: Learn Anders Follows Zariel"], 0],
    ["PLA_PaladinsOfTyr-KarlachRecruited", ["Karlach-Tyr: Recruit Karlach"], 0],
    ["PLA_PaladinsOfTyr-KarlachRecruited_AndersNotMet", ["Karlach-Tyr: Recruit Karlach"], 0],
    ["PLA_PaladinsOfTyr-KillThePaladins", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-PaladinsPermadefeated", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-AndersPermadefeated", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-TakeHead", [], 0],
    ["PLA_PaladinsOfTyr-DeliverHead", [], 0],
    ["PLA_PaladinsOfTyr-KarlachBetrayed", [], 0],
    ["PLA_PaladinsOfTyr-KarlachPermaDefeated", [], 0],
    ["PLA_PaladinsOfTyr-KilledKarlach_NoReward", [], 0],
    ["PLA_PaladinsOfTyr-KilledKarlach_Reward", [], 0],
    ["PLA_PaladinsOfTyr-PointOfNoReturn", [], 0],
    ["PLA_PaladinsOfTyr-HeadNotAvailable", [], 0],
    ["PLA_PaladinsOfTyr-KarlachPermanentlyLeaves", [], 0],
    ["PLA_ZhentShipment-FoundOrders", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-SpokeWithDead", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-FoundCaravan", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-AgreedHelp", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-NoticedStruggle_Cave", ["Waukeen-Zhent: Find Caravan", "Waukeen-Zhent: Notice Struggle"], 0],
    ["PLA_ZhentShipment-NoticedStruggle_Hideout", ["Waukeen-Zhent: Find Caravan", "Waukeen-Zhent: Notice Struggle"], 0],
    ["PLA_ZhentShipment-Instigated", [], 0],
    ["PLA_ZhentShipment-GnollGone_HasMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_NotMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_OneDied_NotMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_RuganDied_HasMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-SavedAgents", ["Waukeen-Zhent: Rescue Agents"], 0],
    ["PLA_ZhentShipment-AgentsDied_Cave", [], 0],
    ["PLA_ZhentShipment-AgentsDied_Hideout", [], 0],
    ["PLA_ZhentShipment-AgentsDied_NoSave", [], 0],
    ["PLA_ZhentShipment-SavedOlly_GotCargo_Hideout", [], 0],
    ["PLA_ZhentShipment-SavedAgents_TookCargo", [], 0],
    ["PLA_ZhentShipment-GotCargo_NoPassword", [], 0],
    ["PLA_ZhentShipment-NoSave_GotCargo_Hideout", [], 0],
    ["PLA_ZhentShipment-TalkedToOlly_Cave", [], 0],
    ["PLA_ZhentShipment-TalkedToOlly_Hideout", [], 0],
    ["PLA_ZhentShipment-GotPassword", ["Waukeen-Zhent: Learn Password"], 0],
    ["PLA_ZhentShipment-GotPasswordDead", ["Waukeen-Zhent: Learn Password"], 0],
    ["PLA_ZhentShipment-GotDirectionsDead", [], 0],
    ["PLA_ZhentShipment-EnteredHideout", ["Waukeen-Zhent: Enter Zhentarim Hideout"], 0],
    ["PLA_ZhentShipment-Rewarded_ZhentReturned", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Rewarded_OnlyCargo", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Rewarded_SentToBG", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Attacked", [], 0],
    ["PLA_ZhentShipment-ChestOpened", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_Attacked", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_ChestLost", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_HadChest", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_NotAllowed", [], 0],
    ["PLA_ZhentShipment-LeftAct", [], 0],
    ["PLA_ZhentShipment-LeftAct_notDecided", [], 0],
    ["PLA_ZhentShipment-Rewarded_NoCargo", [], 0],
    ["PLA_ZhentShipment-RuganForced", [], 0],
    ["SHA_Nightsong-LearnedBryanMap", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-LearnedLocation", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-ReadAgedJournal", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-SawBook", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestArtefactAtCamp", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestReceivedArtefact", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestRecruitedShadowheart", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestSawShadowHeartAndBoxAtCamp", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-GoblinCampGoblinKing", ["Plot-Art: Hear Ragzlin talk about Artefact"], 0],
    ["GLO_ArtefactDiscovery-GoblinCampMinthara", ["Plot-Art: Hear Minthara talk about Artefact"], 0],
    ["GLO_Tadpole_SUB_Druid-Betrayal_DruidDead_Halsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-DruidLeaderDied_NoResearch", [], 0],
    ["GLO_Tadpole_SUB_Druid-DruidLeaderDied_Research", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_DrowDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_KingDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_AoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_KillLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_LeadershipDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_PriestessDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_AoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_KillLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_LeadershipDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-Halsin_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_AoDStarted", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_EndedAoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_KilledLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_KilledLeaders_SkipGrove", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_NoHelp_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_NoHelp_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinReturned_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinReturned_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Return", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HeardHalsinSwD", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedBear", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedEscaped", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedExpeditionGoal", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedHalsinDiary", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedHalsinPosition", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedKilledOrCaptured", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedLostHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedLostHalsin_Update", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedPit", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedResearchHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedResearchHalsin_Update", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReadHalsinDiary", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReportHalsin_AoDStarted", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReportHalsin_LeadersDefeated", [], 0],
    ["GLO_Tadpole_SUB_Druid-StillNeedToSpeakToHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-TalkedLeader_Celebrate", [], 0],
    ["GLO_Tadpole_SUB_Priestess-GotBranded", [], 0],
    ["GLO_Tadpole_SUB_Priestess-LearnPriestess", [], 0],
    ["GLO_Tadpole_SUB_Priestess-Priestess_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessDied", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessImprisoned", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessTurnedHostile", [], 0],
    ["GLO_Tadpole_SUB_Priestess-ReachedQuarters", ["Gobs: Follow Gut to her Quarters"], 0],
    ["GLO_Tadpole_SUB_Priestess-RefusedHelpGut", [], 0],
    ["GLO_Tadpole-ApprenticeDiedEarly", [], 0],
    ["GLO_Tadpole-LaezelJoined", ["Tadpole: Talk to Lae'zel"], 0],
    ["GLO_Tadpole-LaezelPermaDefeatedEarly", [], 0],
    ["GLO_Tadpole-LearnedApprentice", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole-LearnedApprentice_Scouts", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole-LearnedGroveSituation", [], 0],
    ["GLO_Tadpole-LearnedHalsin", ["Tadpole: Learn about Halsin"], 0],
    ["GLO_Tadpole-LearnedPriestess", ["Tadpole: Learn about Priestess Gut"], 0],
    ["GLO_Tadpole-PoisonedByApprentice_ParentCompletion", [], 0],
    ["GLO_Tadpole-PoisonedByApprenticeSuccess_ParentCompletion", [], 0],
    ["GLO_Tadpole-PriestessDiedEarly", [], 0],
    ["GLO_Tadpole-PriestessImprisoned_ParentCompletion", [], 0],
    ["GLO_Tadpole-SawTrueSoulMeldOrTadpole", ["Tadpole: See True Soul Meld/Tadpole"], 0],
    ["GLO_Tadpole-WokeAtCrash", ["Tadpole: Wake on Beach"], 0],
    ["GLO_UnleashPowers-DaisyAskedConsume", ["Tadpole: Guardian Suggests Consuming Tadpole"], 0],
    ["GLO_UnleashPowers-FindMoreTadpoles", ["Tadpole: Found a Tadpole"], 0],
    ["GLO_UnleashPowers-FindTadpole", ["Tadpole: Told by Guardian to find Tadpoles"], 0],
    ["GLO_UnleashPowers-FoundTadpole", ["Tadpole: Found a Tadpole"], 0],
    ["GLO_UnleashPowers-UsedIllithidPersuasion", ["Tadpole: Used Illithid Persuasion"], 0],
    ["ORI_COM_Astarion-CompanionHostile", [], 0],
    ["ORI_COM_Astarion-CompanionLowRelation", [], 0],
    ["ORI_COM_Astarion-CompanionMurdered", [], 0],
    ["ORI_COM_Astarion-LearnedAstarionSlave", ["Astarion: Learned Backstory"], 0],
    ["ORI_COM_Astarion-LearnedAstarionTadpole", ["Astarion: Chat about Tadpole"], 0],
    ["ORI_COM_Astarion-LearnedVampire_Attacked", ["Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-LearnedVampire_GaveBlood", ["Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-LearnedVampire_NoBlood", ["Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-MetGur_AstarionCapture", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_AstarionDisappear", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_AstarionKilledGur", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_Combat", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_DidNotToldCampLocation", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_LearnedEmployer", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-MetGur_LearnedVampire", ["Astarion: Met Gandrel", "Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-MetGur_LearnedVampire_AlreadyKnew", ["Astarion: Met Gandrel", "Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-MetGur_ToldCampLocation", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Astarion-ToldAstarionFeed_Animals", ["Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-ToldAstarionFeed_Enemies", ["Astarion: Learned Vampire"], 0],
    ["ORI_COM_Astarion-ToldGur_CazadorSuspect", ["Astarion: Met Gandrel"], 0],
    ["ORI_COM_Karlach-Recruited_PaladinsDefeated", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach-Recruited_PaladinsNotDefeated", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach-ExploreSwordCoast", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-RecruitedKarlach_KnowsCanBeUpgraded", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-KnowsDammon", ["Karlach-Heart: Introduce Karlach to Dammon"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_FirstUpgrade", ["Karlach-Heart: Find Infernal Metal"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-GetFirstUpgrade", ["Karlach-Heart: Get First Heart Upgrade"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_DoesNotKnowDammon", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_DoesNotKnowDammon_BeforePaladins", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_KnowsDammon", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_KnowsDammon_BeforePaladins", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Laezel-RecruitedLaezel_Beach", [], 0],
    ["ORI_COM_Laezel-RecruitedLaezel_Cage", [], 0],
    ["ORI_COM_Laezel-FoundOutAboutZorru", ["Lae'zel: Find out about Zorru"], 0],
    ["ORI_COM_Laezel-AskedZevlorAboutZorru", [], 0],
    ["ORI_COM_Laezel-FoundZorruLZAbsent", [], 0],
    ["ORI_COM_Laezel-GotNoInfoFromZorru", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-GotNoInfoFromZorruWithoutKnowingHim", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-ZorruDied", [], 0],
    ["ORI_COM_Laezel-ZorruMarkedMap", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-ZorruMarkedMapWithoutKnowingAboutHim", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-TalkedToDeadTiefling", [], 0],
    ["ORI_COM_Laezel-SawDragonRider", ["Lae'zel: See Dragon Rider"], 0],
    ["ORI_COM_Laezel-SawDragonRider_KnowsAboutGithyankiPatrol", ["Lae'zel: See Dragon Rider"], 0],
    ["ORI_COM_Laezel-LaezelRanToKnight", [], 0],
    ["ORI_COM_Laezel-ChokepointCombatStarted", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ChokepointDefeated", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ResolvedPeaceCreche", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ResolvedPeaceNoCreche", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ReadCrecheMap", ["Lae'zel: Learn Creche Location"], 0],
    ["ORI_COM_Laezel-LaezelDied_FoundShadowcursedInSCL", [], 0],
    ["ORI_COM_Laezel-LaezelDied_Generic", [], 0],
    ["ORI_COM_Laezel-LaezelDied_GoBackToMountainpass", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledAtCampNight", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledByShadowheart", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledByVossInPlains", [], 0],
    ["ORI_COM_Laezel-LaezelDied_MissingAtMountainpass", [], 0],
    ["ORI_COM_Laezel-LaezelTurnedHostile_Generic", [], 0],
    ["ORI_COM_Laezel-TurnedHostileAtChokepoint", [], 0],
    ["ORI_COM_ShadowHeart-CampFight_LaezelDied", [], 0],
    ["ORI_COM_ShadowHeart-CampFight_Peace", ["Shart: Resolve Camp Fight (both live)"], 0],
    ["ORI_COM_ShadowHeart-CampFight_ShadowheartDied", [], 0],
    ["ORI_COM_ShadowHeart-CompanionHostile", [], 0],
    ["ORI_COM_ShadowHeart-CompanionLowRelation", [], 0],
    ["ORI_COM_ShadowHeart-CompanionMurdered", [], 0],
    ["ORI_COM_ShadowHeart-Recruited_Beach", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Box", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Camp", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Den", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Githyanki", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Laezel", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Reanimated", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-SawBox", [], 0],
    ["ORI_COM_ShadowHeart-SawIncurableWound", ["Shart: See Wound"], 0],
    ["ORI_COM_Wyll-RecruitedWyll", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorDead", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorDeadKnown", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorRefused", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorTalked", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorTalkedKnowsMT", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-InnReached", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-Kidnapped", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-LearntMT", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-TavernBurnt", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-RavengardFather", ["Wyll: Learn Wyll's Father"], 0],
    ["ORI_COM_Wyll-CompanionHostile", [], 0],
    ["ORI_COM_Wyll-CompanionLowRelation", [], 0],
    ["ORI_COM_Wyll-CompanionMurdered", [], 0],
    ["ORI_COM_Wyll-KarlachHired", ["Wyll: Resolved Conflict with Karlach"], 0],
    ["ORI_COM_Wyll-KarlachKilled", [], 0],
    ["ORI_COM_Wyll-MetPaladinsOfTyr", [], 0],
    ["ORI_COM_Wyll-PostKarlachDead", [], 0],
    ["ORI_COM_Wyll-PostKarlachSpared", ["Wyll: Resolved Conflict with Karlach"], 0],
    ["ORI_COM_Wyll-RecrtuitedMetKarlach", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedAmbush", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedAmbushKarlachKilled", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedKarlachNoWyll", [], 0],
    ["ORI_COM_Wyll-MizorasJudgementDevil", ["Wyll: Meet Mizora"], 0],
    ["ORI_COM_Wyll-MizorasJudgementReward", ["Wyll: Meet Mizora"], 0],

    ["GLO_Tadpole_SUB_Apprentice-SavedHalsin_BeforeTadpoled", ["Victory_Halsin"], 0],
    ["GLO_Tadpole_SUB_Creche_SpeakToDoctor_BetrayedByVlaakith", ["Victory_Wwargaz"], 1],
]
