
BG3_LOCATION_LIST = [
    ["TUT_NautiloidEscape-Start",[],0],
    ["TUT_NautiloidEscape-LearnedHelm_Laezel",["Tut: Learn about the Helm"],0],
    ["TUT_NautiloidEscape-LearnedHelm_AltGuide",["Tut: Learn about the Helm"],0],
    ["TUT_NautiloidEscape-LearnedHelm_Devourer",["Tut: Learn about the Helm"],0],
    ["TUT_NautiloidEscape-ReachedHelm",["Tut: Reach the Helm"],0],
    ["TUT_NautiloidEscape-EscapedHell",["Tut: Connect the Transponder"],0],
    ["TUT_ShadowheartEscape-FindCaptive",["Tut-SH: Find Captive"],0],
    ["TUT_ShadowheartEscape-UsedRune",["Tut-SH: Open the Pod"],0],
    ["TUT_ShadowheartEscape-UsedForce",["Tut-SH: Find the Rune","Tut-SH: Open the Pod"],0],
    ["TUT_ShadowheartEscape-FreedAndRecruited",["Tut-SH: Recruit Captive"],0],
    ["TUT_ShadowheartEscape-FreedDidNotRecruit",[],0],
    ["TUT_ShadowheartEscape-FreedLeftBehind",[],0],
    ["TUT_ShadowheartEscape-LeftBehind",[],0],
    ["TUT_ShadowheartEscape-FoundRune",["Tut-SH: Find the Rune"],0],
    ["CHA_Chapel-ShadowheartMention", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-ReadDruidBook", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-BanditTalking", ["Crypt: Learn about Crypt"], 0],
    ["CHA_Chapel-AccessedTemple", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-WeirdDoor", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-WeirdDoorEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-BeachEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-HatchEntrance", ["Crypt: Learn about Crypt", "Crypt: Enter Crypt"], 0],
    ["CHA_Chapel-FoundSarcophagus_Sealed", ["Crypt: Find Sarcophagus"], 0],
    ["CHA_Chapel-ReadSarcophagusPlaque", ["Crypt: Read Plaque"], 0],
    ["CHA_Chapel-OpenedSarcophagus", ["Crypt: Open Sarcophagus"], 0],
    ["CHA_Chapel-Exit", [], 0],
    ["CHA_Chapel-ConfrontJergal", ["Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-JergalAtCamp", ["Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-ConnectedSarcophagusJergal", ["Crypt: Open Sarcophagus", "Crypt: Read Plaque", "Crypt: Talk to Withers at Camp"], 0],
    ["CHA_Chapel-LeftRegion", [], 0],
    ["CHA_Chapel-FoundSarcophagus_Opened", ["Crypt: Find Sarcophagus", "Crypt: Open Sarcophagus"], 0],
    ["CHA_LaezelRecruit-AgreedToHelp", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-Attacked", [], 0],
    ["CHA_LaezelRecruit-AttackedAlt", [], 0],
    ["CHA_LaezelRecruit-DidntAgreeHelp", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-FailedIntimidation", [], 0],
    ["CHA_LaezelRecruit-FailedIntimidationAlt", [], 0],
    ["CHA_LaezelRecruit-FailedPersuasion", [], 0],
    ["CHA_LaezelRecruit-FailedPersuasionAlt", [], 0],
    ["CHA_LaezelRecruit-Freed", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-IntimidatedLeave", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-IntimidatedLeaveAlt", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-InvitedCamp", ["Beach-LZ: Get the Tieflings Away", "Beach-LZ: Recruit Lae'zel"], 0],
    ["CHA_LaezelRecruit-KilledLaezel", [], 0],
    ["CHA_LaezelRecruit-LaezelPermaDefeatead", [], 0],
    ["CHA_LaezelRecruit-LearnedCure", ["Beach-LZ: Talk to Lae'zel"], 0],
    ["CHA_LaezelRecruit-LeftArea", [], 0],
    ["CHA_LaezelRecruit-LeftAreaAfterRecruitment", [], 0],
    ["CHA_LaezelRecruit-Mindmelted", ["Beach-LZ: Talk to Lae'zel"], 0],
    ["CHA_LaezelRecruit-PersuadedKill", [], 0],
    ["CHA_LaezelRecruit-PersuadedKillAlt", [], 0],
    ["CHA_LaezelRecruit-PersuadedLeave", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-PersuadedLeaveAlt", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["CHA_LaezelRecruit-Recruited", ["Beach-LZ: Get the Tieflings Away", "Beach-LZ: Recruit Lae'zel"], 0],
    ["CHA_LaezelRecruit-RefusedInvolvement", [], 0],
    ["CHA_LaezelRecruit-RefusedRecruit", [], 0],
    ["CHA_LaezelRecruit-ReleasedEarly", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-ReleasedEarlyAlt", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedLaezel", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedLaezelAlt", ["Beach-LZ: Free Lae'zel"], 0],
    ["CHA_LaezelRecruit-SidedTieflings", [], 0],
    ["CHA_LaezelRecruit-Started", ["Beach-LZ: Find Lae'zel"], 0],
    ["CHA_LaezelRecruit-StartedAlt", ["Beach-LZ: Find Lae'zel"], 0],
    ["CHA_LaezelRecruit-TieflingsDefeated", ["Beach-LZ: Get the Tieflings Away"], 0],
    ["DEN_Thieflings-DiscoveredRobbed", ["Grove-Thief: Discover Pickpocketing"], 0],
    ["DEN_Thieflings-ToldRobbed", ["Grove-Thief: Discover Pickpocketing"], 0],
    ["DEN_Thieflings-ToldHideout", ["Grove-Thief: Learn About Hideout"], 0],
    ["DEN_Thieflings-EnteredHideout", ["Grove-Thief: Learn About Hideout", "Grove-Thief: Enter Hideout"], 0],
    ["DEN_Thieflings-KnowsMolLeader", [], 0],
    ["DEN_Thieflings-KnowsMolAndHideout", [], 0],
    ["DEN_Thieflings-AlreadyKnowsMol", [], 0],
    ["DEN_Thieflings-DoneTookGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-BefriendedTieflings", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-DoneOutsmartedKids", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-GivenSomeGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-GivenGoods", ["Grove-Thief: Get Your Stuff Back"], 0],
    ["DEN_Thieflings-TriedSmallEntrance", [], 0],
    ["DEN_Thieflings-DoneAngeredThieflings", [], 0],
    ["DEN_Thieflings-DoneLeftAct", [], 0],
    ["DEN_Thieflings-GroveChanged", [], 0],
    ["DEN_Thieflings-RefusedPayGoods", [], 0],
    ["ORI_COM_Astarion-RecruitedAstarion", ["Astarion: Recruited"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedAboutNettie", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedNettieNearby", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedNettieNearby_NoName", ["Tadpole: Learn about Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-ToldAboutTadpole", ["Tadpole-Nettie: Talk to Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-PoisonedByApprentice", ["Tadpole-Nettie: Be Poisoned by Nettie"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedCureSwD", ["Tadpole-Nettie: Learn about Antidote"], 0],
    ["GLO_Tadpole_SUB_Apprentice-LearnedCureDaleland", ["Tadpole-Nettie: Learn about Antidote"], 0],
    ["GLO_Tadpole_SUB_Apprentice-CuredApprenticePoison", ["Tadpole-Nettie: Cure the Poison"], 0],
    ["GLO_Tadpole_SUB_Apprentice-Apprentice_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticeDied_BeforeTadpoled", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticeDied_Tadpoled", [], 0],
    ["GLO_Tadpole_SUB_Apprentice-ApprenticePersuaded", ["Tadpole-Nettie: Be Poisoned by Nettie", "Tadpole-Nettie: Learn about Antidote", "Tadpole-Nettie: Cure the Poison"], 0],
    ["DEN_HarpyMeal-HeardBeachSong", ["Grove-Harpy: Hear Harpy Song"], 0],
    ["DEN_HarpyMeal-FoundKid", ["Grove-Harpy: Find Child"], 0],
    ["DEN_HarpyMeal-DefeatedHarpies", ["Grove-Harpy: Defeat Harpies"], 0],
    ["DEN_HarpyMeal-FoughtHarpies", ["Grove-Harpy: Defeat Harpies"], 0],
    ["DEN_HarpyMeal-ToldDragonLair", ["Grove-Harpy: Discover Hideout Password"], 0],
    ["DEN_HarpyMeal-DoniShownWay", ["Grove-Harpy: Tell password to Doni"], 0],
    ["DEN_HarpyMeal-MetMol", ["Grove-Harpy: Meet Mol"], 0],
    ["DEN_HarpyMeal-ToldDragonLair_MetMol", ["Grove-Harpy: Tell password to Doni", "Grove-Harpy: Meet Mol"], 0],
    ["DEN_HarpyMeal-DoneKidDied", [], 0],
    ["DEN_HarpyMeal-DoneKidFled_NoThank", [], 0],
    ["DEN_HarpyMeal-DoneLeftKid", [], 0],
    ["DEN_HarpyMeal-DoneNoInvestigation", [], 0],
    ["DEN_HarpyMeal-DoneStateChanged", [], 0],
    ["DEN_HarpyMeal-DoniFled", [], 0],
    ["DEN_HarpyMeal-DoniGone", [], 0],
    ["DEN_HarpyMeal-GroveChanged", [], 0],
    ["DEN_HarpyMeal-InvestigateFoundDeadKid", [], 0],
    ["DEN_HarpyMeal-MolGone", [], 0],
    ["DEN_RobbedAdventurer-AdventurerDead", [], 0],
    ["DEN_RobbedAdventurer-FindLocket_KnockOut", [], 0],
    ["DEN_RobbedAdventurer-FindLocket_NoKnockOut", [], 0],
    ["DEN_RobbedAdventurer-FoundLocket_NoAccuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-FoundLocketChest_Accuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-FoundLocketKid_Accuse", ["Grove-Locket: Recover Locket"], 0],
    ["DEN_RobbedAdventurer-GroveChanged", [], 0],
    ["DEN_RobbedAdventurer-NoConflictResolve", [], 0],
    ["DEN_RobbedAdventurer-NoLocketReturn", [], 0],
    ["DEN_RobbedAdventurer-ReturnedLocketFree", ["Grove-Locket: Return Locket"], 0],
    ["DEN_RobbedAdventurer-ReturnedLocketReward", ["Grove-Locket: Return Locket"], 0],
    ["DEN_SnakeCourt-MetParent", ["Grove-Snake: Learn about Arabella"], 0],
    ["DEN_SnakeCourt-EnteredLair", ["Grove-Snake: Learn about Arabella", "Grove-Snake: Find Arabella", "Grove-Kagha: Get past Guards"], 0],
    ["DEN_SnakeCourt-KidFreed", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-KidFreedFirst", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-LeftRegion", [], 0],
    ["DEN_SnakeCourt-ParentAutoReunited", [], 0],
    ["DEN_SnakeCourt-ParentDevastated", ["Grove-Snake: Talk to Arabella's Parents"], 0],
    ["DEN_SnakeCourt-ParentGone", [], 0],
    ["DEN_SnakeCourt-ParentLied", [], 0],
    ["DEN_SnakeCourt-ParentMovedOn", [], 0],
    ["DEN_SnakeCourt-ParentThankful", ["Grove-Snake: Talk to Arabella's Parents"], 0],
    ["DEN_SnakeCourt-SkippedHelp", [], 0],
    ["DEN_SnakeCourt-GroveChanged", [], 0],
    ["DEN_SnakeCourt-KidDied", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["DEN_SnakeCourt-KidDiedFirst", ["Grove-Snake: Resolve Arabella's Situation"], 0],
    ["ORI_COM_Gale_Letter-DestroyedPouch", [], 0],
    ["ORI_COM_Gale_Letter-GaleDied", ["Gale: Died"], 0],
    ["ORI_COM_Gale_Letter-LearnedFlute", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-LearnedMephit", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-LearnedPouch", ["Gale: Listened to Projection"], 0],
    ["ORI_COM_Gale_Letter-OpenedPouch", ["Gale: Opened Pouch"], 0],
    ["ORI_COM_Gale_Letter-PlayedNotes", ["Gale: Played Flute"], 0],
    ["ORI_COM_Gale_Letter-PrematureProjectionEnd", [], 0],
    ["ORI_COM_Gale_Letter-GotScroll", ["Gale: Told Mephit his Name"], 0],
    ["ORI_COM_Gale_Letter-ResurrectedGale", ["Gale: Resurrected"], 0],
    ["ORI_COM_Gale-FoundAmulet", [], 0],
    ["ORI_COM_Gale-FoundBook", [], 0],
    ["ORI_COM_Gale-FoundBoots", [], 0],
    ["ORI_COM_Gale-FoundCowl", [], 0],
    ["ORI_COM_Gale-FoundFlask", [], 0],
    ["ORI_COM_Gale-FoundIdol", [], 0],
    ["ORI_COM_Gale-FoundStaff", [], 0],
    ["ORI_COM_Gale-FoundSword", [], 0],
    ["ORI_COM_Gale-FoundTome", [], 0],
    ["ORI_COM_Gale-GaveOneItem", ["Gale: Fed an Item"], 0],
    ["ORI_COM_Gale-GaveThreeItems", ["Gale: Fed a Second Item"], 0],
    ["ORI_COM_Gale-GaveTwoItems", ["Gale: Fed a Third Item"], 0],
    ["ORI_COM_Gale-LearnedBackstory", ["Gale: Told Backstory"], 0],
    ["ORI_COM_Gale-LearnedGoal", ["Gale: Told about Hunger"], 0],
    ["ORI_COM_Gale-LearnedGoal2", ["Gale: Told about Hunger"], 0],
    ["ORI_COM_Gale-NeedFirstItem", [], 0],
    ["ORI_COM_Gale-NeedSecondItem", [], 0],
    ["ORI_COM_Gale-NeedThirdItem", [], 0],
    ["ORI_COM_Gale-RecruitedGale", ["Gale: Recruited"], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Lockdown", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_LockdownEnd", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Ready", [], 0],
    ["DEN_Conflict_SUB_AoD-AoD_Started", [], 0],
    ["DEN_Conflict_SUB_AoD-ArrivedAtGrove", [], 0],
    ["DEN_Conflict_SUB_AoD-AskedTorture", [], 0],
    ["DEN_Conflict_SUB_AoD-CelebrationGoblins", [], 0],
    ["DEN_Conflict_SUB_AoD-CelebrationTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-GotBriefed", [], 0],
    ["DEN_Conflict_SUB_AoD-GotGroveLocation", [], 0],
    ["DEN_Conflict_SUB_AoD-King_SentToMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-MintharaDied", [], 0],
    ["DEN_Conflict_SUB_AoD-MintharaDiedLate", [], 0],
    ["DEN_Conflict_SUB_AoD-OrderedKillDruids", [], 0],
    ["DEN_Conflict_SUB_AoD-SazzaToldMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-SidedGoblins", [], 0],
    ["DEN_Conflict_SUB_AoD-SidedTieflings", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryAsharak", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryBackup", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryMinthara", [], 0],
    ["DEN_Conflict_SUB_AoD-VictoryZevlor", [], 0],
    ["DEN_Conflict_SUB_Goblin-DEN_LearntGoblinLeaderCorpses", [], 0],
    ["DEN_Conflict_SUB_Goblin-DEN_LearntGoblinLeaderZevlor", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_ArrivedGoblinCamp", ["Gobs: Arrive at Goblin Camp"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_ArrivedGoblinCampLeaders", ["Gobs: Arrive at Goblin Camp"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledDrow_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledKing_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest_Asharak", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Last_KilledPriest_Cerys", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntAllNames", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the Drow's Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntNoName", [], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntThirdName", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the Drow's Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_LearntTwoNames", ["Gobs: Learn the Priestess' Name", "Gobs: Learn the King's Name"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledDrow", ["Gobs: Defeat (Knock Out) Minthara"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledKing", ["Gobs: Kill Dror Ragzlin"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Solo_KilledPriest", ["Gobs: Kill Priestess Gut"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledDrow", ["Gobs: Defeat (Knock Out) Minthara"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledKing", ["Gobs: Kill Dror Ragzlin"], 0],
    ["DEN_Conflict_SUB_Goblin-GOB_Trio_KilledPriest", ["Gobs: Kill Priestess Gut"], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_Goblin-Goblin_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Goblin-LearnedLeaving", [], 0],
    ["DEN_Conflict_SUB_Halsin-Betrayal_DruidDead_Halsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-Celebration_MetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-DruidLeaderDied", [], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_DrowDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_KingDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_AoD", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_KillLeaders", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Known_LeadershipDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_PriestessDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_AoD", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_KillLeaders", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-FoundHalsin_Unknown_LeadershipDead", ["Gobs-Halsin: Learn Halsin is Missing", "Gobs-Halsin: Found Halsin", "Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-Halsin_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Halsin-Halsin_NoTieflings", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_AoDStarted", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_EndedAoD", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinLeft_KilledLeaders", ["Gobs-Halsin: Tell Halsin about Victory", "Victory_Halsin"], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinReturned_Known", ["Gobs-Halsin: Tell Halsin about Victory", "Victory_Halsin"], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinSentToRath", [], 0],
    ["DEN_Conflict_SUB_Halsin-HalsinSentToRathAlt", [], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedBear", ["Gobs-Halsin: Learn Halsin is a Bear"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedEscaped", [], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedHalsinMissing", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedHalsinPosition", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedLostHalsin", ["Gobs-Halsin: Learn Halsin is Missing"], 0],
    ["DEN_Conflict_SUB_Halsin-LearnedPit", [], 0],
    ["DEN_Conflict_SUB_Halsin-LeftSafe_MetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-LeftSafe_NoMetHalsin", [], 0],
    ["DEN_Conflict_SUB_Halsin-RathDied", [], 0],
    ["DEN_Conflict_SUB_Halsin-RathRewarded", ["Gobs-Halsin: Get Reward from Rath"], 0],
    ["DEN_Conflict_SUB_Halsin-RathRewardedAlt", ["Gobs-Halsin: Get Reward from Rath"], 0],
    ["DEN_Conflict_SUB_Halsin-ReportHalsin_AoDStarted", [], 0],
    ["DEN_Conflict_SUB_Halsin-ReportHalsin_LeadersDefeated", ["Gobs-Halsin: Defeated all Goblin Leaders"], 0],
    ["DEN_Conflict_SUB_Murder-KaghaTurnedGood", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_BadKaghaDead", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Murder-Murder_DADruidsDead", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Murder-Murder_DAStarted", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_GobHuntDone", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Murder-Murder_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Murder-SDCombatStarted", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorDied", [], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorRewarded", ["Grove-Kagha: Return to Zevlor"], 0],
    ["DEN_Conflict_SUB_Murder-ZevlorTalkedMurder", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FightBad", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FightEndedBad", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Ritual-FightEndedGood", ["Grove-Kagha: Kill the Shadow Druids"], 0],
    ["DEN_Conflict_SUB_Ritual-FightGood", ["Grove-Kagha: Confront Kagha"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundLetterAfterNote", ["Grove-Kagha: Find Note in Swamp"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundLetterFirst", ["Grove-Kagha: Find Note in Swamp"], 0],
    ["DEN_Conflict_SUB_Ritual-FoundNote", ["Grove-Kagha: Find Note in Grove"], 0],
    ["DEN_Conflict_SUB_Ritual-ReflectedKagha", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_DAStarted", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_GobHuntDone", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_Lockdown", [], 0],
    ["DEN_Conflict_SUB_Ritual-Ritual_StartedAoD", [], 0],
    ["DEN_Conflict_SUB_Ritual-RitualStopped", [], 0],
    ["DEN_Conflict-AllowedInUnknown", ["Grove-Kagha: Get past Guards"], 0],
    ["DEN_Conflict-AoD_Started_ParentUpdate", [], 0],
    ["DEN_Conflict-Betrayal", [], 0],
    ["DEN_Conflict-BetrayalAfterVictory", [], 0],
    ["DEN_Conflict-DADruidsDead", [], 0],
    ["DEN_Conflict-DADruidsDead_NoMet", [], 0],
    ["DEN_Conflict-FoundHalsin_ParentUpdate", ["Gobs-Halsin: Found Halsin"], 0],
    ["DEN_Conflict-FoundKaghaDoc_AfterZev", ["Grove-Kagha: Find Note in Grove"], 0],
    ["DEN_Conflict-HalsinGaveQuest", [], 0],
    ["DEN_Conflict-HeardAboutAoD", [], 0],
    ["DEN_Conflict-KaghaDiedEarly", [], 0],
    ["DEN_Conflict-LeftRegion", [], 0],
    ["DEN_Conflict-LeftSafe", ["Gobs-Halsin: Tieflings left for Baldur's Gate", "Victory_Halsin"], 0],
    ["DEN_Conflict-Lockdown", [], 0],
    ["DEN_Conflict-MetKagha", ["Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetKagha_FoundNote", ["Grove-Kagha: Find Note in Grove", "Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetKagha_ZevlorDead", ["Grove-Kagha: Meet Kagha"], 0],
    ["DEN_Conflict-MetZevlor", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict-MintharaDiedEarly", [], 0],
    ["DEN_Conflict-NoTieflings", [], 0],
    ["DEN_Conflict-RathGaveQuest_AfterZev", ["Grove-Kagha: Talk to Rath"], 0],
    ["DEN_Conflict-RathGaveQuest_BeforeZev", ["Grove-Kagha: Talk to Rath"], 0],
    ["DEN_Conflict-SidedGoblins_ParentUpdate", [], 0],
    ["DEN_Conflict-SidedTieflings_Celebrate", ["Gobs-Halsin: Celebrate with Tieflings", "Victory_Halsin"], 0],
    ["DEN_Conflict-ToldKaghaZevlorDead_After", [], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom", "Victory_Halsin"], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate_Asharak", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom", "Victory_Halsin"], 0],
    ["DEN_Conflict-VictoryGrove_ParentUpdate_Cerys", ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom", "Victory_Halsin"], 0],
    ["DEN_Conflict-ZevGaveQuest", ["Grove-Kagha: Talk to Zevlor about Kagha"], 0],
    ["DEN_Conflict-ZevlorDiedEarly", [], 0],
    ["DEN_CapturedGoblin-MetGoblin", ["Grove-Sazza: Keep Sazza Alive"], 0],
    ["DEN_CapturedGoblin-Released", ["Grove-Sazza: Free Sazza"], 0],
    ["DEN_CapturedGoblin-Escaped", ["Grove-Sazza: Escort Sazza out"], 0],
    ["DEN_CapturedGoblin-FoundCheckpoint", [], 0],
    ["DEN_CapturedGoblin-FoundNearDrow", ["Grove-Sazza: Find Sazza at Minthara"], 0],
    ["DEN_CapturedGoblin-Saved", ["Grove-Sazza: Save Sazza Again"], 0],
    ["DEN_CapturedGoblin-SavedFromSpider", ["Grove-Sazza: Save Sazza Again"], 0],
    ["DEN_CapturedGoblin-NotReleased", [], 0],
    ["DEN_CapturedGoblin-DiedEscape", [], 0],
    ["DEN_CapturedGoblin-DiedSpiders", [], 0],
    ["DEN_CapturedGoblin-GoblinDead", [], 0],
    ["DEN_CapturedGoblin-NotFoundCheckpoint", [], 0],
    ["DEN_CapturedGoblin-NotRewarded", [], 0],
    ["DEN_FindingDoni-AoDStarted", [], 0],
    ["DEN_FindingDoni-BetrayedTieflings", [], 0],
    ["DEN_FindingDoni-FoundDoni", [], 0],
    ["DEN_FindingDoni-LeftAct", [], 0],
    ["DEN_FindingDoni-ReturnedRikka", [], 0],
    ["DEN_FindingDoni-RikkaAskedQuest", [], 0],
    ["DEN_FindingDoni-RikkaDied", [], 0],
    ["DEN_VoloAdventure-VoloTaken", ["Gobs-Volo: Watch Volo get Escorted Away"], 0],
    ["DEN_VoloAdventure-VoloTakenAlreadyMet", ["Gobs-Volo: Watch Volo get Escorted Away"], 0],
    ["DEN_VoloAdventure-VoloPrison", ["Gobs-Volo: Find Volo in Cage"], 0],
    ["DEN_VoloAdventure-VoloFree", ["Gobs-Volo: Free Volo"], 0],
    ["DEN_VoloAdventure-VoloEscaped", ["Gobs-Volo: Free Volo"], 0],
    ["DEN_VoloAdventure-VoloCamp", ["Gobs-Volo: Meet Volo in Camp"], 0],
    ["DEN_VoloAdventure-VoloDead", [], 0],
    ["DEN_VoloAdventure-NotSaved", [], 0],
    ["DEN_IdolTheft-AttackFinished", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-AttackTriggered", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-GaveIdol", ["Grove-Idol: Give Idol to Mol"], 0],
    ["DEN_IdolTheft-GroveChanged", [], 0],
    ["DEN_IdolTheft-JoinedRaiders", [], 0],
    ["DEN_IdolTheft-KeptIdol", [], 0],
    ["DEN_IdolTheft-KidsHostile", [], 0],
    ["DEN_IdolTheft-LostAttack", [], 0],
    ["DEN_IdolTheft-NoAttackTheft", ["Grove-Idol: Steal the Idol"], 0],
    ["DEN_IdolTheft-NoIdolTheft", [], 0],
    ["DEN_IdolTheft-RaidFinished", [], 0],
    ["DEN_IdolTheft-RaidStarted", [], 0],
    ["DEN_IdolTheft-TheftRequest", ["Grove-Idol: Get Asked to Steal the Idol"], 0],
    ["DEN_IdolTheft-TheftRequest_AlreadyHad", ["Grove-Idol: Get Asked to Steal the Idol"], 0],
    ["DEN_IdolTheft-TieflingsLeftBefore", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-DestroyTome", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-DestroyTome_Radiant", [], 0],
    ["FOR_DangerousBook_SUB_EvilTome-EvilTome_COMPLETE", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-FindKey", ["Village-Book: Find Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-FindWayToDecypherPage", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-InvestigateMissingKnowledge", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook_SUB_UseTome-KeyInCave", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-KeyLost", ["Village-Book: Learn about Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-ReadTome", ["Village-Book: Learn about Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-UnlockTome", ["Village-Book: Learn about Gem", "Village-Book: Find Gem"], 0],
    ["FOR_DangerousBook_SUB_UseTome-UseTome_Destroyed", [], 0],
    ["FOR_DangerousBook_SUB_UseTome-UseTome_LostTome", [], 0],
    ["FOR_DangerousBook-DestroyedTome", [], 0],
    ["FOR_DangerousBook-FindCellar", ["Village-Book: Learn about Lab"], 0],
    ["FOR_DangerousBook-FindCellarAgain", ["Village-Book: Learn about Lab", "Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-FindLab", ["Village-Book: Learn about Lab"], 0],
    ["FOR_DangerousBook-FindLabAgain", ["Village-Book: Learn about Lab", "Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-FindTome", ["Village-Book: Find Lab"], 0],
    ["FOR_DangerousBook-InvestigateTome", ["Village-Book: Find Tome", "Village-Book: Unlock Tome"], 0],
    ["FOR_DangerousBook-LostTome", [], 0],
    ["FOR_DangerousBook-MadnessKnowledge", ["Village-Book: Find Tome", "Village-Book: Unlock Tome"], 0],
    ["FOR_DangerousBook-ReachedLastPage", ["Village-Book: Read Tome"], 0],
    ["FOR_DangerousBook-SearchLabAfterJournal", ["Village-Book: Find Lab"], 0],
    ["FOR_IncompleteMasterwork-FindJournal", ["Village-Forge: Find Journal"], 0],
    ["FOR_IncompleteMasterwork-FindPlansAfterJournal", ["Village-Forge: Find Plans"], 0],
    ["FOR_IncompleteMasterwork-FindPlansBeforeJournal", ["Village-Forge: Find Plans"], 0],
    ["FOR_UnfortunateGnome-Approach", ["Village-Gnome: Find Windmill"], 0],
    ["FOR_UnfortunateGnome-GoblinsAttacked", ["Village-Gnome: Talk to Goblins"], 0],
    ["FOR_UnfortunateGnome-Pacified", ["Village-Gnome: Talk to Goblins", "Village-Gnome: Get Rid of Goblins"], 0],
    ["FOR_UnfortunateGnome-Defeated", ["Village-Gnome: Get Rid of Goblins"], 0],
    ["FOR_UnfortunateGnome-WindmillStopped", ["Village-Gnome: Stop Windmill"], 0],
    ["FOR_UnfortunateGnome-GnomeFreed", ["Village-Gnome: Free Gnome"], 0],
    ["FOR_UnfortunateGnome-GnomeNotToCamp", ["Village-Gnome: Talk to Barcus"], 0],
    ["FOR_UnfortunateGnome-GnomeToCamp", ["Village-Gnome: Talk to Barcus"], 0],
    ["FOR_UnfortunateGnome-GnomeLeft", [], 0],
    ["FOR_UnfortunateGnome-GnomeDied", [], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_MeetArtist", ["Waukeen-Zhent: Meet Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_TwoLoveStory", ["Waukeen-Zhent: Meet Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_AgreedBuy", ["Waukeen-Zhent: Agree to Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_KnowPrice", ["Waukeen-Zhent: Learn Oskar's Price"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LowerPrice", ["Waukeen-Zhent: Learn Oskar's Price"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByBribe", ["Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByPersuade", ["Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_FreedByViolence", ["Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LeftForBG", ["Waukeen-Zhent: Free Oskar"], 0],
    ["GLO_DoubtingArtist-ZhentDungeon_LeftLevelOskarFree", ["Waukeen-Zhent: Free Oskar"], 0],
    ["PLA_GrandDukeRescue-OrderedBreachInn", ["Waukeen-Fire: Notice Fire"], 0],
    ["PLA_GrandDukeRescue-OrderedBreachInn_Fail", ["Waukeen-Fire: Notice Fire"], 0],
    ["PLA_GrandDukeRescue-EnteredInn", ["Waukeen-Fire: Enter Inn"], 0],
    ["PLA_GrandDukeRescue-FoundStuckHalfElf", ["Waukeen-Fire: Find Benryn"], 0],
    ["PLA_GrandDukeRescue-FoundCounsellor", ["Waukeen-Fire: Find Florrick"], 0],
    ["PLA_GrandDukeRescue-FreedCounsellor", ["Waukeen-Fire: Rescue Florrick"], 0],
    ["PLA_GrandDukeRescue-LearnedDukeMissingCounsellor", ["Waukeen-Fire: Learn about Duke"], 0],
    ["PLA_GrandDukeRescue-LearnedDukeMissingSwD", ["Waukeen-Fire: Learn about Duke"], 0],
    ["PLA_GrandDukeRescue-Counsellor_AcceptedHelp_Moonrise", ["Waukeen-Fire: Accept Mission to Rescue Duke"], 0],
    ["PLA_GrandDukeRescue-Counsellor_AcceptedHelp_NoLocation", ["Waukeen-Fire: Accept Mission to Rescue Duke"], 0],
    ["PLA_GrandDukeRescue-LearnedMoonrise", [], 0],
    ["PLA_GrandDukeRescue-Counsellor_DidntRescue", [], 0],
    ["PLA_GrandDukeRescue-Counsellor_RefusedHelp", [], 0],
    ["PLA_StuckHalfElf-Dead", [], 0],
    ["PLA_StuckHalfElf-Defeated", [], 0],
    ["PLA_StuckHalfElf-Start", ["Waukeen-Fire: Find Benryn"], 0],
    ["PLA_StuckHalfElf-Freed1", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-Freed2", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-Safe", ["Waukeen-Fire: Rescue Benryn"], 0],
    ["PLA_StuckHalfElf-LearnedWife", ["Waukeen-Fire: Learn about Benryn's Wife"], 0],
    ["PLA_StuckHalfElf-ReachedWife", ["Waukeen-Fire: Learn about Benryn's Wife"], 0],
    ["PLA_StuckHalfElf-FoundWife", ["Waukeen-Fire: Learn about Benryn's Wife", "Waukeen-Fire: Show Benryn his Wife"], 0],
    ["PLA_StuckHalfElf-KnowDowry", ["Waukeen-Fire: Learn about Dowry"], 0],
    ["PLA_StuckHalfElf-KnowDowry_Benryn", ["Waukeen-Fire: Learn about Dowry"], 0],
    ["PLA_StuckHalfElf-DowryGold", ["Waukeen-Fire: Learn about Dowry", "Waukeen-Fire: Recover Dowry"], 0],
    ["PLA_StuckHalfElf-ReturnedGold", ["Waukeen-Fire: Return Dowry"], 0],
    ["PLA_StuckHalfElf-KeptGold", [], 0],
    ["PLA_StuckHalfElf-ReachedNoReturn", [], 0],
    ["PLA_PaladinsOfTyr-MetAnders_AgreedHelp", ["Karlach-Tyr: Agree to Help Anders"], 0],
    ["PLA_PaladinsOfTyr-MetKarlach", ["Karlach-Tyr: Meet Karlach"], 0],
    ["PLA_PaladinsOfTyr-LearntZarielFollowers", ["Karlach-Tyr: Learn Anders Follows Zariel"], 0],
    ["PLA_PaladinsOfTyr-LearntZarielFollowers_Corpse", ["Karlach-Tyr: Learn Anders Follows Zariel"], 0],
    ["PLA_PaladinsOfTyr-KarlachRecruited", ["Karlach-Tyr: Recruit Karlach"], 0],
    ["PLA_PaladinsOfTyr-KarlachRecruited_AndersNotMet", ["Karlach-Tyr: Recruit Karlach"], 0],
    ["PLA_PaladinsOfTyr-KillThePaladins", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-PaladinsPermadefeated", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-AndersPermadefeated", ["Karlach-Tyr: Kill the Paladins"], 0],
    ["PLA_PaladinsOfTyr-TakeHead", [], 0],
    ["PLA_PaladinsOfTyr-DeliverHead", [], 0],
    ["PLA_PaladinsOfTyr-KarlachBetrayed", [], 0],
    ["PLA_PaladinsOfTyr-KarlachPermaDefeated", [], 0],
    ["PLA_PaladinsOfTyr-KilledKarlach_NoReward", [], 0],
    ["PLA_PaladinsOfTyr-KilledKarlach_Reward", [], 0],
    ["PLA_PaladinsOfTyr-PointOfNoReturn", [], 0],
    ["PLA_PaladinsOfTyr-HeadNotAvailable", [], 0],
    ["PLA_PaladinsOfTyr-KarlachPermanentlyLeaves", [], 0],
    ["PLA_ZhentShipment-FoundOrders", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-SpokeWithDead", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-FoundCaravan", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-AgreedHelp", ["Waukeen-Zhent: Find Caravan"], 0],
    ["PLA_ZhentShipment-NoticedStruggle_Cave", ["Waukeen-Zhent: Find Caravan", "Waukeen-Zhent: Notice Struggle"], 0],
    ["PLA_ZhentShipment-NoticedStruggle_Hideout", ["Waukeen-Zhent: Find Caravan", "Waukeen-Zhent: Notice Struggle"], 0],
    ["PLA_ZhentShipment-Instigated", [], 0],
    ["PLA_ZhentShipment-GnollGone_HasMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_NotMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_OneDied_NotMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-GnollGone_RuganDied_HasMet", ["Waukeen-Zhent: Kill Gnolls"], 0],
    ["PLA_ZhentShipment-SavedAgents", ["Waukeen-Zhent: Rescue Agents"], 0],
    ["PLA_ZhentShipment-AgentsDied_Cave", [], 0],
    ["PLA_ZhentShipment-AgentsDied_Hideout", [], 0],
    ["PLA_ZhentShipment-AgentsDied_NoSave", [], 0],
    ["PLA_ZhentShipment-SavedOlly_GotCargo_Hideout", [], 0],
    ["PLA_ZhentShipment-SavedAgents_TookCargo", [], 0],
    ["PLA_ZhentShipment-GotCargo_NoPassword", [], 0],
    ["PLA_ZhentShipment-NoSave_GotCargo_Hideout", [], 0],
    ["PLA_ZhentShipment-TalkedToOlly_Cave", [], 0],
    ["PLA_ZhentShipment-TalkedToOlly_Hideout", [], 0],
    ["PLA_ZhentShipment-GotPassword", ["Waukeen-Zhent: Learn Password"], 0],
    ["PLA_ZhentShipment-GotPasswordDead", ["Waukeen-Zhent: Learn Password"], 0],
    ["PLA_ZhentShipment-GotDirectionsDead", [], 0],
    ["PLA_ZhentShipment-EnteredHideout", ["Waukeen-Zhent: Enter Zhentarim Hideout"], 0],
    ["PLA_ZhentShipment-Rewarded_ZhentReturned", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Rewarded_OnlyCargo", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Rewarded_SentToBG", ["Waukeen-Zhent: Return Cargo"], 0],
    ["PLA_ZhentShipment-Attacked", [], 0],
    ["PLA_ZhentShipment-ChestOpened", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_Attacked", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_ChestLost", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_HadChest", [], 0],
    ["PLA_ZhentShipment-HideoutFallback_NotAllowed", [], 0],
    ["PLA_ZhentShipment-LeftAct", [], 0],
    ["PLA_ZhentShipment-LeftAct_notDecided", [], 0],
    ["PLA_ZhentShipment-Rewarded_NoCargo", [], 0],
    ["PLA_ZhentShipment-RuganForced", [], 0],
    ["SHA_Nightsong-LearnedBryanMap", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-LearnedLocation", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-ReadAgedJournal", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["SHA_Nightsong-SawBook", ["Gobs-Nightsong: Find Clues to Nightsong"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestArtefactAtCamp", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestReceivedArtefact", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestRecruitedShadowheart", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-AcceptedQuestSawShadowHeartAndBoxAtCamp", ["Plot-Art: Notice Artefact"], 0],
    ["GLO_ArtefactDiscovery-GoblinCampGoblinKing", ["Plot-Art: Hear Ragzlin talk about Artefact"], 0],
    ["GLO_ArtefactDiscovery-GoblinCampMinthara", ["Plot-Art: Hear Minthara talk about Artefact"], 0],
    ["GLO_Tadpole_SUB_Druid-Betrayal_DruidDead_Halsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-DruidLeaderDied_NoResearch", [], 0],
    ["GLO_Tadpole_SUB_Druid-DruidLeaderDied_Research", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_DrowDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_KingDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_AoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_KillLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Known_LeadershipDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_PriestessDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_AoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_KillLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-FoundHalsin_Unknown_LeadershipDead", [], 0],
    ["GLO_Tadpole_SUB_Druid-Halsin_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Known_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinAtGrove_Unknown_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_AoDStarted", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_EndedAoD", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_KilledLeaders", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_KilledLeaders_SkipGrove", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_NoHelp_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinLeft_NoHelp_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinReturned_Known", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinReturned_Unknown", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Asharak", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Cerys", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Return", [], 0],
    ["GLO_Tadpole_SUB_Druid-HalsinSentToRath_Talked", [], 0],
    ["GLO_Tadpole_SUB_Druid-HeardHalsinSwD", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedBear", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedEscaped", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedExpeditionGoal", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedHalsinDiary", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedHalsinPosition", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedKilledOrCaptured", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedLostHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedLostHalsin_Update", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedPit", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedResearchHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-LearnedResearchHalsin_Update", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReadHalsinDiary", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReportHalsin_AoDStarted", [], 0],
    ["GLO_Tadpole_SUB_Druid-ReportHalsin_LeadersDefeated", [], 0],
    ["GLO_Tadpole_SUB_Druid-StillNeedToSpeakToHalsin", [], 0],
    ["GLO_Tadpole_SUB_Druid-TalkedLeader_Celebrate", [], 0],
    ["GLO_Tadpole_SUB_Priestess-GotBranded", [], 0],
    ["GLO_Tadpole_SUB_Priestess-LearnPriestess", [], 0],
    ["GLO_Tadpole_SUB_Priestess-Priestess_PointOfNoReturn", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessDied", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessImprisoned", [], 0],
    ["GLO_Tadpole_SUB_Priestess-PriestessTurnedHostile", [], 0],
    ["GLO_Tadpole_SUB_Priestess-ReachedQuarters", ["Gobs: Follow Gut to her Quarters"], 0],
    ["GLO_Tadpole_SUB_Priestess-RefusedHelpGut", [], 0],
    ["GLO_UnleashPowers-DaisyAskedConsume", ["Tadpole: Guardian Suggests Consuming Tadpole"], 0],
    ["GLO_UnleashPowers-FindMoreTadpoles", ["Tadpole: Found a Tadpole"], 0],
    ["GLO_UnleashPowers-FindTadpole", ["Tadpole: Told by Guardian to find Tadpoles"], 0],
    ["GLO_UnleashPowers-FoundTadpole", ["Tadpole: Found a Tadpole"], 0],
    ["GLO_UnleashPowers-UsedIllithidPersuasion", ["Tadpole: Used Illithid Persuasion"], 0],
    ["ORI_COM_Karlach-Recruited_PaladinsDefeated", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach-Recruited_PaladinsNotDefeated", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach-ExploreSwordCoast", ["Karlach-Heart: Recruit Karlach"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-RecruitedKarlach_KnowsCanBeUpgraded", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-KnowsDammon", ["Karlach-Heart: Introduce Karlach to Dammon"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-FindInfernalMetal_FirstUpgrade", ["Karlach-Heart: Find Infernal Metal"], 0],
    ["ORI_COM_Karlach_SUB_ForgingOfTheHeart-GetFirstUpgrade", ["Karlach-Heart: Get First Heart Upgrade"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_DoesNotKnowDammon", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_DoesNotKnowDammon_BeforePaladins", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_KnowsDammon", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Karlach-ForgingOfTheHeart_KnowsDammon_BeforePaladins", ["Karlach-Heart: Learn about Heart Upgrades"], 0],
    ["ORI_COM_Laezel-RecruitedLaezel_Beach", [], 0],
    ["ORI_COM_Laezel-RecruitedLaezel_Cage", [], 0],
    ["ORI_COM_Laezel-FoundOutAboutZorru", ["Lae'zel: Find out about Zorru"], 0],
    ["ORI_COM_Laezel-AskedZevlorAboutZorru", [], 0],
    ["ORI_COM_Laezel-FoundZorruLZAbsent", [], 0],
    ["ORI_COM_Laezel-GotNoInfoFromZorru", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-GotNoInfoFromZorruWithoutKnowingHim", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-ZorruDied", [], 0],
    ["ORI_COM_Laezel-ZorruMarkedMap", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-ZorruMarkedMapWithoutKnowingAboutHim", ["Lae'zel: Talk to Zorru"], 0],
    ["ORI_COM_Laezel-TalkedToDeadTiefling", [], 0],
    ["ORI_COM_Laezel-SawDragonRider", ["Lae'zel: See Dragon Rider"], 0],
    ["ORI_COM_Laezel-SawDragonRider_KnowsAboutGithyankiPatrol", ["Lae'zel: See Dragon Rider"], 0],
    ["ORI_COM_Laezel-LaezelRanToKnight", [], 0],
    ["ORI_COM_Laezel-ChokepointCombatStarted", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ChokepointDefeated", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ResolvedPeaceCreche", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ResolvedPeaceNoCreche", ["Lae'zel: Deal with Patrol"], 0],
    ["ORI_COM_Laezel-ReadCrecheMap", ["Lae'zel: Learn Creche Location"], 0],
    ["ORI_COM_Laezel-LaezelDied_FoundShadowcursedInSCL", [], 0],
    ["ORI_COM_Laezel-LaezelDied_Generic", [], 0],
    ["ORI_COM_Laezel-LaezelDied_GoBackToMountainpass", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledAtCampNight", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledByShadowheart", [], 0],
    ["ORI_COM_Laezel-LaezelDied_KilledByVossInPlains", [], 0],
    ["ORI_COM_Laezel-LaezelDied_MissingAtMountainpass", [], 0],
    ["ORI_COM_Laezel-LaezelTurnedHostile_Generic", [], 0],
    ["ORI_COM_Laezel-TurnedHostileAtChokepoint", [], 0],
    ["ORI_COM_ShadowHeart-CampFight_LaezelDied", [], 0],
    ["ORI_COM_ShadowHeart-CampFight_Peace", ["Shart: Resolve Camp Fight (both live)"], 0],
    ["ORI_COM_ShadowHeart-CampFight_ShadowheartDied", [], 0],
    ["ORI_COM_ShadowHeart-CompanionHostile", [], 0],
    ["ORI_COM_ShadowHeart-CompanionLowRelation", [], 0],
    ["ORI_COM_ShadowHeart-CompanionMurdered", [], 0],
    ["ORI_COM_ShadowHeart-Recruited_Beach", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Box", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Camp", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Den", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Githyanki", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Laezel", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-Recruited_Reanimated", ["Shart: Recruit Shadowheart"], 0],
    ["ORI_COM_ShadowHeart-SawBox", [], 0],
    ["ORI_COM_ShadowHeart-SawIncurableWound", ["Shart: See Wound"], 0],
    ["ORI_COM_Wyll-RecruitedWyll", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorDead", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorDeadKnown", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorRefused", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorTalked", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-CouncillorTalkedKnowsMT", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-InnReached", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-Kidnapped", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-LearntMT", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-TavernBurnt", [], 0],
    ["ORI_COM_Wyll_SUB_Duke-RavengardFather", ["Wyll: Learn Wyll's Father"], 0],
    ["ORI_COM_Wyll-CompanionHostile", [], 0],
    ["ORI_COM_Wyll-CompanionLowRelation", [], 0],
    ["ORI_COM_Wyll-CompanionMurdered", [], 0],
    ["ORI_COM_Wyll-KarlachHired", ["Wyll: Resolved Conflict with Karlach"], 0],
    ["ORI_COM_Wyll-KarlachKilled", [], 0],
    ["ORI_COM_Wyll-MetPaladinsOfTyr", [], 0],
    ["ORI_COM_Wyll-PostKarlachDead", [], 0],
    ["ORI_COM_Wyll-PostKarlachSpared", ["Wyll: Resolved Conflict with Karlach"], 0],
    ["ORI_COM_Wyll-RecrtuitedMetKarlach", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedAmbush", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedAmbushKarlachKilled", ["Wyll: Recruited"], 0],
    ["ORI_COM_Wyll-RecruitedKarlachNoWyll", [], 0],
    ["ORI_COM_Wyll-MizorasJudgementDevil", ["Wyll: Meet Mizora"], 0],
    ["ORI_COM_Wyll-MizorasJudgementReward", ["Wyll: Meet Mizora"], 0],

    ["GLO_Tadpole_SUB_Apprentice-SavedHalsin_BeforeTadpoled", ["Victory_Halsin"], 0],
    ["GLO_Tadpole_SUB_Creche_SpeakToDoctor_BetrayedByVlaakith", ["Victory_Wwargaz"], 1],
]
