
# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.
LOCATION_NAME_TO_ID = {
    "Tut: Learn about the Helm": 1,
    "Tut: Reach the Helm": 2,
    "Tut: Connect the Transponder": 3,
    "Tut-SH: Find Captive": 4,
    "Tut-SH: Find the Rune": 5,
    "Tut-SH: Open the Pod": 6,
    "Tut-SH: Recruit Captive": 7,
    "Crypt: Learn about Crypt": 8,
    "Crypt: Enter Crypt": 9,
    "Crypt: Find Sarcophagus": 10,
    "Crypt: Read Plaque": 11,
    "Crypt: Open Sarcophagus": 12,
    "Crypt: Talk to Withers at Camp": 13,
    "Beach-LZ: Find Lae'zel": 14,
    "Beach-LZ: Talk to Lae'zel": 15,
    "Beach-LZ: Get the Tieflings Away": 16,
    "Beach-LZ: Free Lae'zel": 17,
    "Beach-LZ: Recruit Lae'zel": 18,
    "Tadpole: Wake on Beach": 24,
    "Tadpole: Talk to Lae'zel": 25,
    "Tadpole: Learn about Nettie": 26,
    "Tadpole: Learn about Halsin": 27,
    "Tadpole: Learn about Priestess Gut": 28,
    "Tadpole: See True Soul Meld/Tadpole": 29,
    "Tadpole-Nettie: Talk to Nettie": 30,
    "Tadpole-Nettie: Be Poisoned by Nettie": 31,
    "Tadpole-Nettie: Learn about Antidote": 32,
    "Tadpole-Nettie: Cure the Poison": 33,
    "Grove-Thief: Discover Pickpocketing": 20,
    "Grove-Thief: Learn About Hideout": 21,
    "Grove-Thief: Enter Hideout": 22,
    "Grove-Thief: Get Your Stuff Back": 23,
    "Grove-Harpy: Hear Harpy Song": 34,
    "Grove-Harpy: Find Child": 35,
    "Grove-Harpy: Defeat Harpies": 36,
    "Grove-Harpy: Discover Hideout Password": 37,
    "Grove-Harpy: Tell password to Doni": 38,
    "Grove-Harpy: Meet Mol": 39,
    "Grove-Locket: Recover Locket": 40,
    "Grove-Locket: Return Locket": 41,
    "Grove-Snake: Learn about Arabella": 42,
    "Grove-Snake: Find Arabella": 43,
    "Grove-Snake: Resolve Arabella's Situation": 44,
    "Grove-Snake: Talk to Arabella's Parents": 45,
    "Grove-Kagha: Talk to Zevlor about Kagha": 74,
    "Grove-Kagha: Meet Kagha": 93,
    "Grove-Kagha: Find Note in Grove": 75,
    "Grove-Kagha: Find Note in Swamp": 76,
    "Grove-Kagha: Confront Kagha": 77,
    "Grove-Kagha: Kill the Shadow Druids": 78,
    "Grove-Kagha: Return to Zevlor": 79,
    "Grove-Kagha: Get past Guards": 80,
    "Grove-Kagha: Talk to Rath": 81,
    "Gobs: Arrive at Goblin Camp": 86,
    "Gobs: Learn the Priestess' Name": 90,
    "Gobs: Learn the Drow's Name": 91,
    "Gobs: Learn the King's Name": 92,
    "Gobs: Kill Priestess Gut": 87,
    "Gobs: Kill Dror Ragzlin": 88,
    "Gobs: Defeat (Knock Out) Minthara": 89,
    "Gobs-Halsin: Learn Halsin is Missing": 96,
    "Gobs-Halsin: Found Halsin": 82,
    "Gobs-Halsin: Defeated all Goblin Leaders": 86,
    "Gobs-Halsin: Tell Halsin about Victory": 94,
    "Gobs-Halsin: Tell Tieflings about Halsin's Freedom": 83,
    "Gobs-Halsin: Celebrate with Tieflings": 84,
    "Gobs-Halsin: Tieflings left for Baldur's Gate": 85,
    "Gobs-Halsin: Learn Halsin is a Bear": 95,
    "Gobs-Halsin: Get Reward from Rath": 97,
    "Gale: Recruited": 46,
    "Gale: Died": 47,
    "Gale: Listened to Projection": 48,
    "Gale: Opened Pouch": 49,
    "Gale: Played Flute": 50,
    "Gale: Told Mephit his Name": 51,
    "Gale: Resurrected": 52,
    "Gale: Told about Hunger": 53,
    "Gale: Fed an Item": 54,
    "Gale: Fed a Second Item": 55,
    "Gale: Fed a Third Item": 56,
    "Gale: Told Backstory": 57,
    "Gale: Met Elminster": 58,
    "Astarion: Recruited": 19,
    "Astarion: Learned Vampire": 59,
    "Astarion: Learned Backstory": 60,
    "Astarion: Chat about Tadpole": 61,
    "Astarion: Met Gandrel": 62,
    "Astarion: Learn about Scars": 63,
    "Astarion: Talk to Raphael": 64,
    "Astarian: Learn about Ascension": 65,
    "Astarion: Meet Ulma": 66,
    "Astarion: Meet other Spawn": 67,
    "Astarion: Enter Cazador's Palace": 68,
    "Astarion: Enter Cazador's Dungeon": 69,
    "Astarion: Meet Sebastian": 70,
    "Astarion: Learn about Staff": 71,
    "Astarion: Defeat Cazador": 72,
    "Astarion: Resolve Spawn": 73,
    "Grove-Sazza: Keep Sazza Alive": 98,
    "Grove-Sazza: Free Sazza": 99,
    "Grove-Sazza: Escort Sazza out": 100,
    "Grove-Sazza: Find Sazza at Minthara": 101,
    "Grove-Sazza: Save Sazza Again": 102,
    "Gobs-Volo: Watch Volo get Escorted Away": 103,
    "Gobs-Volo: Find Volo in Cage": 104,
    "Gobs-Volo: Free Volo": 105,
    "Gobs-Volo: Meet Volo in Camp": 106,
    "Grove-Idol: Get Asked to Steal the Idol": 107,
    "Grove-Idol: Steal the Idol": 108,
    "Grove-Idol: Give Idol to Mol": 109,
    "Village-Book: Learn about Lab": 110,
    "Village-Book: Find Lab": 111,
    "Village-Book: Find Tome": 112,
    "Village-Book: Learn about Gem": 116,
    "Village-Book: Find Gem": 113,
    "Village-Book: Unlock Tome": 114,
    "Village-Book: Read Tome": 115,
    "Village-Forge: Find Journal": 116,
    "Village-Forge: Find Plans": 117,
    "Village-Gnome: Find Windmill": 118,
    "Village-Gnome: Talk to Goblins": 119,
    "Village-Gnome: Get Rid of Goblins": 120,
    "Village-Gnome: Stop Windmill": 121,
    "Village-Gnome: Free Gnome": 122,
    "Village-Gnome: Talk to Barcus": 123,
    "Waukeen-Zhent: Meet Oskar": 124,
    "Waukeen-Zhent: Agree to Free Oskar": 125,
    "Waukeen-Zhent: Learn Oskar's Price": 126,
    "Waukeen-Zhent: Free Oskar": 127,
    "Waukeen-Fire: Notice Fire": 128,
    "Waukeen-Fire: Enter Inn": 129,
    "Waukeen-Fire: Find Benryn": 130,
    "Waukeen-Fire: Find Florrick": 131,
    "Waukeen-Fire: Rescue Benryn": 132,
    "Waukeen-Fire: Rescue Florrick": 133,
    "Waukeen-Fire: Learn about Duke": 134,
    "Waukeen-Fire: Accept Mission to Rescue Duke": 135,
    "Waukeen-Fire: Learn about Benryn's Wife": 136,
    "Waukeen-Fire: Show Benryn his Wife": 137,
    "Waukeen-Fire: Learn about Dowry": 138,
    "Waukeen-Fire: Recover Dowry": 139,
    "Waukeen-Fire: Return Dowry": 140,
    "Karlach-Tyr: Agree to Help Anders": 141,
    "Karlach-Tyr: Meet Karlach": 142,
    "Karlach-Tyr: Learn Anders Follows Zariel": 143,
    "Karlach-Tyr: Recruit Karlach": 144,
    "Karlach-Tyr: Kill the Paladins": 145,
    "Waukeen-Zhent: Find Caravan": 146,
    "Waukeen-Zhent: Notice Struggle": 147,
    "Waukeen-Zhent: Kill Gnolls": 148,
    "Waukeen-Zhent: Rescue Agents": 149,
    "Waukeen-Zhent: Learn Password": 150,
    "Waukeen-Zhent: Enter Zhentarim Hideout": 151,
    "Waukeen-Zhent: Return Cargo": 152,
    "Gobs-Nightsong: Find Clues to Nightsong": 153,
    "Plot-Art: Notice Artefact": 154,
    "Plot-Art: Hear Minthara talk about Artefact": 155,
    "Plot-Art: Hear Ragzlin talk about Artefact": 156,
    "Tadpole: Told by Guardian to find Tadpoles": 157,
    "Tadpole: Used Illithid Persuasion": 158,
    "Tadpole: Found a Tadpole": 159,
    "Tadpole: Guardian Suggests Consuming Tadpole": 160,
    "Karlach-Heart: Recruit Karlach": 161,
    "Karlach-Heart: Learn about Heart Upgrades": 162,
    "Karlach-Heart: Introduce Karlach to Dammon": 163,
    "Karlach-Heart: Find Infernal Metal": 164,
    "Karlach-Heart: Get First Heart Upgrade": 165,
    "Gobs: Follow Gut to her Quarters": 166,
    "Lae'zel: Find out about Zorru": 168,
    "Lae'zel: Talk to Zorru": 169,
    "Lae'zel: See Dragon Rider": 170,
    "Lae'zel: Deal with Patrol": 171,
    "Lae'zel: Learn Creche Location": 172,
    "Shart: Recruit Shadowheart": 173,
    "Shart: Resolve Camp Fight (both live)": 174,
    "Shart: See Wound": 175,
    "Wyll: Recruited": 176,
    "Wyll: Resolved Conflict with Karlach": 177,
    "Wyll: Meet Mizora": 178,
    "Wyll: Learn Wyll's Father": 179,


}
