
# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.
LOCATION_NAME_ID_REGION = [["Tut: Learn about the Helm", 1, "tutorial"],
    ["Tut: Reach the Helm", 2, "tutorial"],
    ["Tut: Connect the Transponder", 3, "tutorial"],
    ["Tut-SH: Find Captive", 4, "tutorial"],
    ["Tut-SH: Find the Rune", 5, "tutorial"],
    ["Tut-SH: Open the Pod", 6, "tutorial"],
    ["Tut-SH: Recruit Captive", 7, "tutorial"],
    ["Beach-LZ: Find Lae'zel", 8, "beach"],
    ["Beach-LZ: Talk to Lae'zel", 9, "beach"],
    ["Beach-LZ: Get the Tieflings Away", 10, "beach"],
    ["Beach-LZ: Free Lae'zel", 11, "beach"],
    ["Beach-LZ: Recruit Lae'zel", 12, "beach"],
    ["Astarion: Recruited", 13, "beach"],
    ["Tadpole: Wake on Beach", 14, "beach"],
    ["Tadpole: Talk to Lae'zel", 15, "beach"],
    ["Gale: Recruited", 16, "beach"],
    ["Gale: Died", 17, "beach"],
    ["Gale: Listened to Projection", 18, "beach"],
    ["Gale: Opened Pouch", 19, "beach"],
    ["Gale: Played Flute", 20, "beach"],
    ["Gale: Told Mephit his Name", 21, "beach"],
    ["Gale: Resurrected", 22, "beach"],
    ["Plot-Art: Notice Artefact", 23, "beach"],
    ["Shart: Recruit Shadowheart", 24, "beach"],
    ["Shart: Resolve Camp Fight (both live)", 25, "beach"],
    ["Tadpole: Learn About Creche", 26, "beach"],
    ["Crypt: Learn about Crypt", 27, "crypt"],
    ["Crypt: Enter Crypt", 28, "crypt"],
    ["Crypt: Find Sarcophagus", 29, "crypt"],
    ["Crypt: Open Sarcophagus", 30, "crypt"],
    ["Grove-Thief: Discover Pickpocketing", 31, "grove"],
    ["Grove-Thief: Learn About Hideout", 32, "grove"],
    ["Grove-Thief: Enter Hideout", 33, "grove"],
    ["Grove-Thief: Get Your Stuff Back", 34, "grove"],
    ["Tadpole: Learn about Nettie", 35, "grove"],
    ["Tadpole: Learn about Halsin", 36, "grove"],
    ["Tadpole: Learn about Priestess Gut", 37, "grove"],
    ["Tadpole: See True Soul Meld/Tadpole", 38, "grove"],
    ["Tadpole-Nettie: Talk to Nettie", 39, "grove"],
    ["Tadpole-Nettie: Be Poisoned by Nettie", 40, "grove"],
    ["Tadpole-Nettie: Learn about Antidote", 41, "grove"],
    ["Tadpole-Nettie: Cure the Poison", 42, "grove"],
    ["Grove-Harpy: Hear Harpy Song", 43, "grove"],
    ["Grove-Harpy: Find Child", 44, "grove"],
    ["Grove-Harpy: Defeat Harpies", 45, "grove"],
    ["Grove-Harpy: Discover Hideout Password", 46, "grove"],
    ["Grove-Harpy: Tell password to Doni", 47, "grove"],
    ["Grove-Harpy: Meet Mol", 48, "grove"],
    ["Grove-Locket: Recover Locket", 49, "grove"],
    ["Grove-Locket: Return Locket", 50, "grove"],
    ["Grove-Snake: Learn about Arabella", 51, "grove"],
    ["Grove-Snake: Find Arabella", 52, "grove"],
    ["Grove-Snake: Resolve Arabella's Situation", 53, "grove"],
    ["Grove-Snake: Talk to Arabella's Parents", 54, "grove"],
    ["Grove-Kagha: Talk to Zevlor about Kagha", 55, "grove"],
    ["Grove-Kagha: Meet Kagha", 56, "grove"],
    ["Grove-Kagha: Find Note in Grove", 57, "grove"],
    ["Grove-Kagha: Get past Guards", 58, "grove"],
    ["Grove-Kagha: Talk to Rath", 59, "grove"],
    ["Lae'zel: Find out about Zorru", 60, "grove"],
    ["Lae'zel: Talk to Zorru", 61, "grove"],
    ["Shart: See Wound", 62, "grove"],
    ["Wyll: Recruited", 63, "grove"],
    ["Grove-Sazza: Keep Sazza Alive", 64, "grove"],
    ["Grove-Sazza: Free Sazza", 65, "grove"],
    ["Grove-Sazza: Escort Sazza out", 66, "grove"],
    ["Grove-Idol: Get Asked to Steal the Idol", 67, "grove"],
    ["Shart: Discuss Wound", 68, "grove"],
    ["Shart: Learn about Wolf Phobia", 69, "grove"],
    ["Shart: Discuss Wolf Phobia", 70, "grove"],
    ["Shart: Learn about BG Mission", 71, "grove"],
    ["Grove: Rescue Nadira", 72, "grove"],
    ["Grove: Open the Vault", 73, "grove"],
    ["Grove: Move Tuffet", 74, "grove"],
    ["Grove: Save Findal", 75, "grove"],
    ["Grove: Train Guex", 76, "grove"],
    ["Grove: Loot Haystack", 77, "grove"],
    ["Grove: Convince Rolan to Stay", 78, "grove"],
    ["Grove: Make Friends with Mol", 79, "grove"],
    ["Grove: Help Alfira with her Song", 80, "grove"],
    ["Tadpole: Learned about Ethel", 81, "grove"],
    ["Village-Book: Learn about Lab", 82, "blighted_village"],
    ["Village-Book: Find Lab", 83, "blighted_village"],
    ["Village-Book: Find Tome", 84, "blighted_village"],
    ["Village-Book: Find Gem", 85, "blighted_village"],
    ["Village-Book: Unlock Tome", 86, "blighted_village"],
    ["Village-Book: Read Tome", 87, "blighted_village"],
    ["Village-Book: Learn about Gem", 88, "blighted_village"],
    ["Village-Forge: Find Journal", 89, "blighted_village"],
    ["Village-Forge: Find Plans", 90, "blighted_village"],
    ["Village-Gnome: Find Windmill", 91, "blighted_village"],
    ["Village-Gnome: Talk to Goblins", 92, "blighted_village"],
    ["Village-Gnome: Get Rid of Goblins", 93, "blighted_village"],
    ["Village-Gnome: Stop Windmill", 94, "blighted_village"],
    ["Village-Gnome: Free Gnome", 95, "blighted_village"],
    ["Village-Gnome: Talk to Barcus", 96, "blighted_village"],
    ["Tadpole: Used Illithid Persuasion", 97, "blighted_village"],
    ["Tadpole: Found a Tadpole", 98, "blighted_village"],
    ["Village: Tame Scratch", 99, "blighted_village"],
    ["Village: Tame Owlbear Cub", 100, "blighted_village"],
    ["Village: Open Selune's Stash", 101, "blighted_village"],
    ["Village-Book: Open Lab Mirror", 102, "blighted_village"],
    ["Gobs-Halsin: Found Halsin", 103, "goblin_camp"],
    ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom", 104, "goblin_camp"],
    ["Gobs-Halsin: Celebrate with Tieflings", 105, "goblin_camp"],
    ["Gobs-Halsin: Tieflings left for Baldur's Gate", 106, "goblin_camp"],
    ["Gobs: Arrive at Goblin Camp", 107, "goblin_camp"],
    ["Gobs-Halsin: Defeated all Goblin Leaders", 108, "goblin_camp"],
    ["Gobs: Kill Priestess Gut", 109, "goblin_camp"],
    ["Gobs: Kill Dror Ragzlin", 110, "goblin_camp"],
    ["Gobs: Defeat (Knock Out) Minthara", 111, "goblin_camp"],
    ["Gobs: Learn the Priestess' Name", 112, "goblin_camp"],
    ["Gobs: Learn the Drow's Name", 113, "goblin_camp"],
    ["Gobs: Learn the King's Name", 114, "goblin_camp"],
    ["Gobs-Halsin: Tell Halsin about Victory", 115, "goblin_camp"],
    ["Gobs-Halsin: Learn Halsin is a Bear", 116, "goblin_camp"],
    ["Gobs-Halsin: Learn Halsin is Missing", 117, "goblin_camp"],
    ["Gobs-Halsin: Get Reward from Rath", 118, "goblin_camp"],
    ["Grove-Sazza: Find Sazza at Minthara", 119, "goblin_camp"],
    ["Grove-Sazza: Save Sazza Again", 120, "goblin_camp"],
    ["Gobs-Volo: Watch Volo get Escorted Away", 121, "goblin_camp"],
    ["Gobs-Volo: Find Volo in Cage", 122, "goblin_camp"],
    ["Gobs-Volo: Free Volo", 123, "goblin_camp"],
    ["Gobs-Volo: Meet Volo in Camp", 124, "goblin_camp"],
    ["Grove-Idol: Steal the Idol", 125, "goblin_camp"],
    ["Grove-Idol: Give Idol to Mol", 126, "goblin_camp"],
    ["Gobs-Nightsong: Find Clues to Nightsong", 127, "goblin_camp"],
    ["Plot-Art: Hear Minthara talk about Artefact", 128, "goblin_camp"],
    ["Plot-Art: Hear Ragzlin talk about Artefact", 129, "goblin_camp"],
    ["Tadpole: Told by Guardian to find Tadpoles", 130, "goblin_camp"],
    ["Tadpole: Guardian Suggests Consuming Tadpole", 131, "goblin_camp"],
    ["Gobs: Follow Gut to her Quarters", 132, "goblin_camp"],
    ["Gobs-Halsin: Tell Ormn that Halsin was Saved", 133, "goblin_camp"],
    ["Gobs: Win the Chicken Chase", 134, "goblin_camp"],
    ["Gobs: Crush Crusher (in dialogue)", 135, "goblin_camp"],
    ["Gobs: Scry with Ragzlin", 136, "goblin_camp"],
    ["Gobs: Free Brakkal", 137, "goblin_camp"],
    ["Gobs: Get Book from Piddle", 138, "goblin_camp"],
    ["Gobs: Experience Abdirak's Penance", 139, "goblin_camp"],
    ["Gobs: Find Moon Puzzle in Temple", 140, "goblin_camp"],
    ["Gobs: Solve Moon Puzzle in Temple", 141, "goblin_camp"],
    ["Gobs: Free Liam", 142, "goblin_camp"],
    ["Gale: Told about Hunger", 143, "waukeen"],
    ["Gale: Fed an Item", 144, "waukeen"],
    ["Waukeen-Zhent: Meet Oskar", 145, "waukeen"],
    ["Waukeen-Zhent: Agree to Free Oskar", 146, "waukeen"],
    ["Waukeen-Zhent: Learn Oskar's Price", 147, "waukeen"],
    ["Waukeen-Zhent: Free Oskar", 148, "waukeen"],
    ["Waukeen-Fire: Notice Fire", 149, "waukeen"],
    ["Waukeen-Fire: Enter Inn", 150, "waukeen"],
    ["Waukeen-Fire: Find Benryn", 151, "waukeen"],
    ["Waukeen-Fire: Find Florrick", 152, "waukeen"],
    ["Waukeen-Fire: Rescue Benryn", 153, "waukeen"],
    ["Waukeen-Fire: Rescue Florrick", 154, "waukeen"],
    ["Waukeen-Fire: Learn about Duke", 155, "waukeen"],
    ["Waukeen-Fire: Accept Mission to Rescue Duke", 156, "waukeen"],
    ["Waukeen-Fire: Learn about Benryn's Wife", 157, "waukeen"],
    ["Waukeen-Fire: Show Benryn his Wife", 158, "waukeen"],
    ["Waukeen-Fire: Learn about Dowry", 159, "waukeen"],
    ["Waukeen-Fire: Recover Dowry", 160, "waukeen"],
    ["Waukeen-Fire: Return Dowry", 161, "waukeen"],
    ["Karlach-Tyr: Agree to Help Anders", 162, "waukeen"],
    ["Karlach-Tyr: Meet Karlach", 163, "waukeen"],
    ["Karlach-Tyr: Learn Anders Follows Zariel", 164, "waukeen"],
    ["Karlach-Tyr: Recruit Karlach", 165, "waukeen"],
    ["Karlach-Tyr: Kill the Paladins", 166, "waukeen"],
    ["Waukeen-Zhent: Find Caravan", 167, "waukeen"],
    ["Waukeen-Zhent: Notice Struggle", 168, "waukeen"],
    ["Waukeen-Zhent: Kill Gnolls", 169, "waukeen"],
    ["Waukeen-Zhent: Rescue Agents", 170, "waukeen"],
    ["Waukeen-Zhent: Learn Password", 171, "waukeen"],
    ["Waukeen-Zhent: Enter Zhentarim Hideout", 172, "waukeen"],
    ["Waukeen-Zhent: Return Cargo", 173, "waukeen"],
    ["Karlach-Heart: Recruit Karlach", 174, "waukeen"],
    ["Karlach-Heart: Learn about Heart Upgrades", 175, "waukeen"],
    ["Karlach-Heart: Introduce Karlach to Dammon", 176, "waukeen"],
    ["Karlach-Heart: Find Infernal Metal", 177, "waukeen"],
    ["Karlach-Heart: Get First Heart Upgrade", 178, "waukeen"],
    ["Lae'zel: See Dragon Rider", 179, "waukeen"],
    ["Lae'zel: Deal with Patrol", 180, "waukeen"],
    ["Lae'zel: Learn Creche Location", 181, "waukeen"],
    ["Wyll: Resolved Conflict with Karlach", 182, "waukeen"],
    ["Wyll: Meet Mizora", 183, "waukeen"],
    ["Wyll: Learn Wyll's Father", 184, "waukeen"],
    ["Shart: Learn about Shar Worship", 185, "waukeen"],
    ["Grove-Kagha: Find Note in Swamp", 186, "hag"],
    ["Grove-Kagha: Confront Kagha", 187, "hag"],
    ["Grove-Kagha: Kill the Shadow Druids", 188, "hag"],
    ["Grove-Kagha: Return to Zevlor", 189, "hag"],
    ["Astarion: Learned Vampire", 190, "hag"],
    ["Astarion: Learned Backstory", 191, "hag"],
    ["Astarion: Chat about Tadpole", 192, "hag"],
    ["Astarion: Met Gandrel", 193, "hag"],
    ["Hag: Find Mayrina's Brothers", 194, "hag"],
    ["Hag: Meet Mayrina", 195, "hag"],
    ["Hag: Force Ethel into her Lair", 196, "hag"],
    ["Hag: Enter Ethel's Lair", 197, "hag"],
    ["Hag: Fight Ethel in her Lair", 198, "hag"],
    ["Hag: Rescue Mayrina", 199, "hag"],
    ["Hag: Find the Bitter Divorce", 200, "hag"],
    ["Hag: Send Mayrina off to Baldur's Gate", 201, "hag"],
    ["Tadpole: Learned about Moonrise Towers", 202, "underdark"],
    ["Grotto: Meet Omeluum", 203, "underdark"],
    ["Grotto: Tell Blurg about Tadpole", 204, "underdark"],
    ["Grotto: Get Omeluum's Recipe", 205, "underdark"],
    ["Grotto: Find Timmask Spores", 206, "underdark"],
    ["Grotto: Find Tongue of Madness", 207, "underdark"],
    ["Grotto: Drink Omeluum's Potion", 208, "underdark"],
    ["Grotto: Get Mind Shielding Ring", 209, "underdark"],
    ["Underdark: Find Sussur Bark", 210, "underdark"],
    ["Underdark: Learn about Sussur Bark", 211, "underdark"],
    ["Underdark: Forge Masterwork", 212, "underdark"],
    ["Grotto: Talk to Derryth", 213, "underdark"],
    ["Grotto: Find Baelen", 214, "underdark"],
    ["Grotto: Tell Derryth the Result", 215, "underdark"],
    ["Grotto: Agree to Kill Duergar", 216, "underdark"],
    ["Grotto: Find Duergar", 217, "underdark"],
    ["Grotto: Kill Duergar", 218, "underdark"],
    ["Grotto: Tell Glut about Duergar", 219, "underdark"],
    ["Grotto: Hear Glut's Plan", 220, "underdark"],
    ["Grotto: Decide which Sovereign to Support", 221, "underdark"],
    ["Grotto: Reward for Killing Sovereign", 222, "underdark"],
    ["Grotto: Kill one of the Sovereigns", 223, "underdark"],
    ["Grotto: Enter Guardian Gate", 224, "underdark"],
    ["Grotto: Get Reward for Duergar", 225, "underdark"],
    ["Grotto: Accept Quest to Kill Nere", 226, "underdark"],
    ["Grotto: Cure Thulla", 227, "underdark"],
    ["Grotto: Meet Thulla", 228, "underdark"],
    ["Underdark: Find Runaway", 229, "underdark"],
    ["Underdark: Get Told about Runaway", 230, "underdark"],
    ["Underdark: Get Boots", 231, "underdark"],
    ["Gale: Fed a Second Item", 232, "waukeen"],
    ["Gale: Fed a Third Item", 233, "waukeen"],
    ["Gale: Told Backstory", 234, "waukeen"],
    ["Grotto: Asked to Save Gnomes", 235, "underdark"],
    ["Underdark: Activate Arcane Tower", 236, "underdark"],
    ["Underdark: Put Flowers on the Pet Grave near Arcane Tower", 237, "underdark"],
    ["Underdark: Identify Chest of the Mundane", 238, "underdark"],
    ["Underdark: Get Phalar Aluve", 239, "underdark"],
    ["Nightsong: Enter Underdark", 240, "underdark"],
    ["Grym: Lead Duergar Mutiny", 241, "grymforge"],
    ["Grym: Take Nere's Head", 242, "grymforge"],
    ["Grym: Kill Nere", 243, "grymforge"],
    ["Grym: Return Nere's Head to Sovereign", 244, "grymforge"],
    ["Grym: Take Nere's Head", 245, "grymforge"],
    ["Grym: Agree to Help Barcus", 246, "grymforge"],
    ["Grym: Find Philomeen", 247, "grymforge"],
    ["Grym: Clear Rubble", 248, "grymforge"],
    ["Grym: Free the Gnomes", 249, "grymforge"],
    ["Grym: Thanked by Gnomes", 250, "grymforge"],
    ["Grym: Agree to help Brithvar", 251, "grymforge"],
    ["Grym: Kill Scrying Eye", 252, "grymforge"],
    ["Grym: Learn about Philomeen", 253, "grymforge"],
    ["Grym: Get Smokepowder from Philomeen", 254, "grymforge"],
    ["Grym: Mind-meld with Nere", 255, "grymforge"],
    ["Grym: Asked to Save Nere", 256, "grymforge"],
    ["Forge: Find Rubble", 257, "grymforge"],
    ["Forge: Clear Rubble", 258, "grymforge"],
    ["Forge: Get Past Rubble", 259, "grymforge"],
    ["Forge: Read Xargrim's Manual", 260, "grymforge"],
    ["Forge: View Dhourn's Memory Shard", 261, "grymforge"],
    ["Forge: Read Filro's Notes", 262, "grymforge"],
    ["Forge: Learn About Forge", 263, "grymforge"],
    ["Forge: Enter Forge", 264, "grymforge"],
    ["Forge: Activate Forge", 265, "grymforge"],
    ["Forge: Defeat Grym", 266, "grymforge"],
    ["Forge: Pick up Crafted Item", 267, "grymforge"],
    ["Grym: Find Trinket on Dead Gnome", 268, "grymforge"],
    ["Forge: Disable Gargoyle on Fire Bridge", 269, "grymforge"],
    ["Grym: Open Harper Stash", 270, "grymforge"],
    ["Grym: Find all Merregon Masks", 271, "grymforge"],
    ["Grym: Tell Thulla Gnomes were Rescued", 272, "grymforge"],
    ["Grym: Convince Spiders to Serve Lolth", 273, "grymforge"],
    ["Shart: Find Justiciar Bodies", 274, "grymforge"],
    ["Shart: Learn about Shar Temple", 275, "grymforge"],
    ["Shart: Discover Shar Temple is Blocked", 276, "grymforge"],
    ["Shart: Fight Fiends", 277, "grymforge"],
    ["Shart: Discuss Wolf Dream", 278, "grymforge"],
    ["Nightsong: Reach Grymforge", 279, "grymforge"],
    ["Grym: Find Monk Amulet", 280, "grymforge"],
    ["Monastery: Offer to Help Blue Jay", 281, "monastery"],
    ["Monastery: Find Eagles", 282, "monastery"],
    ["Monastery: Defeat Eagles", 283, "monastery"],
    ["Monastery: Return to Blue Jay", 284, "monastery"],
    ["Monastery: Accept Quest from Esther", 285, "monastery"],
    ["Monastery: Acquire Githyanki Egg", 286, "monastery"],
    ["Monastery: Resolve Esther's Quest", 287, "monastery"],
    ["Monastery: Find Githyanki Patrol", 288, "monastery"],
    ["Monastery: Resolve Githyanki Patrol", 289, "monastery"],
    ["Monastery: Find Directions to Creche", 290, "monastery"],
    ["Monastery: Solve Stained Glass Weapons Puzzle", 291, "monastery"],
    ["Gale: Meet Elminster", 292, "monastery"],
    ["Gale: Learn Backstory after Elminster", 293, "monastery"],
    ["Creche: Reach Creche", 294, "creche"],
    ["Creche: Directed to Infirmary", 295, "creche"],
    ["Creche: Reached Infirmary", 296, "creche"],
    ["Creche: Used Zaithisk", 297, "creche"],
    ["Creche: Defeat Inquisitor W'wargaz", 298, "creche"],
    ["Creche: Enter Captain's Office", 299, "creche"],
    ["Creche: Talk to Captain", 300, "creche"],
    ["Creche: Speak to Vlaakith", 301, "creche"],
    ["Creche: Enter Astral Prism", 302, "creche"],
    ["Creche: Speak with Dream Visitor", 303, "creche"],
    ["Creche: Leave Astral Prism", 304, "creche"],
    ["Creche: Decipher Orpheus Book 1", 305, "creche"],
    ["Creche: Decipher Orpheus Book 2", 306, "creche"],
    ["Creche: Save Boy in Combat Training", 307, "creche"]]

LOCATION_NAME_TO_ID = {item[0]: item[1] for item in LOCATION_NAME_ID_REGION}
