
# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.
LOCATION_NAME_ID_REGION = [["Tut: Learn about the Helm", 1, "tutorial"],
    ["Tut: Reach the Helm", 2, "tutorial"],
    ["Tut: Connect the Transponder", 3, "tutorial"],
    ["Tut-SH: Find Captive", 4, "tutorial"],
    ["Tut-SH: Find the Rune", 5, "tutorial"],
    ["Tut-SH: Open the Pod", 6, "tutorial"],
    ["Tut-SH: Recruit Captive", 7, "tutorial"],
    ["Beach-LZ: Talk to Lae'zel", 8, "beach"],
    ["Beach-LZ: Get the Tieflings Away", 9, "beach"],
    ["Beach-LZ: Free Lae'zel", 10, "beach"],
    ["Beach-LZ: Recruit Lae'zel", 11, "beach"],
    ["Astarion: Recruited", 12, "beach"],
    ["Tadpole: Wake on Beach", 13, "beach"],
    ["Tadpole: Talk to Lae'zel", 14, "beach"],
    ["Gale: Recruited", 15, "beach"],
    ["Gale: Died", 16, "beach"],
    ["Gale: Listened to Projection", 17, "beach"],
    ["Gale: Opened Pouch", 18, "beach"],
    ["Gale: Played Flute", 19, "beach"],
    ["Gale: Told Mephit his Name", 20, "beach"],
    ["Gale: Resurrected", 21, "beach"],
    ["Plot-Art: Notice Artefact", 22, "beach"],
    ["Shart: Recruit Shadowheart", 23, "beach"],
    ["Shart: Resolve Camp Fight (both live)", 24, "beach"],
    ["Tadpole: Learn About Creche", 25, "beach"],
    ["Crypt: Learn about Crypt", 26, "crypt"],
    ["Crypt: Enter Crypt", 27, "crypt"],
    ["Crypt: Find Sarcophagus", 28, "crypt"],
    ["Crypt: Open Sarcophagus", 29, "crypt"],
    ["Grove-Thief: Discover Pickpocketing", 30, "grove"],
    ["Grove-Thief: Learn About Hideout", 31, "grove"],
    ["Grove-Thief: Enter Hideout", 32, "grove"],
    ["Grove-Thief: Get Your Stuff Back", 33, "grove"],
    ["Tadpole: Learn about Nettie", 34, "grove"],
    ["Tadpole: Learn about Halsin", 35, "grove"],
    ["Tadpole: Learn about Priestess Gut", 36, "grove"],
    ["Tadpole: See True Soul Meld/Tadpole", 37, "grove"],
    ["Tadpole-Nettie: Talk to Nettie", 38, "grove"],
    ["Tadpole-Nettie: Be Poisoned by Nettie", 39, "grove"],
    ["Tadpole-Nettie: Learn about Antidote", 40, "grove"],
    ["Tadpole-Nettie: Cure the Poison", 41, "grove"],
    ["Grove-Harpy: Hear Harpy Song", 42, "grove"],
    ["Grove-Harpy: Find Child", 43, "grove"],
    ["Grove-Harpy: Defeat Harpies", 44, "grove"],
    ["Grove-Harpy: Discover Hideout Password", 45, "grove"],
    ["Grove-Harpy: Tell password to Doni", 46, "grove"],
    ["Grove-Harpy: Meet Mol", 47, "grove"],
    ["Grove-Locket: Recover Locket", 48, "grove"],
    ["Grove-Locket: Return Locket", 49, "grove"],
    ["Grove-Snake: Learn about Arabella", 50, "grove"],
    ["Grove-Snake: Find Arabella", 51, "grove"],
    ["Grove-Snake: Resolve Arabella's Situation", 52, "grove"],
    ["Grove-Snake: Talk to Arabella's Parents", 53, "grove"],
    ["Grove-Kagha: Talk to Zevlor about Kagha", 54, "grove"],
    ["Grove-Kagha: Meet Kagha", 55, "grove"],
    ["Grove-Kagha: Find Note in Grove", 56, "grove"],
    ["Grove-Kagha: Get past Guards", 57, "grove"],
    ["Grove-Kagha: Talk to Rath", 58, "grove"],
    ["Lae'zel: Find out about Zorru", 59, "grove"],
    ["Lae'zel: Talk to Zorru", 60, "grove"],
    ["Shart: See Wound", 61, "grove"],
    ["Wyll: Recruited", 62, "grove"],
    ["Grove-Sazza: Keep Sazza Alive", 63, "grove"],
    ["Grove-Sazza: Free Sazza", 64, "grove"],
    ["Grove-Sazza: Escort Sazza out", 65, "grove"],
    ["Grove-Idol: Get Asked to Steal the Idol", 66, "grove"],
    ["Shart: Discuss Wound", 67, "grove"],
    ["Shart: Learn about Wolf Phobia", 68, "grove"],
    ["Shart: Discuss Wolf Phobia", 69, "grove"],
    ["Shart: Learn about BG Mission", 70, "grove"],
    ["Grove: Rescue Nadira", 71, "grove"],
    ["Grove: Open the Vault", 72, "grove"],
    ["Grove: Move Tuffet", 73, "grove"],
    ["Grove: Save Findal", 74, "grove"],
    ["Grove: Train Guex", 75, "grove"],
    ["Grove: Loot Haystack", 76, "grove"],
    ["Grove: Convince Rolan to Stay", 77, "grove"],
    ["Grove: Make Friends with Mol", 78, "grove"],
    ["Grove: Help Alfira with her Song", 79, "grove"],
    ["Tadpole: Learned about Ethel", 80, "grove"],
    ["Village-Book: Learn about Lab", 81, "blighted_village"],
    ["Village-Book: Find Lab", 82, "blighted_village"],
    ["Village-Book: Find Tome", 83, "blighted_village"],
    ["Village-Book: Find Gem", 84, "blighted_village"],
    ["Village-Book: Unlock Tome", 85, "blighted_village"],
    ["Village-Book: Read Tome", 86, "blighted_village"],
    ["Village-Book: Learn about Gem", 87, "blighted_village"],
    ["Village-Forge: Find Journal", 88, "blighted_village"],
    ["Village-Forge: Find Plans", 89, "blighted_village"],
    ["Village-Gnome: Find Windmill", 90, "blighted_village"],
    ["Village-Gnome: Talk to Goblins", 91, "blighted_village"],
    ["Village-Gnome: Get Rid of Goblins", 92, "blighted_village"],
    ["Village-Gnome: Stop Windmill", 93, "blighted_village"],
    ["Village-Gnome: Free Gnome", 94, "blighted_village"],
    ["Village-Gnome: Talk to Barcus", 95, "blighted_village"],
    ["Tadpole: Used Illithid Persuasion", 96, "blighted_village"],
    ["Tadpole: Found a Tadpole", 97, "blighted_village"],
    ["Village: Tame Scratch", 98, "blighted_village"],
    ["Gobs: Tame Owlbear Cub", 99, "goblin_camp"],
    ["Village: Open Selune's Stash", 100, "blighted_village"],
    ["Village-Book: Open Lab Mirror", 101, "blighted_village"],
    ["Gobs-Halsin: Found Halsin", 102, "goblin_camp"],
    ["Gobs-Halsin: Tell Tieflings about Halsin's Freedom", 103, "goblin_camp"],
    ["Gobs-Halsin: Celebrate with Tieflings", 104, "goblin_camp"],
    ["Gobs-Halsin: Tieflings left for Baldur's Gate", 105, "goblin_camp"],
    ["Gobs: Arrive at Goblin Camp", 106, "goblin_camp"],
    ["Gobs-Halsin: Defeated all Goblin Leaders", 107, "goblin_camp"],
    ["Gobs: Kill Priestess Gut", 108, "goblin_camp"],
    ["Gobs: Kill Dror Ragzlin", 109, "goblin_camp"],
    ["Gobs: Defeat (Knock Out) Minthara", 110, "goblin_camp"],
    ["Gobs: Learn the Priestess' Name", 111, "goblin_camp"],
    ["Gobs: Learn the Drow's Name", 112, "goblin_camp"],
    ["Gobs: Learn the King's Name", 113, "goblin_camp"],
    ["Gobs-Halsin: Tell Halsin about Victory", 114, "goblin_camp"],
    ["Gobs-Halsin: Learn Halsin is a Bear", 115, "goblin_camp"],
    ["Gobs-Halsin: Learn Halsin is Missing", 116, "goblin_camp"],
    ["Gobs-Halsin: Get Reward from Rath", 117, "goblin_camp"],
    ["Grove-Sazza: Find Sazza at Minthara", 118, "goblin_camp"],
    ["Grove-Sazza: Save Sazza Again", 119, "goblin_camp"],
    ["Gobs-Volo: Watch Volo get Escorted Away", 120, "goblin_camp"],
    ["Gobs-Volo: Find Volo in Cage", 121, "goblin_camp"],
    ["Gobs-Volo: Free Volo", 122, "goblin_camp"],
    ["Gobs-Volo: Meet Volo in Camp", 123, "goblin_camp"],
    ["Grove-Idol: Steal the Idol", 124, "goblin_camp"],
    ["Grove-Idol: Give Idol to Mol", 125, "goblin_camp"],
    ["Gobs-Nightsong: Find Clues to Nightsong", 126, "goblin_camp"],
    ["Plot-Art: Hear Minthara talk about Artefact", 127, "goblin_camp"],
    ["Plot-Art: Hear Ragzlin talk about Artefact", 128, "goblin_camp"],
    ["Tadpole: Told by Guardian to find Tadpoles", 129, "goblin_camp"],
    ["Tadpole: Guardian Suggests Consuming Tadpole", 130, "goblin_camp"],
    ["Gobs: Follow Gut to her Quarters", 131, "goblin_camp"],
    ["Gobs-Halsin: Tell Ormn that Halsin was Saved", 132, "goblin_camp"],
    ["Gobs: Win the Chicken Chase", 133, "goblin_camp"],
    ["Gobs: Crush Crusher (in dialogue)", 134, "goblin_camp"],
    ["Gobs: Scry with Ragzlin", 135, "goblin_camp"],
    ["Gobs: Free Brakkal", 136, "goblin_camp"],
    ["Gobs: Get Book from Piddle", 137, "goblin_camp"],
    ["Gobs: Experience Abdirak's Penance", 138, "goblin_camp"],
    ["Gobs: Find Moon Puzzle in Temple", 139, "goblin_camp"],
    ["Gobs: Solve Moon Puzzle in Temple", 140, "goblin_camp"],
    ["Gobs: Free Liam", 141, "goblin_camp"],
    ["Gale: Told about Hunger", 142, "waukeen"],
    ["Gale: Fed an Item", 143, "waukeen"],
    ["Waukeen-Zhent: Meet Oskar", 144, "waukeen"],
    ["Waukeen-Zhent: Agree to Free Oskar", 145, "waukeen"],
    ["Waukeen-Zhent: Learn Oskar's Price", 146, "waukeen"],
    ["Waukeen-Zhent: Free Oskar", 147, "waukeen"],
    ["Waukeen-Fire: Notice Fire", 148, "waukeen"],
    ["Waukeen-Fire: Enter Inn", 149, "waukeen"],
    ["Waukeen-Fire: Find Benryn", 150, "waukeen"],
    ["Waukeen-Fire: Find Florrick", 151, "waukeen"],
    ["Waukeen-Fire: Rescue Benryn", 152, "waukeen"],
    ["Waukeen-Fire: Rescue Florrick", 153, "waukeen"],
    ["Waukeen-Fire: Learn about Duke", 154, "waukeen"],
    ["Waukeen-Fire: Accept Mission to Rescue Duke", 155, "waukeen"],
    ["Waukeen-Fire: Learn about Benryn's Wife", 156, "waukeen"],
    ["Waukeen-Fire: Show Benryn his Wife", 157, "waukeen"],
    ["Waukeen-Fire: Learn about Dowry", 158, "waukeen"],
    ["Waukeen-Fire: Recover Dowry", 159, "waukeen"],
    ["Waukeen-Fire: Return Dowry", 160, "waukeen"],
    ["Karlach-Tyr: Meet Karlach", 161, "waukeen"],
    ["Karlach-Tyr: Learn Anders Follows Zariel", 162, "waukeen"],
    ["Karlach-Tyr: Recruit Karlach", 163, "waukeen"],
    ["Karlach-Tyr: Kill the Paladins", 164, "waukeen"],
    ["Waukeen-Zhent: Find Caravan", 165, "waukeen"],
    ["Waukeen-Zhent: Notice Struggle", 166, "waukeen"],
    ["Waukeen-Zhent: Kill Gnolls", 167, "waukeen"],
    ["Waukeen-Zhent: Rescue Agents", 168, "waukeen"],
    ["Waukeen-Zhent: Learn Password", 169, "waukeen"],
    ["Waukeen-Zhent: Enter Zhentarim Hideout", 170, "waukeen"],
    ["Waukeen-Zhent: Return Cargo", 171, "waukeen"],
    ["Karlach-Heart: Recruit Karlach", 172, "waukeen"],
    ["Karlach-Heart: Learn about Heart Upgrades", 173, "waukeen"],
    ["Karlach-Heart: Introduce Karlach to Dammon", 174, "waukeen"],
    ["Karlach-Heart: Get First Heart Upgrade", 175, "waukeen"],
    ["Lae'zel: See Dragon Rider", 176, "waukeen"],
    ["Lae'zel: Deal with Patrol", 177, "waukeen"],
    ["Lae'zel: Learn Creche Location", 178, "waukeen"],
    ["Wyll: Resolved Conflict with Karlach", 179, "waukeen"],
    ["Wyll: Meet Mizora", 180, "waukeen"],
    ["Wyll: Learn Wyll's Father", 181, "waukeen"],
    ["Shart: Learn about Shar Worship", 182, "waukeen"],
    ["Grove-Kagha: Find Note in Swamp", 183, "hag"],
    ["Grove-Kagha: Confront Kagha", 184, "hag"],
    ["Grove-Kagha: Kill the Shadow Druids", 185, "hag"],
    ["Grove-Kagha: Return to Zevlor", 186, "hag"],
    ["Astarion: Learned Vampire", 187, "hag"],
    ["Astarion: Learned Backstory", 188, "hag"],
    ["Astarion: Chat about Tadpole", 189, "hag"],
    ["Astarion: Met Gandrel", 190, "hag"],
    ["Hag: Find Mayrina's Brothers", 191, "hag"],
    ["Hag: Meet Mayrina", 192, "hag"],
    ["Hag: Force Ethel into her Lair", 193, "hag"],
    ["Hag: Enter Ethel's Lair", 194, "hag"],
    ["Hag: Fight Ethel in her Lair", 195, "hag"],
    ["Hag: Rescue Mayrina", 196, "hag"],
    ["Hag: Find the Bitter Divorce", 197, "hag"],
    ["Hag: Send Mayrina off to Baldur's Gate", 198, "hag"],
    ["Tadpole: Learned about Moonrise Towers", 199, "underdark"],
    ["Grotto: Meet Omeluum", 200, "underdark"],
    ["Grotto: Tell Blurg about Tadpole", 201, "underdark"],
    ["Grotto: Get Omeluum's Recipe", 202, "underdark"],
    ["Grotto: Find Timmask Spores", 203, "underdark"],
    ["Grotto: Find Tongue of Madness", 204, "underdark"],
    ["Grotto: Drink Omeluum's Potion", 205, "underdark"],
    ["Grotto: Get Mind Shielding Ring", 206, "underdark"],
    ["Underdark: Find Sussur Bark", 207, "underdark"],
    ["Underdark: Learn about Sussur Bark", 208, "underdark"],
    ["Underdark: Forge Masterwork", 209, "underdark"],
    ["Grotto: Talk to Derryth", 210, "underdark"],
    ["Grotto: Find Baelen", 211, "underdark"],
    ["Grotto: Tell Derryth the Result", 212, "underdark"],
    ["Grotto: Agree to Kill Duergar", 213, "underdark"],
    ["Grotto: Find Duergar", 214, "underdark"],
    ["Grotto: Kill Duergar", 215, "underdark"],
    ["Grotto: Tell Glut about Duergar", 216, "underdark"],
    ["Grotto: Hear Glut's Plan", 217, "underdark"],
    ["Grotto: Decide which Sovereign to Support", 218, "underdark"],
    ["Grotto: Reward for Killing Sovereign", 219, "underdark"],
    ["Grotto: Kill one of the Sovereigns", 220, "underdark"],
    ["Grotto: Enter Guardian Gate", 221, "underdark"],
    ["Grotto: Get Reward for Duergar", 222, "underdark"],
    ["Grotto: Accept Quest to Kill Nere", 223, "underdark"],
    ["Grotto: Cure Thulla", 224, "underdark"],
    ["Grotto: Meet Thulla", 225, "underdark"],
    ["Underdark: Find Runaway", 226, "underdark"],
    ["Underdark: Get Told about Runaway", 227, "underdark"],
    ["Underdark: Get Boots", 228, "underdark"],
    ["Gale: Fed a Second Item", 229, "waukeen"],
    ["Gale: Fed a Third Item", 230, "waukeen"],
    ["Gale: Told Backstory", 231, "waukeen"],
    ["Grotto: Asked to Save Gnomes", 232, "underdark"],
    ["Underdark: Activate Arcane Tower", 233, "underdark"],
    ["Underdark: Put Flowers on the Pet Grave near Arcane Tower", 234, "underdark"],
    ["Underdark: Identify Chest of the Mundane", 235, "underdark"],
    ["Underdark: Get Phalar Aluve", 236, "underdark"],
    ["Nightsong: Enter Underdark", 237, "underdark"],
    ["Grym: Lead Duergar Mutiny", 238, "grymforge"],
    ["Grym: Take Nere's Head", 239, "grymforge"],
    ["Grym: Kill Nere", 240, "grymforge"],
    ["Grym: Return Nere's Head to Sovereign", 241, "grymforge"],
    ["Grym: Take Nere's Head", 242, "grymforge"],
    ["Grym: Agree to Help Barcus", 243, "grymforge"],
    ["Grym: Find Philomeen", 244, "grymforge"],
    ["Grym: Clear Rubble", 245, "grymforge"],
    ["Grym: Free the Gnomes", 246, "grymforge"],
    ["Grym: Thanked by Gnomes", 247, "grymforge"],
    ["Grym: Agree to help Brithvar", 248, "grymforge"],
    ["Grym: Kill Scrying Eye", 249, "grymforge"],
    ["Grym: Learn about Philomeen", 250, "grymforge"],
    ["Grym: Get Smokepowder from Philomeen", 251, "grymforge"],
    ["Grym: Mind-meld with Nere", 252, "grymforge"],
    ["Grym: Asked to Save Nere", 253, "grymforge"],
    ["Forge: Find Rubble", 254, "grymforge"],
    ["Forge: Clear Rubble", 255, "grymforge"],
    ["Forge: Get Past Rubble", 256, "grymforge"],
    ["Forge: Read Xargrim's Manual", 257, "grymforge"],
    ["Forge: View Dhourn's Memory Shard", 258, "grymforge"],
    ["Forge: Read Filro's Notes", 259, "grymforge"],
    ["Forge: Learn About Forge", 260, "grymforge"],
    ["Forge: Enter Forge", 261, "grymforge"],
    ["Forge: Activate Forge", 262, "grymforge"],
    ["Forge: Defeat Grym", 263, "grymforge"],
    ["Forge: Pick up Crafted Item", 264, "grymforge"],
    ["Grym: Find Trinket on Dead Gnome", 265, "grymforge"],
    ["Forge: Disable Gargoyle on Fire Bridge", 266, "grymforge"],
    ["Grym: Open Harper Stash", 267, "grymforge"],
    ["Grym: Find all Merregon Masks", 268, "grymforge"],
    ["Grym: Tell Thulla Gnomes were Rescued", 269, "grymforge"],
    ["Grym: Convince Spiders to Serve Lolth", 270, "grymforge"],
    ["Shart: Find Justiciar Bodies", 271, "grymforge"],
    ["Shart: Learn about Shar Temple", 272, "grymforge"],
    ["Shart: Discover Shar Temple is Blocked", 273, "grymforge"],
    ["Shart: Fight Fiends", 274, "grymforge"],
    ["Shart: Discuss Wolf Dream", 275, "grymforge"],
    ["Nightsong: Reach Grymforge", 276, "grymforge"],
    ["Grym: Find Monk Amulet", 277, "grymforge"],
    ["Monastery: Offer to Help Blue Jay", 278, "monastery"],
    ["Monastery: Find Eagles", 279, "monastery"],
    ["Monastery: Defeat Eagles", 280, "monastery"],
    ["Monastery: Return to Blue Jay", 281, "monastery"],
    ["Monastery: Accept Quest from Esther", 282, "monastery"],
    ["Monastery: Acquire Githyanki Egg", 283, "monastery"],
    ["Monastery: Resolve Esther's Quest", 284, "monastery"],
    ["Monastery: Find Githyanki Patrol", 285, "monastery"],
    ["Monastery: Resolve Githyanki Patrol", 286, "monastery"],
    ["Monastery: Find Directions to Creche", 287, "monastery"],
    ["Monastery: Solve Stained Glass Weapons Puzzle", 288, "monastery"],
    ["Gale: Meet Elminster", 289, "monastery"],
    ["Gale: Learn Backstory after Elminster", 290, "monastery"],
    ["Creche: Reach Creche", 291, "creche"],
    ["Creche: Directed to Infirmary", 292, "creche"],
    ["Creche: Reached Infirmary", 293, "creche"],
    ["Creche: Used Zaithisk", 294, "creche"],
    ["Creche: Defeat Inquisitor W'wargaz", 295, "creche"],
    ["Creche: Enter Captain's Office", 296, "creche"],
    ["Creche: Talk to Captain", 297, "creche"],
    ["Creche: Speak to Vlaakith", 298, "creche"],
    ["Creche: Enter Astral Prism", 299, "creche"],
    ["Creche: Speak with Dream Visitor", 300, "creche"],
    ["Creche: Leave Astral Prism", 301, "creche"],
    ["Creche: Decipher Orpheus Book 1", 302, "creche"],
    ["Creche: Decipher Orpheus Book 2", 303, "creche"],
    ["Creche: Save Boy in Combat Training", 304, "creche"],





    ["Tut: Kill Devil 1", 10001,"tutorial"],
    ["Tut: Kill Devil 2", 10002,"tutorial"],
    ["Tut: Kill Devil 3", 10003,"tutorial"],
    ["Tut: Kill Devil Bkup 1", 10004,"tutorial"],
    ["Tut: Kill Devil Bkup 2", 10005,"tutorial"],
    ["Tut: Kill Devil Bkup 3", 10006,"tutorial"],
    ["Tut: Kill Imp 1", 10007,"tutorial"],
    ["Tut: Kill Imp 2", 10008,"tutorial"],
    ["Tut: Kill Imp 3", 10009,"tutorial"],
    ["Beach: Kill Int Devourer 1", 10010,"beach"],
    ["Beach: Kill Int Devourer 2", 10011,"beach"],
    ["Beach: Kill Int Devourer 3", 10012,"beach"],
    ["Crypt: Kill Andorn", 10013,"crypt"],
    ["Crypt: Kill Barton", 10014,"crypt"],
    ["Crypt: Kill Cefrey", 10015,"crypt"],
    ["Crypt: Kill Haseid", 10016,"crypt"],
    ["Crypt: Kill Mari", 10017,"crypt"],
    ["Crypt: Kill Skel. Caster 1", 10018,"crypt"],
    ["Crypt: Kill Skel. Caster 2", 10019,"crypt"],
    ["Crypt: Kill Skel. Caster 3", 10020,"crypt"],
    ["Crypt: Kill Skel. Caster 4", 10021,"crypt"],
    ["Crypt: Kill Skel. Melee", 10022,"crypt"],
    ["Crypt: Kill Torgga", 10023,"crypt"],
    ["Grove: Kill Bugbear", 10024,"grove"],
    ["Grove: Kill Goblin Brawler 1", 10025,"grove"],
    ["Grove: Kill Goblin Brawler 2", 10026,"grove"],
    ["Grove: Kill Goblin Tracker 1", 10027,"grove"],
    ["Grove: Kill Goblin Tracker 2", 10028,"grove"],
    ["Grove: Kill Goblin Tracker 3", 10029,"grove"],
    ["Grove: Kill Worg", 10030,"grove"],
    ["Grove: Kill Za'krug", 10031,"grove"],
    ["Village: Kill Brawler Brek", 10032,"blighted_village"],
    ["Village: Kill Chock", 10033,"blighted_village"],
    ["Village: Kill Ettercap 1", 10034,"blighted_village"],
    ["Village: Kill Ettercap 2", 10035,"blighted_village"],
    ["Village: Kill Fank", 10036,"blighted_village"],
    ["Village: Kill Goblin Booyahg 1", 10037,"blighted_village"],
    ["Village: Kill Goblin Booyahg 2", 10038,"blighted_village"],
    ["Village: Kill Goblin Brawler", 10039,"blighted_village"],
    ["Village: Kill Goblin Sharp-Eye 1", 10040,"blighted_village"],
    ["Village: Kill Goblin Sharp-Eye 2", 10041,"blighted_village"],
    ["Village: Kill Goblin Tracker 1", 10042,"blighted_village"],
    ["Village: Kill Goblin Tracker 2", 10043,"blighted_village"],
    ["Village: Kill Goblin Warrior 1", 10044,"blighted_village"],
    ["Village: Kill Goblin Warrior 2", 10045,"blighted_village"],
    ["Village: Kill Lump the Enlightened", 10046,"blighted_village"],
    ["Village: Kill Sleeping Bugbear", 10047,"blighted_village"],
    ["Village: Kill Tracker Slice", 10048,"blighted_village"],
    ["Village: Kill Well Spider 1", 10049,"blighted_village"],
    ["Village: Kill Well Spider 2", 10050,"blighted_village"],
    ["Village: Kill Well Spider 3", 10051,"blighted_village"],
    ["Village: Kill Well Spider 4", 10052,"blighted_village"],
    ["Village: Kill Well Spider Queen", 10053,"blighted_village"],
    ["Village: Kill Andrick", 10054,"blighted_village"],
    ["Village: Kill Brynna", 10055,"blighted_village"],
    ["Gobs: Kill Bao'ek'nuk", 10056,"goblin_camp"],
    ["Gobs: Kill Booyahg Culk", 10057,"goblin_camp"],
    ["Gobs: Kill Booyahg Gnat", 10058,"goblin_camp"],
    ["Gobs: Kill Booyahg Piddle", 10059,"goblin_camp"],
    ["Gobs: Kill Booyahg Shekt", 10060,"goblin_camp"],
    ["Gobs: Kill Brakkal", 10061,"goblin_camp"],
    ["Gobs: Kill Brawler Gurd", 10062,"goblin_camp"],
    ["Gobs: Kill Brawler Rot", 10063,"goblin_camp"],
    ["Gobs: Kill Brawler Tiny", 10064,"goblin_camp"],
    ["Gobs: Kill Crusher", 10065,"goblin_camp"],
    ["Gobs: Kill Devout Cry", 10066,"goblin_camp"],
    ["Gobs: Kill Devout Mezzka", 10067,"goblin_camp"],
    ["Gobs: Kill Devout Mrak", 10068,"goblin_camp"],
    ["Gobs: Kill Devout Muzul", 10069,"goblin_camp"],
    ["Gobs: Kill Devout Wasp", 10070,"goblin_camp"],
    ["Gobs: Kill Dror Ragzlin", 10071,"goblin_camp"],
    ["Gobs: Kill Grat the Trader", 10072,"goblin_camp"],
    ["Gobs: Kill Gribbo", 10073,"goblin_camp"],
    ["Gobs: Kill Guard Gurgon", 10074,"goblin_camp"],
    ["Gobs: Kill Klaw", 10075,"goblin_camp"],
    ["Gobs: Kill Krolla", 10076,"goblin_camp"],
    ["Gobs: Kill Larger Giant Spider", 10077,"goblin_camp"],
    ["Gobs: Kill Lookout Grush", 10078,"goblin_camp"],
    ["Gobs: Kill Polma", 10079,"goblin_camp"],
    ["Gobs: Kill Rozzak", 10080,"goblin_camp"],
    ["Gobs: Kill Scrying Eye", 10081,"goblin_camp"],
    ["Gobs: Kill Sentinel Olak", 10082,"goblin_camp"],
    ["Gobs: Kill Sharp Eye Zami", 10083,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Aggy", 10084,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Breg", 10085,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Eef", 10086,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Gruz", 10087,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Mirg", 10088,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Nass", 10089,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Neem", 10090,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Nozk", 10091,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Raagg", 10092,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Roo", 10093,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Sluck", 10094,"goblin_camp"],
    ["Gobs: Kill Sharp-Eye Snurd", 10095,"goblin_camp"],
    ["Gobs: Kill Skrut", 10096,"goblin_camp"],
    ["Gobs: Kill Small Klaw", 10097,"goblin_camp"],
    ["Gobs: Kill Smaller Giant Spider", 10098,"goblin_camp"],
    ["Gobs: Kill Stimk", 10099,"goblin_camp"],
    ["Gobs: Kill Teghun", 10100,"goblin_camp"],
    ["Gobs: Kill Torturer Spike", 10101,"goblin_camp"],
    ["Gobs: Kill Tracker Azak", 10102,"goblin_camp"],
    ["Gobs: Kill Tracker Bal", 10103,"goblin_camp"],
    ["Gobs: Kill Tracker Dullwill", 10104,"goblin_camp"],
    ["Gobs: Kill Tracker Fezk", 10105,"goblin_camp"],
    ["Gobs: Kill Tracker Grikka", 10106,"goblin_camp"],
    ["Gobs: Kill Tracker Kirz", 10107,"goblin_camp"],
    ["Gobs: Kill Tracker Klagga", 10108,"goblin_camp"],
    ["Gobs: Kill Tracker Puli", 10109,"goblin_camp"],
    ["Gobs: Kill Tracker Rindle", 10110,"goblin_camp"],
    ["Gobs: Kill Tracker Tak", 10111,"goblin_camp"],
    ["Gobs: Kill Tracker Tizg", 10112,"goblin_camp"],
    ["Gobs: Kill Tracker Tozad", 10113,"goblin_camp"],
    ["Gobs: Kill True Soul Gut", 10114,"goblin_camp"],
    ["Gobs: Kill Warlock Bolt", 10115,"goblin_camp"],
    ["Gobs: Kill Warlock Greez", 10116,"goblin_camp"],
    ["Gobs: Kill Warlock Gurk", 10117,"goblin_camp"],
    ["Gobs: Kill Warlock Tud", 10118,"goblin_camp"],
    ["Gobs: Kill Warrior Bez", 10119,"goblin_camp"],
    ["Gobs: Kill Warrior Clack", 10120,"goblin_camp"],
    ["Gobs: Kill Warrior Druk", 10121,"goblin_camp"],
    ["Gobs: Kill Warrior Huk", 10122,"goblin_camp"],
    ["Gobs: Kill Warrior Nrog", 10123,"goblin_camp"],
    ["Gobs: Kill Warrior Puce", 10124,"goblin_camp"],
    ["Gobs: Kill Warrior Sul", 10125,"goblin_camp"],
    ["Gobs: Kill Warrior Trinzas", 10126,"goblin_camp"],
    ["Gobs: Kill Zurga", 10127,"goblin_camp"],
    ["Waukeen: Kill Flind", 10128,"waukeen"],
    ["Waukeen: Kill Gnoll Fang of Yeenoghu", 10129,"waukeen"],
    ["Waukeen: Kill Gnoll Flesh Gnawer", 10130,"waukeen"],
    ["Waukeen: Kill Gnoll Hunter 1", 10131,"waukeen"],
    ["Waukeen: Kill Gnoll Hunter 2", 10132,"waukeen"],
    ["Waukeen: Kill Gnoll Hunter 3", 10133,"waukeen"],
    ["Waukeen: Kill Hyena 1", 10134,"waukeen"],
    ["Waukeen: Kill Hyena 2", 10135,"waukeen"],
    ["Waukeen: Kill Hyena 3", 10136,"waukeen"],
    ["Waukeen: Kill Hyena 4", 10137,"waukeen"],
    ["Waukeen: Kill Hyena 5", 10138,"waukeen"],
    ["Waukeen: Kill Hyena 6", 10139,"waukeen"],
    ["Waukeen: Kill Hyena 7", 10140,"waukeen"],
    ["Waukeen: Kill Hyena 8", 10141,"waukeen"],
    ["Waukeen: Kill Hyena 9", 10142,"waukeen"],
    ["Waukeen: Kill Hyena at Cave 1", 10143,"waukeen"],
    ["Waukeen: Kill Hyena at Cave 2", 10144,"waukeen"],
    ["Waukeen: Kill Paladin TBD 1", 10145,"waukeen"],
    ["Waukeen: Kill Paladin TBD 2", 10146,"waukeen"],
    ["Waukeen: Kill Paladin TBD 3", 10147,"waukeen"],
    ["Hag: Kill Auntie Ethel", 10148,"hag"],
    ["Hag: Kill Mephit 1", 10149,"hag"],
    ["Hag: Kill Mephit 2", 10150,"hag"],
    ["Hag: Kill Mephit 3", 10151,"hag"],
    ["Hag: Kill Mephit 4", 10152,"hag"],
    ["Hag: Kill Redcap 1", 10153,"hag"],
    ["Hag: Kill Redcap 2", 10154,"hag"],
    ["Hag: Kill Redcap 3", 10155,"hag"],
    ["Hag: Kill Redcap 4", 10156,"hag"],
    ["Hag: Kill Wood Woad 1", 10157,"hag"],
    ["Hag: Kill Wood Woad 2", 10158,"hag"],
    ["Underdark: Kill Animated Armor 1", 10159,"underdark"],
    ["Underdark: Kill Animated Armor 2", 10160,"underdark"],
    ["Underdark: Kill Animated Armor 3", 10161,"underdark"],
    ["Underdark: Kill Animated Armor 4", 10162,"underdark"],
    ["Underdark: Kill Arcane Turret 1", 10163,"underdark"],
    ["Underdark: Kill Arcane Turret 2", 10164,"underdark"],
    ["Underdark: Kill Arcane Turret 3", 10165,"underdark"],
    ["Underdark: Kill Arcane Turret 4", 10166,"underdark"],
    ["Underdark: Kill Bernard", 10167,"underdark"],
    ["Underdark: Kill Bulette", 10168,"underdark"],
    ["Underdark: Kill Filro the Forgotten", 10169,"underdark"],
    ["Underdark: Kill Fort Minotaur", 10170,"underdark"],
    ["Underdark: Kill Gekh Coal", 10171,"underdark"],
    ["Underdark: Kill Holvik", 10172,"underdark"],
    ["Underdark: Kill Hook Horror 1", 10173,"underdark"],
    ["Underdark: Kill Hook Horror 2", 10174,"underdark"],
    ["Underdark: Kill Hook Horror 3", 10175,"underdark"],
    ["Underdark: Kill Hook Horror 4", 10176,"underdark"],
    ["Underdark: Kill Lurgan", 10177,"underdark"],
    ["Underdark: Kill Novice Garmor", 10178,"underdark"],
    ["Underdark: Kill Sovereign Glut", 10179,"underdark"],
    ["Underdark: Kill Spectator", 10180,"underdark"],
    ["Forge: Kill Animated Armor 1", 10181,"grymforge"],
    ["Forge: Kill Animated Armor 2", 10182,"grymforge"],
    ["Forge: Kill Animated Armor 3", 10183,"grymforge"],
    ["Forge: Kill Animated Armor 4", 10184,"grymforge"],
    ["Forge: Kill Grym", 10185,"grymforge"],
    ["Forge: Kill Hellsboar 1", 10186,"grymforge"],
    ["Forge: Kill Hellsboar 2", 10187,"grymforge"],
    ["Forge: Kill Hellsboar 3", 10188,"grymforge"],
    ["Forge: Kill Magma Mephit 1", 10189,"grymforge"],
    ["Forge: Kill Magma Mephit 2", 10190,"grymforge"],
    ["Forge: Kill Magma Mephit 3", 10191,"grymforge"],
    ["Forge: Kill Magma Mephit 4", 10192,"grymforge"],
    ["Forge: Kill Magma Mephit 5", 10193,"grymforge"],
    ["Forge: Kill Magma Mephit 6", 10194,"grymforge"],
    ["Forge: Kill Magma Mephit 7", 10195,"grymforge"],
    ["Forge: Kill Magma Mephit 8", 10196,"grymforge"],
    ["Forge: Kill Magma Mephit 9", 10197,"grymforge"],
    ["Forge: Kill Merregon Legionnaire", 10198,"grymforge"],
    ["Grym: Kill Corsair Greymon", 10199,"grymforge"],
    ["Grym: Kill Dalthar", 10200,"grymforge"],
    ["Grym: Kill Drar", 10201,"grymforge"],
    ["Grym: Kill Grundril", 10202,"grymforge"],
    ["Grym: Kill Headmaster Skarjall", 10203,"grymforge"],
    ["Grym: Kill Mimic 1", 10204,"grymforge"],
    ["Grym: Kill Mimic 2", 10205,"grymforge"],
    ["Grym: Kill Mimic 3", 10206,"grymforge"],
    ["Grym: Kill Mind Master Dunnol", 10207,"grymforge"],
    ["Grym: Kill Mind Master Fonmara", 10208,"grymforge"],
    ["Grym: Kill Morgya", 10209,"grymforge"],
    ["Grym: Kill Nere", 10210,"grymforge"],
    ["Grym: Kill Ochre Jelly 1", 10211,"grymforge"],
    ["Grym: Kill Ochre Jelly 2", 10212,"grymforge"],
    ["Grym: Kill Ochre Jelly 3", 10213,"grymforge"],
    ["Grym: Kill Scrying Eye", 10214,"grymforge"],
    ["Grym: Kill Sergeant Thrinn", 10215,"grymforge"],
    ["Monastery: Kill Death Sheperd 1", 10216,"monastery"],
    ["Monastery: Kill Death Sheperd 2", 10217,"monastery"],
    ["Monastery: Kill Ghast", 10218,"monastery"],
    ["Monastery: Kill Ghoul 1", 10219,"monastery"],
    ["Monastery: Kill Ghoul 2", 10220,"monastery"],
    ["Monastery: Kill Ghoul 3", 10221,"monastery"],
    ["Monastery: Kill Ghoul 4", 10222,"monastery"],
    ["Monastery: Kill Giant Eagle 1", 10223,"monastery"],
    ["Monastery: Kill Giant Eagle 2", 10224,"monastery"],
    ["Monastery: Kill Gremishka 1", 10225,"monastery"],
    ["Monastery: Kill Gremishka 2", 10226,"monastery"],
    ["Monastery: Kill Gremishka 3", 10227,"monastery"],
    ["Monastery: Kill Gremishka 4", 10228,"monastery"],
    ["Monastery: Kill Gremishka 5", 10229,"monastery"],
    ["Monastery: Kill Gremishka 6", 10230,"monastery"],
    ["Monastery: Kill Gremishka 7", 10231,"monastery"],
    ["Monastery: Kill Gremishka 8", 10232,"monastery"],
    ["Monastery: Kill Gremishka 9", 10233,"monastery"],
    ["Monastery: Kill Guardian of Faith", 10234,"monastery"],
    ["Monastery: Kill Kobold Inventor", 10235,"monastery"],
    ["Monastery: Kill Kobold Looter 1", 10236,"monastery"],
    ["Monastery: Kill Kobold Looter 2", 10237,"monastery"],
    ["Monastery: Kill Kobold Looter 3", 10238,"monastery"],
    ["Monastery: Kill Kobold Looter 4", 10239,"monastery"],
    ["Monastery: Kill Kobold Looter 5", 10240,"monastery"],
    ["Monastery: Kill Kobold Looter 6", 10241,"monastery"],
    ["Monastery: Kill Kobold Looter 7", 10242,"monastery"],
    ["Monastery: Kill Kobold Looter in Barrel 1", 10243,"monastery"],
    ["Monastery: Kill Kobold Looter in Barrel 2", 10244,"monastery"],
    ["Monastery: Kill Kobold Looter in Barrel 3", 10245,"monastery"],
    ["Monastery: Kill Kobold Looter in Barrel 4", 10246,"monastery"],
    ["Monastery: Kill Kobold Scout 1", 10247,"monastery"],
    ["Monastery: Kill Kobold Scout 2", 10248,"monastery"],
    ["Monastery: Kill Kobold Scout 3", 10249,"monastery"],
    ["Monastery: Kill Kobold Scout 4", 10250,"monastery"],
    ["Monastery: Kill Gish For'reth", 10251,"monastery"],
    ["Monastery: Kill Raider Ghost", 10252,"monastery"],
    ["Monastery: Kill Raider Zastri", 10253,"monastery"],
    ["Monastery: Kill Sarth Baretha", 10254,"monastery"],
    ["Creche: Kill A'jak'nir Jeera", 10255,"creche"],
    ["Creche: Kill Ardent G'nuril", 10256,"creche"],
    ["Creche: Kill Ardent Jhe'rezath", 10257,"creche"],
    ["Creche: Kill Ardent Kur'ashk", 10258,"creche"],
    ["Creche: Kill Ardent Lin'a'an", 10259,"creche"],
    ["Creche: Kill Ardent Qu'th", 10260,"creche"],
    ["Creche: Kill Ardent Vraalsith", 10261,"creche"],
    ["Creche: Kill Ch'r'ai W'wargaz", 10262,"creche"],
    ["Creche: Kill D'hak", 10263,"creche"],
    ["Creche: Kill Ghustil Stornugoss", 10264,"creche"],
    ["Creche: Kill Gish Far'aag", 10265,"creche"],
    ["Creche: Kill Gish Umr'a'ac", 10266,"creche"],
    ["Creche: Kill Gremishka in a Box", 10267,"creche"],
    ["Creche: Kill Kith'rak Therezzyn", 10268,"creche"],
    ["Creche: Kill Raider Add'ath", 10269,"creche"],
    ["Creche: Kill Raider Ahu'u'rag", 10270,"creche"],
    ["Creche: Kill Raider Chy'raagh", 10271,"creche"],
    ["Creche: Kill Raider G'r'ath", 10272,"creche"],
    ["Creche: Kill Raider Jy'ir", 10273,"creche"],
    ["Creche: Kill Raider Kyrr'a'ath", 10274,"creche"],
    ["Creche: Kill Raider Ra'gur", 10275,"creche"],
    ["Creche: Kill Raider Zar'an", 10276,"creche"],
    ["Creche: Kill Sa'varsh Kethk", 10277,"creche"],
    ["Creche: Kill Ur'uth", 10278,"creche"],
    ["Creche: Kill Varsh Ko'kuu", 10279,"creche"],
    ["Creche: Kill Warrior Brelal'reth", 10280,"creche"],
    ["Creche: Kill Warrior Ith'dul", 10281,"creche"],
    ["Creche: Kill Warrior Khunaruth", 10282,"creche"],
    ["Creche: Kill Warrior Qen", 10283,"creche"],
    ["Creche: Kill Warrior Vu'un", 10284,"creche"],
    ["Creche: Kill Warrior Yr'rk", 10285,"creche"],
    ["Creche: Kill Youth Astyl", 10286,"creche"],
    ["Creche: Kill Youth Ba'akreth", 10287,"creche"],
    ["Creche: Kill Youth Dyrr'kas", 10288,"creche"],
    ["Creche: Kill Youth Mirya'al", 10289,"creche"],
    ["Creche: Kill Youth Pyrindath", 10290,"creche"],
    ["Creche: Kill Youth Qun'irel", 10291,"creche"],
    ["Creche: Kill Youth Rheg'zel", 10292,"creche"],
    ["Creche: Kill Youth Tra'an", 10293,"creche"],
    ["Creche: Kill Youth Vis'kiir", 10294,"creche"],
    ["Creche: Kill Youth Zar'a'ath", 10295,"creche"]
]

LOCATION_NAME_TO_ID = {item[0]: item[1] for item in LOCATION_NAME_ID_REGION}
